### ISSUE TITLE
Carousel block caption should not focus on block selection

### ISSUE THREAD

**Issue by richtabor** [godaddy-wordpress/coblocks#1010]
Currently, selecting the Carousel block causes the optional caption to focus - which distracts the user by having a seemingly unrelated action occur upon selecting the block.

We need to disable the auto-focus of the caption, where the focus only occurs when the user intends to add a caption.

**Comment by paranoia1906** [comment]
Related to managing focus on RichText
https://github.com/WordPress/gutenberg/issues/9740

**Comment by jrtashjian** [comment]
Closing. There is more context and info in #1149.
