### ISSUE TITLE
ISBAT ensure the integrity of the Posts block through automated tests

### ISSUE THREAD

**Issue by jrtashjian** [godaddy-wordpress/coblocks#1029]
Automated tests need to be added to the `posts` block which follow the groundwork from #835.

#### Tests Required:
- [x] The save function (server rendered block #1069)
- [x] Block transforms #1233
- [x] Block deprecation (not applicable)

#### AC
- Any attribute that modifies the serialized block output needs to have tests.
- Any existing transforms to or from a block needs to have tests (if applicable).
- Any existing block deprecations need to have tests (if applicable).

**Comment by AnthonyLedesma** [comment]
Closing this issue with the completion of #1233
