### ISSUE TITLE
Update SizeControl components to use the new reusable component

### ISSUE THREAD

**Issue by richtabor** [godaddy-wordpress/coblocks#1041]
We should attempt updating existing `SizeControl` components to use the upcoming component @jrtashjian is working on adding to replace the `ButtonGroup` type components we are using in the Posts and Carousel blocks. 

There's some logic in how some of the SizeControl components display per different alignment settings (wide or full). We need to decide if we want to maintain that logic, or bake in a way to pass that logic through the new component. 

We can remove the `SizeControl` component once it's been replaced throughout the blocks: 

**Carousel and Masonry refactors should be handled in respective refactor issues**
- [x] Carousel
- [x] Masonry
- [ ] Stacked

**Comment by jrtashjian** [comment]
This is still a valid "issue". To clarify what needs to happen here: we are replacing the `SizeControl` component with the new `OptionSelectorControl` component used in the Features, Food and Drinks, Posts, Pricing Table, Row, and Services blocks.

The three blocks listed in the issue description still require updating but the Collage and Offset gallery blocks already use this component.
