### ISSUE TITLE
Media Card - increase max width to 2560px

### ISSUE THREAD

**Issue by sweetappleuk** [godaddy-wordpress/coblocks#1080]
The media card has a max width of 2000px. Increasing this to 2560px will mean that you can create full width layouts on QHD monitors.

modify the <RangeControl> template in
src/blocks/media-card/inspector.js and modify max={ 2000 } to max={ 2560 }

**Comment by richtabor** [comment]
Hey @sweetappleuk, thanks for the insight on QHD monitors. The default value of the Media Card maxWidth is not set initially. If you simply remove that value do you get the full width layout you're looking for?

**Comment by richtabor** [comment]
Heyo @sweetappleuk, just following up here. I'd like to know that if you choose not to set a value, would you get the layout you're looking for (as it defaults to none)?

**Comment by sweetappleuk** [comment]
Apologies for the delay. Yes it does go full width. However if you enter a max-width value it is set between 400 - 2000 px. There's no Reset button. The default position of the slider is at 50%, so if you do what I did, trying to drag the slider back into the centre position you can't get to an "auto" value. So you have to manually delete the value in the input. Stupidly I didn't think of this because "it's a GUI control", I just assumed it was a functional limitation of the GUI.

Changing the default max width from 200 to 2560 will stop any other people as stupid as me getting confused, with zero code knock on issues that I can see...
