### ISSUE TITLE
ISBAT see image captions while using Lightbox

### ISSUE THREAD

**Issue by AnthonyLedesma** [godaddy-wordpress/coblocks#1099]
**Is this enhancement related to a problem? Please describe.**
Image captions are visible when looking at the published page but not when viewing through the image Lightbox. I should be able to see image captions within the Lightbox if toggled.

Captions on page
![image](https://user-images.githubusercontent.com/30462574/68408902-69f01600-0143-11ea-9a85-f7f2bfd43b75.png)

No captions in Lightbox
![image](https://user-images.githubusercontent.com/30462574/68409010-9c9a0e80-0143-11ea-9339-f0e23c33afed.png)

**Additional context**
Lightbox functionality is sourced from `/src/js/coblocks-lightbox.js`. Ideally we should explore the option to display captions here.

**Inspired with WordPress.org support request**
https://wordpress.org/support/topic/how-to-expand-the-lightbox/

**Comment by richtabor** [comment]
@AnthonyLedesma Do we know if this is possible with our current lightbox solution?

**Comment by AnthonyLedesma** [comment]
@richtabor It should be possible to hook into the DOM and attach what we need. The unknown here is referencing the captions from the Lightbox UI.

**Comment by jrtashjian** [comment]
The lightbox is built dynamically here: https://github.com/godaddy-wordpress/coblocks/blob/master/src/js/coblocks-lightbox.js#L12-L74 and rendered to the page on this line: https://github.com/godaddy-wordpress/coblocks/blob/master/src/js/coblocks-lightbox.js#L32

I would save the caption in the `imagePreloader` object here: https://github.com/godaddy-wordpress/coblocks/blob/master/src/js/coblocks-lightbox.js#L40-L47

The imagePreloader is an actual `img` element so you'll want to add a new `data-caption` attribute that can be referenced one changing the images. When [`changeImage`](https://github.com/godaddy-wordpress/coblocks/blob/master/src/js/coblocks-lightbox.js#L67-L73) is called you would replace the content of the caption element you create with the value we've saved in the `imagePreloader` object.
