### ISSUE TITLE
Enhance CoBlocks with an uninstall.php file to remove extraneous options

### ISSUE THREAD

**Issue by AnthonyLedesma** [godaddy-wordpress/coblocks#1153]
**Is your feature request related to a problem? Please describe.**
Now that PR https://github.com/godaddy/coblocks/pull/1110/ has been merged, CoBlocks has an entry in the WordPress database options table titled `coblocks_settings_api`. This settings API is no longer referenced or used with the removal of Block Manager. CoBlocks should remove these database entries when uninstalled.

**Describe the solution you'd like**
Expect a `uninstall.php` file to remove the database CoBlocks database entries when invoked. 

Related developer resources:
https://developer.wordpress.org/plugins/plugin-basics/uninstall-methods/#method-2-uninstall-php

https://developer.wordpress.org/reference/functions/get_option/

https://developer.wordpress.org/reference/functions/delete_option/

**Comment by jrtashjian** [comment]
Closed in #1172
