### ISSUE TITLE
ISBAT navigate Lightbox by keyboard

### ISSUE THREAD

**Issue by AnthonyLedesma** [godaddy-wordpress/coblocks#1155]
CoBlocks should consider enhancing the Lightbox with navigation controls.

**Feature**
Keyboard navigation of the Lightbox using arrow keys.

**Inspired with WordPress.org support request**
https://wordpress.org/support/topic/lightbox-add-keyboard-navigation/

**Comment by richtabor** [comment]
This issue should be split into two separate issues. 👍
