### ISSUE TITLE
ISBAT set Lightbox background

### ISSUE THREAD

**Issue by AnthonyLedesma** [godaddy-wordpress/coblocks#1157]
CoBlocks should consider enhancing the Lightbox by allowing background settings.

**Feature**
Block-level or Global background controls to the Lightbox. Possibly the ability to set a solid color or dedicated logo.

**Inspired with WordPress.org support request**
https://wordpress.org/support/topic/lightbox-add-keyboard-navigation/

**Comment by richtabor** [comment]
I'm not sure of the value here honestly, especially the "dedicated logo". We can't have options for everything. This really should be a CSS solution. 

@AnthonyLedesma Any objections to closing this one?
