### ISSUE TITLE
Random order option for gallery blocks

### ISSUE THREAD

**Issue by hvianna** [godaddy-wordpress/coblocks#1209]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
An option to randomize the display order of images in gallery blocks and carousel

Thanks!

**Comment by richtabor** [comment]
Thanks for the feedback @hvianna. Although this is an interesting idea, it would likely decrease performance as we'd need to load another script to randomize the images. You could likely write a script and include it via a separate plugin to achieve this though. :)

Thanks!
