### ISSUE TITLE
Auto scroll option for Post Carousel

### ISSUE THREAD

**Issue by hvianna** [godaddy-wordpress/coblocks#1210]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
An option to enable auto scroll of the posts carousel, with configurable transition speed, like the carousel gallery.

Thanks!

**Comment by richtabor** [comment]
Hey @hvianna, thanks for the suggestion. Per UX considerations, I don't believe auto-scrolling the posts would be a good idea. Having text auto-scroll out-of-view away is not an experience I want to foster - as then the reader has to click on one of the arrows to move it back into view, before continuing to read (though its likely the reader will give up on reading it). 

Again, thanks for contributing your idea - we welcome and appreciate them all. 👍
