### ISSUE TITLE
Paragraph block with custom font sizes break when CoBlocks is active

### ISSUE THREAD

**Issue by mmtr** [godaddy-wordpress/coblocks#1220]
**Describe the bug**
All paragraph blocks inserted in post that are using a custom font size are marked as invalid when the CoBlocks plugin is active.

It seems those blocks gets an unexpected `has-custom-size` class:
```
Content generated by `save` function:

<p style="font-size:16px" class="has-custom-size">Test paragraph</p>

Content retrieved from post body:

<p style="font-size:16px">Test paragraph</p>
```

**To Reproduce**
1. Insert a paragraph block.
1. Change the font size to 16px.
1. Activate CoBlocks.
1. See error.

**Screenshots**
Block before activating CoBlocks:
<img width="1028" alt="Screenshot 2019-12-20 at 18 51 32" src="https://user-images.githubusercontent.com/1233880/71280103-a164fb80-235a-11ea-952a-715e02506dc8.png">

Block after activating CoBlocks:
<img width="650" alt="Screenshot 2019-12-20 at 18 52 18" src="https://user-images.githubusercontent.com/1233880/71280084-9ad68400-235a-11ea-96ce-6921c0e76ebe.png">

**Expected behavior**
Block shouldn't break.

**Isolating the problem:**
Mark completed items with an [x].

-   [x] This bug happens with no other plugins activated
-   [x] This bug happens with a default WordPress theme active
-   [x] This bug happens **without** the Gutenberg plugin active
-   [x] I can reproduce this bug consistently using the steps above

**WordPress Version**
5.3.2

**Comment by jrtashjian** [comment]
@mmtr Thank you for submitting this! Looks like a custom class is being added to paragraph block from our Typography Controls feature. This class isn't needed and removing it resolves the issue.

This will be fixed in [1.19.1](https://github.com/godaddy-wordpress/coblocks/milestone/24), releasing later today.
