### ISSUE TITLE
Offset gallery: Captions removed after adding new images

### ISSUE THREAD

**Issue by mmtr** [godaddy-wordpress/coblocks#1229]
**Describe the bug**
Any caption entered in an offset gallery image is removed after adding a new image to the gallery.

**To Reproduce**
1. Insert an offset gallery block.
1. Add some images.
1. Activate the captions.
1. Add captions to the images.
1. Add a new image to gallery.
1. Captions previously entered are removed.

**Screenshots**
![Jan-02-2020 15-56-44](https://user-images.githubusercontent.com/1233880/71673389-f9e3c200-2d78-11ea-9258-cf41c6fb9ac2.gif)

**Expected behavior**
Captions previously entered should be preserved.

**Isolating the problem:**
-  [x] This bug happens with no other plugins activated
-  [x] This bug happens with a default WordPress theme active
-  [ ] This bug happens **without** the Gutenberg plugin active
-  [x] I can reproduce this bug consistently using the steps above

**WordPress Version**
5.3.2

**Gutenberg Version**
7.1.0

**Comment by AnthonyLedesma** [comment]
It also occurs on the Stacked and Masonry blocks.

**Comment by richtabor** [comment]
@AnthonyLedesma Want to take this and look into it deeper?
