### ISSUE TITLE
ISNBAT use the CoBlocks buttons block in Gutenberg 7.2.0

### ISSUE THREAD

**Issue by mmtr** [godaddy-wordpress/coblocks#1235]
**Describe the bug**
The Buttons block from CoBlocks does not work when using the [incoming Gutenberg 7.2.0](https://github.com/WordPress/gutenberg/releases/tag/v7.2.0-rc.1). It might be related to the addition of a similar Buttons block introduced in Gutenberg 7.2.0 (https://github.com/wordpress/gutenberg/pull/17352).

**To Reproduce**

1. [Download, install and activate Gutenberg 7.2.0 RC](https://github.com/WordPress/gutenberg/releases/tag/v7.2.0-rc.1)
1. Insert a Buttons block from CoBlocks.
1. Buttons are in different lines. Neither text nor URLs can be entered.

**Screenshots**

| Gutenberg 7.2.0 RC | Gutenberg 7.1.0 |
|---|---|
| <img width="668" alt="Screenshot 2020-01-06 at 17 01 19" src="https://user-images.githubusercontent.com/1233880/71830289-bf469600-30a6-11ea-8ac1-71e17dba6428.png"> | <img width="642" alt="Screenshot 2020-01-06 at 17 01 39" src="https://user-images.githubusercontent.com/1233880/71830301-c40b4a00-30a6-11ea-9e0c-2a9429a80fa8.png"> |

**Expected behavior**

Not sure, but there are several options:
- Deprecate the CoBlocks Buttons block in favor of the new one from Core.
- Rename the CoBlocks Buttons block so there are no 2 blocks with the same name.
- If CoBlocks Buttons block remain active, it should behave like before (buttons are in the same line, and text or URLs can be entered).

**Isolating the problem:**
-   [x] This bug happens with no other plugins activated
-   [x] This bug happens with a default WordPress theme active
-   [ ] This bug happens **without** the Gutenberg plugin active
-   [x] I can reproduce this bug consistently using the steps above

**WordPress Version**
5.3.2

**Gutenberg Version**
7.2.0 RC

**Comment by richtabor** [comment]
Yea we definitely would like to deprecate our Buttons block for the version in 7.2.0, but there's not a clear way to deprecate blocks into other blocks just yet - but we're looking into it. 

The ideal situation would be: if there's a `core/buttons` block registered, auto-transform the `coblocks/buttons` block into the core version.
