### ISSUE TITLE
ISBAT disable prices from Food and Drinks block

### ISSUE THREAD

**Issue by AnthonyLedesma** [godaddy-wordpress/coblocks#1276]
**Describe the bug**
If a price is set on the Food Item block then prices are disabled from the parent Food and Drinks block, we receive "This block contains unexpected or invalid content."

![image](https://user-images.githubusercontent.com/30462574/72745172-611cb700-3b6c-11ea-9e84-ce8ad4fe2294.png)
![image](https://user-images.githubusercontent.com/30462574/72745209-772a7780-3b6c-11ea-84d5-fc7459f586ad.png)

**To Reproduce**

1. Add Food and Drinks block.
2. Click on Food Item block and type in a price.
3. Click on parent Food and Drinks block.
4. Disable (toggle) prices attribute in the editor sidebar. 
5. Save.
6. Reload page to see the error.

**Expected behavior**
Should be able to disable attribute at block level without errors.

**Isolating the problem:**
Mark completed items with an [x].

-   [x] This bug happens with no other plugins activated
-   [x] This bug happens with a default WordPress theme active
-   [x] This bug happens **without** the Gutenberg plugin active
-   [x] I can reproduce this bug consistently using the steps above

**WordPress Version**
What version of WordPress are you using?
5.3.2

**Gutenberg Version**
What version of the Gutenberg plugin are you using? (If any)
Happens with and without GB 7.2 running.

**Comment by EvanHerman** [comment]
I can't seem to be able to replicate this one 🤔
