### ISSUE TITLE
ISBAT disable images from Food and Drinks block

### ISSUE THREAD

**Issue by AnthonyLedesma** [godaddy-wordpress/coblocks#1277]
**Describe the bug**
If an image is set on the Food Item block then images are disabled from the parent Food and Drinks block, we receive "This block contains unexpected or invalid content."

![image](https://user-images.githubusercontent.com/30462574/72748150-b01a1a80-3b73-11ea-8e36-07cfcf2b2e7f.png)
![image](https://user-images.githubusercontent.com/30462574/72748163-b7412880-3b73-11ea-82f0-63b7dfe960b0.png)

**To Reproduce**

1. Add Food and Drinks block and click on the block.
2. Enable images in editor sidebar.
3. Click on Food Item block and add an image.
4. Click on parent Food and Drinks block.
5. Disable images in editor sidebar.
6. Save.
7. Reload page to see the error.

**Expected behavior**
Expect to toggle image attribute at a block level.

**Isolating the problem:**
Mark completed items with an [x].

-   [x] This bug happens with no other plugins activated
-   [x] This bug happens with a default WordPress theme active
-   [x] This bug happens **without** the Gutenberg plugin active
-   [x] I can reproduce this bug consistently using the steps above

**WordPress Version**
What version of WordPress are you using?
5.3.2

**Gutenberg Version**
What version of the Gutenberg plugin are you using? (If any)
Happens with and without GB 7.2 running.

**Comment by richtabor** [comment]
@EvanHerman Can you also not replicate this one?

**Comment by richtabor** [comment]
I was able to replicate this on my end.
