### ISSUE TITLE
Masonry block custom links disappear when adding new images

### ISSUE THREAD

**Issue by kdevnel** [godaddy-wordpress/coblocks#1290]
**Describe the bug**
The bug involves adding new gallery items to a Masonry Gallery block when the block link settings are set to a custom URL. Existing items with links have the links removed as soon as you update the gallery with the new item.

**To Reproduce**

1. Add a Masonry block to a post or page
2. Add any number of gallery items to the block
3. In the Block settings in the sidebar > Links Settings > Link To dropdown, select "Custom URL"
4. Go back to your images and click each one, then enter a URL
5. Click to add a new image to the gallery
6. Choose your image, click the "add to gallery" button and then the "update gallery" button
7. Check previously entered custom URLs - they will be missing

**Screenshots**
GIF to show issue:
![https://d.pr/i/KflVAs](https://d.pr/i/KflVAs+)  

Image link if embed above doesn't work: `https://d.pr/i/KflVAs`

**Expected behavior**
I would expect all previously entered custom URLs to still be in place when adding new gallery items.

**Isolating the problem:**
Mark completed items with an [x].

-   [x] This bug happens with no other plugins activated
-   [x] This bug happens with a default WordPress theme active
-   [x] This bug happens **without** the Gutenberg plugin active
-   [x] I can reproduce this bug consistently using the steps above

**WordPress Version**
* Tested on vanilla install of WordPress 5.3.2 on local system
* Tested on WordPress.com site

**Gutenberg Version**
What version of the Gutenberg plugin are you using? (If any)
None, tested with plugin on and without one installed.

**Comment by AnthonyLedesma** [comment]
Occurs with Offset, Masonry and Stacked blocks. The cause is similar to the loss of captions when adding new images. Look at how https://github.com/godaddy-wordpress/coblocks/pull/1243/files accomplish this.
