### ISSUE TITLE
Add more icons to the icon block

### ISSUE THREAD

**Issue by nickhamze** [godaddy-wordpress/coblocks#1316]
Ok, I'm a liar. I'm posting again. I really will try to stop but I'm so bored :).

I was working on my Zune fansite this afternoon and I discovered your icon block (haven't really used WordPress for a while). I like it and it works great. The only thing is the icon selection is a bit limited. 

Have you ever consider hooking into something like the noun project API to offer really large selection of icons:
https://thenounproject.com/developers/

Seems like it could be pretty simple to get the icons from the API and they are already in SVG format so it would work great with your block. 

While I'm spouting crazy talk did you ever consider removing the block together and adding SVG icon capability to the rich text editor (with all the cool features you already have) kinda like we did with emoji conbini here.
https://github.com/sortabrilliant/emojiconbini

**Comment by richtabor** [comment]
Core is also [working on an Icon block](https://github.com/WordPress/gutenberg/issues/16484), experimenting with just that. Emoji Conbini is super cool by the way! Have you considered added type support, like Slack? Where `:grimacing` could pull up the 😬 emoji?

**Comment by seb86** [comment]
@richtabor There is [Emoji Autocomplete Gutenberg](https://wordpress.org/plugins/emoji-autocomplete-gutenberg/) that provides a Slack method.

**Comment by nickhamze** [comment]
It's neat they are doing that but I'm worried that the icon sets they are proposing are pretty small (comparatively). The noun project has over 2 million icons and they aren't all geared towards business. You aren't going to find a trapper keeper icon in FontAwesome:
https://thenounproject.com/search/?q=trapper%20keeper&i=831922

Re: emoji what Seb said. To me the type support is something Emoji pros know, I wanted to make something for people who don't know emojis all that well and need to browse for them visually. EAG was the inspiration for our plugin and it does a great job if that is what you are looking for.

**Comment by richtabor** [comment]
> @richtabor There is [Emoji Autocomplete Gutenberg](https://wordpress.org/plugins/emoji-autocomplete-gutenberg/) that provides a Slack method.

Nice, super cool!
