### ISSUE TITLE
Non-blocking Error shown in console when uploading images to galleries

### ISSUE THREAD

**Issue by chriskmnds** [godaddy-wordpress/coblocks#1318]
**Describe the bug**

An Unhandled Promise Rejection Error is shown in the console when uploading images to the Offset, Masonry, and Stacked galleries. This happens on CoBlocks version `1.20.1`.

This is a non-blocking error, since the images are uploaded as expected. The Error is shown only on the first upload - it seems to be cleared on consecutive ones. 

Tested in Chrome & Safari.

**To Reproduce**

1. Insert a new Gallery (Offset, Masonry, or Stacked).
2. Click on "Upload" at the bottom - should upload image as expected.
4. See error in console.

**Screenshots**

![Kapture 2020-01-30 at 13 05 02](https://user-images.githubusercontent.com/1705499/73445249-ed945a00-4362-11ea-9e30-5bba19f88a94.gif)

**Isolating the problem:**
Mark completed items with an [x].

-   [ ] This bug happens with no other plugins activated
-   [ ] This bug happens with a default WordPress theme active
-   [ ] This bug happens **without** the Gutenberg plugin active
-   [ ] I can reproduce this bug consistently using the steps above

**WordPress Version**
What version of WordPress are you using?
5.4
**Gutenberg Version**
What version of the Gutenberg plugin are you using? (If any)
7.3.0

**Comment by EvanHerman** [comment]
I am not seeing this issue running CoBlocks 1.2.0 in Chrome. Can someone else test and confirm this is a bug in CoBlocks?

**Comment by richtabor** [comment]
I'm also unable to replicate this - @chriskmnds are you still seeing the issue?

**Comment by AnthonyLedesma** [comment]
This issue is no longer present in CoBlocks 2.9.1.
