### ISSUE TITLE
Hero Block: buttons toolbar invisible when Hero has a background

### ISSUE THREAD

**Issue by senff** [godaddy-wordpress/coblocks#1324]
**Describe the bug**
The toolbar for Buttons in a Hero block doesn't appear anymore once the Hero Block has a background.

**To Reproduce**

1. Insert a Hero Block
2. Select a Button - you will see a toolbar for the button
3. Add a background (color or image) to the Hero Block
4. Select a Button - the toolbar will not be visible anymore

**Screenshots**
Without background:
![Good](https://user-images.githubusercontent.com/1710669/73799594-5d9c4900-4784-11ea-847a-d669f5005eee.png)

With background color:
![Bad](https://user-images.githubusercontent.com/1710669/73799596-5e34df80-4784-11ea-8da7-5aa286ed8118.png)

**Expected behavior**
Buttons toolbar should be visible regardless of the background setting.

**Isolating the problem:**
Mark completed items with an [x].

-   [x] This bug happens with no other plugins activated
-   [x] This bug happens with a default WordPress theme active
-   [x] This bug happens **without** the Gutenberg plugin active
-   [x] I can reproduce this bug consistently using the steps above

**WordPress Version**
5.3.2

**Gutenberg Version**
n/a

**Comment by richtabor** [comment]
Related: #1252
