### ISSUE TITLE
ISBAT add lightbox to a single image block

### ISSUE THREAD

**Issue by FriendlyWP** [godaddy-wordpress/coblocks#1356]
I would like to be able to insert a single image block containing a small version of an image (thumbnail, medium) and open the large/full version in a lightbox, as is possible in the various Coblocks gallery blocks.

### Describe the solution you'd like
Ideally this would work using the "lightbox" button group in the block sidebar instead of having to link the image to the Media file + turn on lightbox. I think think that doing it this way would allow users to link images to URLs  OR have them appear in a lightbox based on that choice (if lightbox = on, ignore URLs, else link to URL or nothing).

### Describe alternatives you've considered
The only workaround I've found is to use one of the Coblocks gallery blocks with a single image, but then I lose the ability to align the image left / right / center, as only 'wide/full' alignment options apply to the galleries. It's also not intuitive for users.

I've also tried adding plugins like WP Featherlight or dFactory's Responsive Lightbox, but if using any automated lightbox (vs adding lightboxes via rel="lightbox") the lightboxes double up wherever Coblocks lightboxes appear.

**Comment by AnthonyLedesma** [comment]
Hi @FriendlyWP, 

Thank you for taking some time to write this request up early last year. Over time with the CoBlocks Lightbox we have managed to integrate the Core image block thereby extending the Lightbox to work with the standard Image block as well as the CoBlocks Gallery blocks.

In a [new PR I have introduced](https://github.com/godaddy-wordpress/coblocks/pull/1787) the ability to use Lightbox with aligned images. My understanding is that this new feature, when merged will successfully address your original request. I will assign this issue to myself and attach it to the new PR here: https://github.com/godaddy-wordpress/coblocks/pull/1787
