### ISSUE TITLE
Row One Column in 1.21, please don't do this

### ISSUE THREAD

**Issue by barbeapapier** [godaddy-wordpress/coblocks#1359]
Since version 1.21 it is impossible to create Rows of 1 column, it is extremely penalizing since I use this system to create pages with a width limitation and with backgrounds of image type. So I no longer have the possibility of creating these elements and I am forced to stay on version 1.20.1 …

Please don’t do this.

**Comment by AnthonyLedesma** [comment]
We had a few similar requests come in regarding this. 

https://wordpress.org/support/topic/bring-back-1-column-row/
https://wordpress.org/support/topic/1-columns-row-block-disapear/
https://github.com/godaddy-wordpress/coblocks/pull/1308#issuecomment-586352178

**Comment by richtabor** [comment]
@AnthonyLedesma Let's add it back :)
