### ISSUE TITLE
ISBAT have links from the Social Profiles Block open in a new window

### ISSUE THREAD

**Issue by benchilcote** [godaddy-wordpress/coblocks#1360]
ISBAT have the option for social profile links to open in a new window or tab.  This is currently not an option in the block settings.

**Comment by AnthonyLedesma** [comment]
This request also came in on WordPress.org
https://wordpress.org/support/topic/request-social-block-open-in-new-window/

**Comment by webbpickersgill** [comment]
Thanks Anthony for re-posting my request here.  

Question for the dev team on this: Am I allowed to code this enhancement and then push it up?  I do coding, but I've never contributed to a project before through Git.  Are there any guidelines or tips for doing this correctly?  Thank you!

**Comment by AnthonyLedesma** [comment]
Hi @webbpickersgill,

> Am I allowed to code this enhancement and then push it up?

Yes! We welcome all contributions to CoBlocks. Get a look at the [how you can contribute](https://github.com/godaddy-wordpress/coblocks#how-you-can-contribute) section on our README. There we link to our Contributing Guidelines and have other general information. 

If you are just getting started I would advise getting a look at the [development section](https://github.com/godaddy-wordpress/coblocks#development) of the README which covers setup.

**Comment by webbpickersgill** [comment]
Excellent.  Thank you!  Those links will be very helpful.

**Comment by richtabor** [comment]
Let us know if you need a hand @webbpickersgill.

I've put together a mockup of what we should do here. It'd be best to imitate how core does this. The following is based on the UI/X of adding a link to text within the core Paragraph block. 

<img width="866" alt="Screen Shot 2020-03-05 at 12 23 13 PM" src="https://user-images.githubusercontent.com/1813435/76007612-52038580-5edc-11ea-8cf7-05a7eb405b36.png">

And [here's the draft](https://www.figma.com/file/ub8cmDQQt3m6Iidi7lyHYd/CoBlocks-Social-Open-in-new-tab?node-id=0%3A1) in Figma.

**Comment by richtabor** [comment]
Alternate approach (using a control within the sidebar): 
<img width="486" alt="Screen Shot 2020-04-16 at 2 04 41 PM" src="https://user-images.githubusercontent.com/1813435/79776748-2c9fcf00-8304-11ea-8b92-206019ae7b00.png">

I'm wondering if using the first option (commented above) would work better - but have the control labels "Open links in new tabs", which is a singular control for all the links.
