### ISSUE TITLE
ISBAT use coblocks without jQuery being required by default. (Events block issue)

### ISSUE THREAD

**Issue by stephenheron** [godaddy-wordpress/coblocks#1361]
### Describe the bug:
Hi, 

I updated coblocks to the latest version (1.21.0) and I noticed that now jQuery appears in the source even when no blocks are being used. Using the previous version that we were using (1.15.0) this was not the case.

I narrowed down the issue to Events block enqueuing 'coblock-slick' (https://github.com/godaddy-wordpress/coblocks/blob/master/src/blocks/events/index.php#L139).

If we compare this to the Posts Carousel block (https://github.com/godaddy-wordpress/coblocks/blob/master/src/blocks/post-carousel/index.php#L322) which also uses Slick, it instead uses 'wp_register_script' and 'editor_script' so it is only included for the editor. 

Interestingly in the [class-coblocks.block.assets.php](https://github.com/godaddy-wordpress/coblocks/blob/master/includes/class-coblocks-block-assets.php#L299) it seems it looks for the events block and enqueues the scripts. 

### To reproduce:
Install coblocks 1.21.0.
View source on page not using any blocks.
jQuery is being included.

### Expected behavior:
Install coblocks 1.21.0.
View source on page not using any blocks.
jQuery is not being included.

**Comment by josephscott** [comment]
@jrtashjian this appears to be coming from this change: https://github.com/godaddy-wordpress/coblocks/commit/950cdb9b36714982c43bc1692536d33877490d9d#diff-2c58a1e4d8686ecb878210a36c71d29dR139

As noted above, CoBlocks now adds extra JS and CSS on every page view, just by activating the plugin.  These include:

- jQuery ( 33 KB )
- jQuery Migrate ( 4.3 KB )
- slick.js ( 10.9 KB )
- coblocks-style.css ( 19.6 KB )

That is an extra 67.8 KB over the wire for every page view, just by activating the CoBlocks plugin.

While #1365 is a good long term solution, not loading these extra resources on every page view would be a big help right now.
