### ISSUE TITLE
ISBAT have consistent variation picker icon spacing with Row block

### ISSUE THREAD

**Issue by AnthonyLedesma** [godaddy-wordpress/coblocks#1362]
### Describe the bug:
The Row block uses a variation picker type of component using choices represented with icons. This is a similar UX to the `core/columns` block. The icons, when split over two lines, do not have proper spacing and should be corrected.

### To reproduce:

1. Add post and edit post.
2. Add the Row block and chose the three columns option.
3. Adjust your screen width until the icons are split between two rows.
4. See error.

### Screenshots:
![image](https://user-images.githubusercontent.com/30462574/74676385-27db6500-5173-11ea-993f-7caf90975893.png)

### Isolating the problem:

- [x] This bug happens with no other plugins activated
- [x] This bug happens with a default WordPress theme active
- [x] This bug happens **without** the Gutenberg plugin active
- [x] I can reproduce this bug consistently using the steps above

### WordPress version:

5.3.2

### Gutenberg version:

N/A (Also occurs with 7.5 active)

**Comment by richtabor** [comment]
Just to confirm @AnthonyLedesma, we'll still need this fixed, even with the #1372 variations API migration you put together - correct?

**Comment by AnthonyLedesma** [comment]
@richtabor Only an issue with 5.3.2 using the classic selector system. This fix is not necessary when the variations API picker is in use. That applies to 5.4 with and without Gutenberg running.
