### ISSUE TITLE
ISBAT see an error message with Events block if not a valid calendar URL

### ISSUE THREAD

**Issue by AnthonyLedesma** [godaddy-wordpress/coblocks#1363]
### Describe the bug:
Events block can be given a URL that does not have a compatible calendar resulting in a block without content. An example of such a URL would be: https://www.nasa.gov/calendar. 

### To reproduce:
1. Add post and edit post.
2. Add Events block and enable `Link a Calendar` in Sidebar.
3. Paste incompatible URL such as https://www.nasa.gov/calendar.
4. See bug.

### Expected behavior:

Events block should use consistent error reporting in case of no content. 

### Screenshots:

![eventsNonError](https://user-images.githubusercontent.com/30462574/74677700-4e4ecf80-5176-11ea-9c22-3510f6d5c2ab.gif)

### Isolating the problem:

- This bug happens with no other plugins activated
- This bug happens with a default WordPress theme active
- This bug happens **without** the Gutenberg plugin active
- I can reproduce this bug consistently using the steps above

### WordPress version:

5.3.2

### Gutenberg version:

N/A (Also occurs with GB 7.5)

**Comment by jlemay-godaddy** [comment]
It looks like it was fixed. Using the `nasa.gov/calendar` link an error message was shown : 
![image](https://user-images.githubusercontent.com/85305825/137010273-85bf1a2f-d369-4352-b57c-469cdf1c2bb6.png)
