### ISSUE TITLE
Change Typography: Font Dropdown Always Shows "Default"

### ISSUE THREAD

**Issue by jacoswan** [godaddy-wordpress/coblocks#1374]
### Describe the bug:

I should be able to see at a glance the name of the Font instead of "Default" if I previously selected a non-default font. Instead it currently always shows "Default" regardless of it actually being the default font or not. 

### To reproduce:

1. Go to a new post and add some text
2. Via the "Change typography" select a non-default option from the Font dropdown
3. Notice how the Font changes, but the dropdown goes back to Default

### Expected behavior:

When I select non-default values from the Font dropdown, I would expect the font name to replace "Default" and be visible the next time I return to edit that text, similar to how the Weight and Transform dropdowns do. 

### Screenshots:

![Screen Capture on 2020-02-24 at 08-49-23](https://user-images.githubusercontent.com/15178758/75133233-a6d81c80-56e2-11ea-9c31-e8358d88e4a4.gif)

### Isolating the problem:

- [x] This bug happens with no other plugins activated
- [x] This bug happens with a default WordPress theme active
- [x] This bug happens **without** the Gutenberg plugin active
- [x] I can reproduce this bug consistently using the steps above

### WordPress version:

5.4.2

### Gutenberg version:

N/a

**Comment by richtabor** [comment]
Confirmed.
