### ISSUE TITLE
Bug: Post Carousel doesn't allow for category filter 

### ISSUE THREAD

**Issue by selectedselections** [godaddy-wordpress/coblocks#1387]
### Describe the bug:
Using a Post Carousel coblock, I should be able to choose the category of post I wish to display within the block. 

The drop down list of categories is currently unavailable 

### To reproduce:

1. Assign a category to a blog post 
2. Add the post carousel block to a page 
3. Choose the category of post you wish to display in within the carousel from the block settings

### Expected behavior:

Post Carousel allows user to select category and displays only the posts within that category 

### Screenshots:
This [screencast was created within a site that includes many categories](https://d.pr/v/7cwSIZ).

### More information: 

@mikestraw noted that there is an error in the PHP logs: 

`[28-Feb-2020 15:07:46 UTC] PHP Notice:  Trying to get property ‘ID’ of non-object in /wordpress/plugins/coblocks/1.21.1/src/blocks/post-carousel/index.php on line 25`

Cannot reproduce the issue using coblocks **1.16.1** but the issue can be reproduced using **1.21.1** which suggests the issue came up during an update between those versions. 

user reported issue

**Comment by richtabor** [comment]
Seems to affect our Posts block as well.
