### ISSUE TITLE
ISBAT Filter out and remove CoBlocks icons SVGs

### ISSUE THREAD

**Issue by colorful-tones** [godaddy-wordpress/coblocks#1394]
Awesome work on #1006  and this works great! It would be great to have a filter or boolean to perhaps allow users to disable all of CoBlock's icons and then load in their own in theme. Whereas, right now CoBlocks' icons are always loaded along with the user's added SVGs.

Could even be a boolean flag in the theme's `config.json`? Or, perhaps an `apply_filters( 'use_coblocks_svgs', return true );` at the top of [`get_custom_icons()`](https://github.com/godaddy-wordpress/coblocks/blob/master/includes/class-coblocks-block-assets.php#L160). 

Then user could set in their theme:
``` php
add_filter( 'use_coblocks_svgs', return false );
```

This would hide all of CoBlocks' SVG, and just show what is available in the theme's `coblocks/icons/*.svg` dir.

**Comment by richtabor** [comment]
Great idea!

**Comment by EvanHerman** [comment]
@colorful-tones I've got a PR that implements just this. https://github.com/godaddy-wordpress/coblocks/pull/1403 Feel free to take things for a spin while we test things out on our end. 👌

Thanks for the great suggestion!
