### ISSUE TITLE
The lightbox does not work with lazy loading

### ISSUE THREAD

**Issue by florianbrinkmann** [godaddy-wordpress/coblocks#1421]
### Describe the bug:
A user of my lazy loading plugin reported (https://wordpress.org/support/topic/plugin-compatibility-coblocks-gallery-lightbox/) that there are problems using it with CoBlocks’ lightbox for, for example, the offset gallery block.

I took a look into the code and the issue seems to be that on load the `img` elements are scraped for the `src` attribute values, to store them in a variable. But at that point, the `src` holds the placeholder data uri from my plugin, so the lightbox tries to display that instead of the image that gets loaded later.

### To reproduce:

1. Install and activate Lazy Loader (https://wordpress.org/plugins/lazy-loading-responsive-images/) and CoBlocks.
2. Create an offset gallery with the lightbox feature enabled.
3. View the frontend and try the lightbox.
4. See error.

### Expected behavior:

Correct displaying of the image :)

### Isolating the problem:

- [x] This bug happens with no other plugin (except Lazy Loader) activated
- [x] This bug happens with a default WordPress theme active
- [x] This bug happens **without** the Gutenberg plugin active
- [x] I can reproduce this bug consistently using the steps above

### WordPress version:
5.4 RC2-47460

**Comment by AnthonyLedesma** [comment]
@florianbrinkmann Thank you for this report. I have a PR up that should fix this bug here: #1486. If you have time to test out the branch `fix/lazy-load-lightbox` We would appreciate it.
