### ISSUE TITLE
ISBAT add and choose custom (local) fonts

### ISSUE THREAD

**Issue by zitrusblau** [godaddy-wordpress/coblocks#1426]
### Is your feature request related to a problem? Please describe.
It would be nice to modify the font selection, i.e. when editing a paragraph or heading block in order to A) set other google fonts B) use custom local fonts from theme.
Ideally, disabling google fonts altogther as a privacy related issue would make sense, too.

### Describe the solution you'd like
Have some hooks in place to modify the list of available custom fonts.

### Describe alternatives you've considered
- writing a custom font selector from scratch.
- add custom block styles and set font via custom css class

### Additional context/screenshots
none, actually. just found that this setting can be disabled completely via
`add_filter( 'coblocks_typography_controls_enabled', '__return_false' );`

Thanks!

**Comment by AnthonyLedesma** [comment]
Hi @zitrusblau,

For clarity on this issue, I'd advise getting a look at the hook documentation for adding more Google fonts to the list of available fonts. https://github.com/godaddy-wordpress/coblocks/blob/master/docs/hooks/typography-controls.md.

Regarding Theme fonts, you should be able to use the fonts which your Theme uses by default. If you do not set any Fonts with the CoBlocks Typography controls and instead use a font from the theme customizer, that theme should continue to take precedence. Is there something about this request that I am missing?

**Comment by zitrusblau** [comment]
@AnthonyLedesma 

thanks for your reply.
As for the google fonts filter hook: Good to know!
I'm aware that the regular theme font(s) will be used if no additional typography setting is enabled for the block that needs custom styling.

But there might be use cases where an editor would like to set a theme font for a paragraph or some other content in order to format the content with this theme font.

I also think that this might be not a very common issue and that one should go with the global font styling provided by the theme but I found this an issue on a project we're currently working on that adds a decorative font that can be used "on demand" so to speak.

I solved it by adding a custom block style instead. it's just not the best UX, I think. but thanks for your time!

**Comment by AnthonyLedesma** [comment]
@zitrusblau 

Thanks again for creating this report and glad to help. After consideration, we do not expect a feature like this to be developed for CoBlocks in the near future. 

Please do not hesitate to create new issues if you encounter any.
