### ISSUE TITLE
ISBAT view controls properly while using a RTL language

### ISSUE THREAD

**Issue by richtabor** [godaddy-wordpress/coblocks#1438]
### Describe the bug:
Some of our controls need refining for proper RTL support. 

### To reproduce:

Select a RTL language in WordPress, view Settings Sidebar block controls. 

### Expected behavior:
Controls are properly modified stylistically to provide a consistent RTL experience.

### Screenshots:
Here's a screenshot of our Hero block's controls, but we need to evaluate any block we have that is using a component we built. 
<img width="473" alt="Screen Shot 2020-03-18 at 4 02 14 PM" src="https://user-images.githubusercontent.com/1813435/77773865-95a36800-7020-11ea-9653-a93f54c22de6.png">
<img width="268" alt="Screen Shot 2020-03-18 at 4 08 12 PM" src="https://user-images.githubusercontent.com/1813435/77773869-95a36800-7020-11ea-801c-bf0bf266286a.png">

### Isolating the problem:

- [x] This bug happens with no other plugins activated
- [x] This bug happens with a default WordPress theme active
- [x] This bug happens **without** the Gutenberg plugin active
- [x] I can reproduce this bug consistently using the steps above

**Comment by AnthonyLedesma** [comment]
Not able to reproduce. 

![image](https://user-images.githubusercontent.com/30462574/78580375-2c251580-77e7-11ea-9183-c84b2b9dcb67.png)
