### ISSUE TITLE
Accordion block not displaying correctly on Edge browser

### ISSUE THREAD

**Issue by jamiepalatnik** [godaddy-wordpress/coblocks#1441]
### Describe the bug:

Accordion blocks display always open and can't be closed on Internet Explorer and Edge browsers.

### To reproduce:

1. Add an accordion block to a post or page.
2. Display as open should be toggled off.
3. View the accordion block on Edge or Internet Explorer.
4. See error: accordion displays as open and can't be closed.

### Expected behavior:

I expected the accordion to display as closed and only open when I click, as it does on other browsers.

### Isolating the problem:

- [x] This bug happens with no other plugins activated
- [x] This bug happens with a default WordPress theme active
- [x] This bug happens **without** the Gutenberg plugin active
- [x] I can reproduce this bug consistently using the steps above

### WordPress version:

WordPress version 5.4

**Comment by AnthonyLedesma** [comment]
Hi @jamiepalatnik,

Thank you for taking the time to write up this bug report. This is something that I have been able to reproduce conditionally. The Accordion block has control to allow polyfill for proper compatibility with Edge and Internet Explorer.

Please ensure that you have this control enabled and let me know if your issue persists.
![image](https://user-images.githubusercontent.com/30462574/78834311-4146a380-79a3-11ea-8ad6-a78ad0a710c5.png)

To find this control first select the parent Accordion block. The easiest way to accomplish this is to use the block navigation component. 
![image](https://user-images.githubusercontent.com/30462574/78834418-63d8bc80-79a3-11ea-8ea1-63ce20d5222f.png)

**Comment by jamiepalatnik** [comment]
Thanks, that resolved the issue for me on Edge in my test but there is still a bullet point showing, which I would not expect.

**Comment by richtabor** [comment]
> Thanks, that resolved the issue for me on Edge in my test but there is still a bullet point showing, which I would not expect.

Hi @jamiepalatnik, do you mind posting a screenshot of the bullet point you're seeing? Thanks!

**Comment by jamiepalatnik** [comment]
Yes, here's a screenshot:
![Edge accordions](https://user-images.githubusercontent.com/30788962/79257427-9842f180-7e57-11ea-9897-acbc2ec24e0e.png)

I'm using Edge 18 on Windows 10.

**Comment by richtabor** [comment]
@AnthonyLedesma Can you confirm this bullet point appears in Edge?

**Comment by richtabor** [comment]
@jamiepalatnik do you have a URL we can look at?

**Comment by jamiepalatnik** [comment]
Sure, here is my test site: https://wpjcp.mystagingwebsite.com/2020/04/accordions/

**Comment by AnthonyLedesma** [comment]
@richtabor I cannot replicate this with the latest versions of Edge but the issue does occur running IE11.

![image](https://user-images.githubusercontent.com/30462574/79348166-801bb280-7ee9-11ea-9fd6-aa92c1f2b37e.png)
