### ISSUE TITLE
ISBAT insert the Pricing Table block using the Block Inserter

### ISSUE THREAD

**Issue by marekhrabe** [godaddy-wordpress/coblocks#1449]
### Describe the bug:
The block inserter is unexpectedly closed when user hovers the Pricing Table block. 

This **does not happen** with core block editor but only with the Gutenberg plugin active. I have been reproducing this error consistently using latest CoBlocks and Gutenberg plugins straight from the plugin repo (CoBlocks 1.23.0, Gutenberg 7.8.1) on a fresh WP install.

No other CoBlocks block shows this behavior to my knowledge.

### To reproduce:
- open the block inserter (the very left top of the screen, "plus" icon)
- find Pricing Table in the list
- hover it

### Expected behavior:
See the example preview and be able to click the button to insert the block.

### Screenshots:
![2020-04-13 17 53 36](https://user-images.githubusercontent.com/156676/79135561-d2f14f00-7daf-11ea-95e3-6523a49fc0a6.gif)

### Isolating the problem:

- [x] This bug happens with no other plugins activated
- [x] This bug happens with a default WordPress theme active
- [ ] This bug happens **without** the Gutenberg plugin active
- [x] I can reproduce this bug consistently using the steps above

### WordPress version:
5.4

### Gutenberg version:
7.8.1

### More investigation
There is no console error which is super strange and hard to debug without knowing this codebase.

There is sometimes a console warning which has been already documented in #799:

```
wp.blockEditor.RichText formattingControls prop is deprecated. Please use allowedFormats instead.
```

I have tried to check whether this is to root cause by removing all `formattingControls` usages. No effect so I assume it does not cause the error with the inserter.

After some more debugging I have found that this error is likely connected to the way Pricing Table generates its inner blocks during the block initialization. I haven't dug much deeper but I have an understanding that when this block sees no inner blocks, it generates and inserts `pricing-table-item` blocks into itself, based on the count attribute.

I don't know what is the root cause responsible but I've been able to make the inserter work again by providing an `example` of the pricing table block with inner blocks included. This probably skips the block-generating logic in the Pricing Block and just shows it.

```
	example: {
		attributes: {
			count: 1,
		},
		innerBlocks: [
			{
				name: 'coblocks/pricing-table-item',
				attributes: {
					placeholder: sprintf( __( 'Plan %d', 'coblocks' ), 1 ),
				},
			},
		],
	},
```

Since this is not a proper fix of the root cause, I haven't done a PR but unless you can pinpoint the error, I think it might be good idea to get this in. The preview it generates matches the one that will get generated anyway and follows how core blocks define their examples (including inner blocks, for [`example in core/columns`](https://github.com/WordPress/gutenberg/blob/c3798f141028240312dc7e7d530ad82b38900151/packages/block-library/src/columns/index.js#L33-L89)).

**Comment by jrtashjian** [comment]
@marekhrabe I'm seeing "1 hidden" pop-up in the top-right part of the console window when you insert the block. Is this the `wp.blockEditor.RichText` warning you mentioned or is this something else?

**Comment by marekhrabe** [comment]
Takes a ton of tries to replicate (isn't consistent) but it's this:

```
[Violation] 'setTimeout' handler took 54ms
```

from somewhere deep in lodash file. My gut says it's likely not related.

**Comment by getdave** [comment]
Is there a way we could improve Core to avoid/manage errors in the case that the preview itself is in an error state?
