### ISSUE TITLE
ISBAT to add a Google Maps API Key and still see the Map Block

### ISSUE THREAD

**Issue by Reinpal** [godaddy-wordpress/coblocks#1453]
### Describe the bug:
When adding an API Key to the Google Maps Block, the Map dissappears from the Backend and is not rendered on the Frontend.

### To reproduce:
1. Add Google Map Block
2. Enter the Place you want to show
3. Add the API Key
4. The Map dissappears in the Editor, on the Frontend it renders a grey block.
5. Console shows no error in Backend, on Frontend it shows the following:
`InvalidValueError: setCenter: not a LatLng or LatLngLiteral with finite coordinates: in property lat: NaN is not an accepted value`

### Expected behavior:
The Map should show up in the Editor and the Frontend with all the settings I have applied.

### Screenshots:
https://drive.google.com/drive/folders/1kBjOAdpGA1O6xd1bORHHqReS-OIfRePf?usp=sharing

### Isolating the problem:
- [x] This bug happens with no other plugins activated
- [x] This bug happens with a default WordPress theme active
- [x] This bug happens **without** the Gutenberg plugin active
- [x] I can reproduce this bug consistently using the steps above

### WordPress version:
5.4.0

### Gutenberg version:
7.8.1

### CoBlocks Plugin version:
1.23.0

**Comment by richtabor** [comment]
I wonder if the API key is correct? If not, perhaps we need an error state if the API key does not work.

**Comment by Reinpal** [comment]
Are there any specific APIs that need to be enabled besides the Maps Javascript API?
Because I just generated a new key and was facing the same error as above. I also tried it with an unrestricted key just to exclude any errors on that side, didn't help either. 
What am I missing here?

**Comment by BibraDesign** [comment]
I'm having the very same issues, now the second time with CoBlocks on two different sites. Is this going to be fixed soon?
