### ISSUE TITLE
Hero block's button doesn't center on selection

### ISSUE THREAD

**Issue by trssssrt** [godaddy-wordpress/coblocks#1460]
### Describe the bug:
When adding the Hero block the buttons do not align with users choices.

### To reproduce:

1. Install plugin
2. Go to a page
3. Add Hero block, remove the second button,
<img width="1677" alt="Screen Shot" src="https://user-images.githubusercontent.com/34108479/79480571-45467700-7fdc-11ea-82cb-45edce014547.png">
 and select center layout
4. Publish page
5. Scroll until Hero block is in view
6. See error

### Expected behavior:
When the center layout option is selected, the Hero button should also readjust

### Isolating the problem:

- [ x] This bug happens with no other plugins activated
- [x ] This bug happens with a default WordPress theme active
- [x ] This bug happens **without** the Gutenberg plugin active
- [ x] I can reproduce this bug consistently using the steps above

### WordPress version:
5.4

### Extra Possibly Useful Information
- Theme: Storefront

**Comment by AnthonyLedesma** [comment]
Hi @trssssrt. I see what you are referring to. The buttons block is set to align left by default which my be causing the behavior you are experiencing. Have you attempted to change the alignment to resolve the issue? Get a look at these screenshots.

This one has the alignment issue. 
![image](https://user-images.githubusercontent.com/30462574/79584421-3666cf80-8083-11ea-9d0f-83df0159db1d.png)

This one I have changed the alignment to center.
![image](https://user-images.githubusercontent.com/30462574/79584482-526a7100-8083-11ea-8014-d9197089e937.png)

**Comment by trssssrt** [comment]
Hi,Thanks for getting back. The screenshots you included work if you have two buttons. If you remove one you should see the problem I'm experiencing

    On Friday, April 17, 2020, 11:15:15 AM EDT, Anthony Ledesma <notifications@github.com> wrote:  
 
 


Hi @trssssrt. I see what you are referring to. The buttons block is set to align left by default which my be causing the behavior you are experiencing. Have you attempted to change the alignment to resolve the issue? Get a look at these screenshots.

This one has the alignment issue.


This one I have changed the alignment to center.

**Comment by AnthonyLedesma** [comment]
Gotcha,

I have a pull request up that will set the alignment correctly when you set the Hero block alignment. This will resolve the issue you report. Thank you for taking the time to write all this up.

**Comment by trssssrt** [comment]
Perfect thanks!I'll be looking out for the new update!
    On Friday, April 17, 2020, 02:12:09 PM EDT, Anthony Ledesma <notifications@github.com> wrote:  
 
 


Gotcha,

I have a pull request up that will set the alignment correctly when you set the Hero block alignment. This will resolve the issue you report. Thank you for taking the time to write all this up.
