### ISSUE TITLE
Form block: Messages Not Sending

### ISSUE THREAD

**Issue by JoshuaGoode** [godaddy-wordpress/coblocks#1466]
### Describe the bug:

Attempts to use the CoBlocks form do not seem to fire off wp_mail(). Attempts are not being logged by various mail logging plugins. 

With a colleague of mine at Automattic, I’ve ran a few tests across multiple infrastructures (WordPress.com, SiteGround, personal server…) with various different configurations. Alongside Jetpack’s Form, Contact Form 7, and WP Forms — all work but the CoBlocks form.

This was originally reported by a user we were assisting where Jetpack’s form was working but not the CoBlocks form.

### To reproduce:

1. Ensure your WordPress site can send mail via other forms and calls to wp_mail()
2. Optional: Setup and review logging for these message attempts. This can be done on the server level or via a  mail logging plugin.
2. Add the CoBlocks form to a page.
3. Attempt to use the form.

### Expected behavior:
Message sends properly or, at least, the attempt is logged

### Isolating the problem:

- [X] This bug happens with no other plugins activated
- [X] This bug happens with a default WordPress theme active
- [X] This bug happens **without** the Gutenberg plugin active
- [X] I can reproduce this bug consistently using the steps above

### WordPress version:
WordPress 5.4

### Gutenberg version:
7.9.1 & 7.8.1

**Comment by jordesign** [comment]
I've confirmed this behavior in 2 separate setups.

**Comment by JoshuaGoode** [comment]
Encountered another internal user report with working mail settings, other forms working, but the CoBlocks form failing. I haven't had a moment to dig in further other than confirming the sites have working mail.

Also, a report on your plugin forums at https://wordpress.org/support/topic/coblocks-form-not-working/#post-12720028 that can get other forms to work.

**Comment by EvanHerman** [comment]
Thanks for the bug report @JoshuaGoode . I've got a PR up with some details on what the issue is. The PR should resolve things with the mail not sending. There was a bug in some of the logic that checks whether the form was submitted or not.
