### ISSUE TITLE
CoBlocks Hero Block: Button toolbar unusable/disapears

### ISSUE THREAD

**Issue by khristiansnyder** [godaddy-wordpress/coblocks#1470]
### Describe the bug:
The toolbar for the buttons within a Hero Block is unusable, or simply doesn't show at all, making it impossible to add a link for the button.

When the block has a background image, the toolbar doesn't show at all. When the image is removed, clicking on a button reveals the toolbar, but the toolbar cannot be clicked:
![](https://d.pr/i/I08LuQ+)

Tested in latest versions Chrome and Firefox. Looks like it is only happening on simple sites.

### To reproduce:

1. On a simple site, create a new, blank page and add the Hero Block
2. Try clicking on a button to add a link to the button. When trying to click the link, the toolbar disappears
3. Add a background image to the Hero block, then click on a button. No toolbar shows.

---

First noted in 20639804-hc, where a user couldn't add links to their buttons. 

Workaround: User a cover block and add buttons to it.

**Comment by EvanHerman** [comment]
Hi @khristiansnyder 

Do you have any other plugins installed and active? And what theme are using? Can you try testing without any other plugins active? If the issue persists, can you test with another theme such as our [Go](https://wordpress.org/themes/go/) theme? I've tested it on two themes and I can't seem to reproduce the error.

One work around might be to enable the 'Top Toolbar'. That may make the link clickable in the top of the page, if there is a z-index issue with your theme or another plugin you have installed.

Evan

**Comment by khristiansnyder** [comment]
Hello!

I meant to assign this to a different internal repo, sorry about that! This can be closed.

**Comment by EvanHerman** [comment]
No worries 👌

Have a great rest of your day!
