### ISSUE TITLE
Form Block: Submit button is missing

### ISSUE THREAD

**Issue by xpurichan** [godaddy-wordpress/coblocks#1472]
### Describe the bug:
When we add the co-blocks form block to a page it loads properly in the page editor. Once we preview the page or view the page on the public site, then the "submit" button is missing.

May or may not be related to this previously reported issue:
https://wordpress.org/support/topic/form-has-no-submit-button/

### To reproduce:
1. Create a new page/post and add the coblocks form to it
2. When adding the form you're provided with three variation options, you can choose any of these
3. Save the page, and note that the "submit" button appears in the editor
4. Preview the page, or visit the page and notice that the "submit" button is missing.

### Expected behavior:
Forms should have a submit button

### Isolating the problem:

- [ x ] This bug happens with no other plugins activated
- [ x ] This bug happens with a default WordPress theme active
- [ x ] This bug happens **without** the Gutenberg plugin active
- [ x ] I can reproduce this bug consistently using the steps above

### WordPress version:
Only tested on WPcom, which is on 5.4 currently

### Gutenberg version:
N/A

Originally reported in 2926369-zd

**Comment by JoshuaGoode** [comment]
Encountered another user report.

WordPress 5.4, Gutenberg 7.8.1.

**Comment by richtabor** [comment]
@JoshuaGoode @xpurichan - Hey team, do you know what version of CoBlocks is running on those sites? We're looking into this.

**Comment by xpurichan** [comment]
@richtabor I'm running coblocks `1.26.0` on my site and can reproduce the problem there. I checked the user's site where the problem was initially reported and it is also on `1.26.0`

**Comment by JoshuaGoode** [comment]
I'm going to run a few more tests today.  From what I see, the sites impacted had forms in place prior to the 1.25.0 update fixing the button logic. 

We automatically update these sites to the latest version in the repo.  On my newer sites, the form works fine and adds its own button block.

However, on the sites where we are seeing issues, it seems to be having older behavior and the button is treated as an individual block. Its options and color controls are also on the main form block's settings instead.

**Comment by jrtashjian** [comment]
I did a bit of testing and these are my findings:

- Forms added to a post/page in CoBlocks 1.24.0 and later properly show the button when upgrading to CoBlocks 1.25.0, and 1.26.0.

- Forms added to a post/page in CoBlocks 1.23.0 and earlier are missing the button on the theme side when upgrading to 1.24.0 and later.

- The submit button exists as it should when editing these posts/pages regardless.

I'm working on a fix for this and we are planning to push a few fixes in a patch release on Monday (May 4th).
