### ISSUE TITLE
Masonry: No scripts in front-end when made reusable

### ISSUE THREAD

**Issue by obenland** [godaddy-wordpress/coblocks#1491]
### Describe the bug:
It looks like the Masonry block doesn't enqueue scripts and styles on the front-end when converted into a reusable block.

### To reproduce:

1. Insert a Masonry block
1. Select two images and insert the "gallery"
1. Convert the block to a Reusable Block
1. Preview the post in the front-end
1. Notice the block is being displayed in a bulleted list.
-->

### Screenshots
See https://github.com/Automattic/wp-calypso/issues/42235

### Isolating the problem:

- [x] This bug happens with no other plugins activated
- [x] This bug happens with a default WordPress theme active
- [x] This bug happens **without** the Gutenberg plugin active
- [x] I can reproduce this bug consistently using the steps above

### WordPress version:
5.4.1, 5.5-alpha-47800

### Gutenberg version:
Whatever ships with the above WP versions, 8.0

**Comment by AnthonyLedesma** [comment]
Originated from #1454
