### ISSUE TITLE
"Add accordion item" button not working

### ISSUE THREAD

**Issue by adriantoll** [godaddy-wordpress/coblocks#1499]
### Describe the bug:
I should be able to add an accordion item after the first one in the same block.

### To reproduce:
Add an accordion block and enter title / content in the first accordion. Click the "Add accordion item" button below, the first accordion item collapses, but a new one is not added. Clicking the button again does nothing.

### Expected behavior:
An accordion item should be added.

### Screenshots:
N/A

### Isolating the problem:
- [x] This bug happens with no other plugins activated
- [x] This bug happens with a default WordPress theme active
- [ ] This bug happens **without** the Gutenberg plugin active
- [x] I can reproduce this bug consistently using the steps above

Unclear what the relevance of "This bug happens **without** the Gutenberg plugin active" is above - the block would not be available without it.

### WordPress version:
I'm using a fresh WordPress 5.4.1 installation with TwentyTwenty and only the CoBlocks plugin installed. I'm using the latest versions of MacOS / Chrome.

### Gutenberg version:
N/A

**Comment by richtabor** [comment]
A bit more info: 

It works properly if you're selected on the parent Accordion block: 
<img width="837" alt="Screen Shot 2020-05-26 at 2 36 23 PM" src="https://user-images.githubusercontent.com/1813435/82938323-9fcdde00-9f5f-11ea-8896-6f8cfb0dc031.png">

.. but does _not_ if you're within a previous Accordion Item (as pictured below):
<img width="863" alt="Screen Shot 2020-05-26 at 2 35 37 PM" src="https://user-images.githubusercontent.com/1813435/82938407-c2f88d80-9f5f-11ea-9f4d-222dbcd1e929.png">

**Comment by adriantoll** [comment]
@richtabor I can't match that behaviour. The only way I can see to select the parent accordion block is to start a new page, add an accordion block and then tab to it from the title. Even then I can't add new accordion blocks, I just get the same behaviour.

Another issue I've found while testing is that if I remove the single empty accordion block, then update, then refresh, the accordion block is still there. Not sure if that's to do with something else, but I can't see any obvious JS console errors, and this is a completely vanilla WP installation with no other plugins, and using the default twentytwenty theme. These are the console errors I do see:

```
https://wordpress-vanilla.bureau.test/wp-includes/js/dist/deprecated.min.js?ver=cd9e35508705772fbc5e2d9736bde31b
wp.components.IconButton is deprecated. Please use wp.components.Button instead.

https://wordpress-vanilla.bureau.test/wp-admin/post.php?post=7&action=edit
[DOM] Found 2 elements with non-unique id #_wpnonce: (More info: https://goo.gl/9p2vKq)
<input type="hidden" id="_wpnonce" name="_wpnonce" value="0b39607155">
<input type="hidden" id="_wpnonce" name="_wpnonce" value="e960a150c9">
```
