### ISSUE TITLE
Gutenberg's line-height setting doesn't work if CoBlocks is activated 

### ISSUE THREAD

**Issue by iamtakashi** [godaddy-wordpress/coblocks#1500]
### Describe the bug:
Gutenberg plugin introduced line-height setting, but in a site with CoBlocks, the setting is not reflected on the front of the site.   

### To reproduce:

1. Go to the editor.
2. Add a heading or a paragraph.
3. Alter the line-height in the block setting in the sidebar.
4. Notice the line-height change in the editor.
5. See the front of the site.
6. Notice the line-height setting is not respected on the front of the site.

Or
1. Deactivate CoBlocks.
2. Go to the editor and add a heading or a paragraph.
3. Change the line-height of the blocks and save.
4. Activate CoBlocks.
5. Open the post/page that you've created in 3.
6. See the invalid block error. 

### Expected behavior:
* The line-height setting should be reflected on the front of the site.
* The content made without CoBlock should not break with CoBlocks activated. 

### Screenshots:
An extreme example to illustrate the issue.

**In the editor:**
<img width="1392" alt="Screenshot 2020-05-23 at 03 03 53" src="https://user-images.githubusercontent.com/908665/82719710-ee9c1f00-9ca4-11ea-9d3c-0b9996950509.png">

**Front of the site**
<img width="1392" alt="Screenshot 2020-05-23 at 03 05 02" src="https://user-images.githubusercontent.com/908665/82719719-01aeef00-9ca5-11ea-8b2d-5ce4155b13ac.png">

**Content that altered the line-height setting with CoBlock activated**
<img width="1392" alt="Screenshot 2020-05-23 at 03 18 41" src="https://user-images.githubusercontent.com/908665/82719735-2a36e900-9ca5-11ea-8004-3135605919bd.png">

### Isolating the problem:

- [x] This bug happens with no other plugins activated
- [x] This bug happens with a default WordPress theme active
- [ ] This bug happens **without** the Gutenberg plugin active
- [x] I can reproduce this bug consistently using the steps above

### WordPress version:
5.4.1

### Gutenberg version:
8.1.0

**Comment by alaczek** [comment]
I can reproduce the issue as well.
