### ISSUE TITLE
ISBAT Pricing Table should not ignore empty Price Table Items

### ISSUE THREAD

**Issue by liviopv** [godaddy-wordpress/coblocks#1501]
### Is your feature request related to a problem? Please describe.
When you add an empty Price Table Item on the backend in order to create a line break, the plugin ignores that empty item and skips it on the front end.

### Describe the solution you'd like
An empty Price Table Item should be rendered as empty space on the frontend to avoid alignment problems between multiple columns.

**Backend:**
![Screenshot](https://d.pr/i/0UyBb4+)
Screenshot: https://d.pr/i/0UyBb4

**Frontend:**
![Screenshot](https://d.pr/i/VypyGj+)
Screenshot: https://d.pr/i/VypyGj

### Describe alternatives you've considered
Using `&nbsp;` to populate the empty Price Table Item is the current workaround

**Comment by jrtashjian** [comment]
Thanks @liviopv for the feature request!

I wonder if this is a bug or an intended feature of the RichText component in WordPress Core. Either way, we can take a look to determine that and if we can easily implement a fix for this block alone.

**Comment by AnthonyLedesma** [comment]
I wonder if something changed here between the original reprot and your PR. I am not able to replicate this bug.
