### ISSUE TITLE
Masonry Gallery Block: Unable to edit caption when Custom URL option is enabled

### ISSUE THREAD

**Issue by davipontesblog** [godaddy-wordpress/coblocks#1503]
### Describe the bug:
When you set the block to allow for Custom URL links the caption field is not useable in the editor.

### To reproduce:
- Create a page
- Add the Masonry block
- Select a few images
- Add some captions
- Change Link settings to Custom URL. The captions aren't accessible anymore in the editor canvas. There is nothing you can do to edit captions unless you set the Link Settings option to "None" temporarily. This allows us to edit the caption.

### Expected behavior:
To be able to continue editing both captions and custom URL in the editor canvas. Perhaps add a caption and a link button to each image in the gallery so users can select what they want to edit when space is limited in the canvas.

### Screenshots:
- Picture: https://d.pr/i/Hhe9UA/acHiiJZmpK
- Video: https://d.pr/v/ckbg8K/bPJXAeRhRu

### Isolating the problem:
- [x] This bug happens with no other plugins activated
- [x] This bug happens with a default WordPress theme active
- [x] This bug happens **without** the Gutenberg plugin active
- [x] I can reproduce this bug consistently using the steps above

### WordPress version:
5.4.1

### Gutenberg version:
Gutenberg: 8.1.0
CoBlocks: 1.23.0

**Comment by AnthonyLedesma** [comment]
Effects Masonry, Offset, Stacked.
