### ISSUE TITLE
Required checkbox not working

### ISSUE THREAD

**Issue by PavleMarjanovic** [godaddy-wordpress/coblocks#1517]
Describe the bug:
I should be able to add the checkbox to the contact form so that form can't be sent out without checking it. However, the form is sent out even if this required field is not checked.

To reproduce:

1. Create a Form using the first variation.
2. Add the checkbox field before the Submit button.
3. Make the checkbox field required.
4. Submit the form.

The form should alert that the required field is empty.
Instead, the form is being sent out.

- [X] This bug happens with no other plugins activated
- [X] This bug happens with a default WordPress theme active
- [X] This bug happens **without** the Gutenberg plugin active
- [ ] I can reproduce this bug consistently using the steps above

### WordPress version: 5.4.1

**Comment by KokkieH** [comment]
Noting we've had a report of this from someone using the Coblocks plugin on WordPress.com as well: https://wordpress.com/forums/topic/form-checkbox-required-not-working-as-expected/
