### ISSUE TITLE
ISBAT Change the confirmation text when submitting the Form

### ISSUE THREAD

**Issue by PavleMarjanovic** [godaddy-wordpress/coblocks#1519]
I should be able to change the confirmation text when submitting the Form.

Currently, the Form (with any variation) displays the inputs of all fields and this can't be changed.

**Comment by AnthonyLedesma** [comment]
Hi @PavleMarjanovic,

Would you mind clarifying this request? I want to point out that a user is able to set a custom success message: https://github.com/godaddy-wordpress/coblocks/blob/master/docs/hooks/forms-block.md#customize-success-message

A user is also able to change the input labels, which then show on the confirmation page (and within the sent email). 
![image](https://user-images.githubusercontent.com/30462574/85765077-a076a300-b6ca-11ea-85ab-a2d8976591ed.png)
![image](https://user-images.githubusercontent.com/30462574/85765205-bedc9e80-b6ca-11ea-8251-6d0f0db814f6.png)



What else should be customized? Thanks!

**Comment by PavleMarjanovic** [comment]
Hi @AnthonyLedesma 

The user wants to modify the whole success message, for example: "Your message has been successfully sent. We will reply to you as soon as possible. Have a nice day" with or without input data underneath.

I hope I clarified this a bit more for you.

**Comment by AnthonyLedesma** [comment]
Gotcha. I would recommend using the PHP filter as such.

```php
/**
 * Set a custom success message for a successful form submission
 *
 * @return string Form submission success message
 */
function coblocks_form_sent_message() {

	return __( 'Your message has been successfully sent. We will reply to you as soon as possible. Have a nice day.', 'textdomain' );

}
add_filter( 'coblocks_form_sent_notice', 'coblocks_form_sent_message' );
```

![image](https://user-images.githubusercontent.com/30462574/85775533-b7ba8e00-b6d4-11ea-9eee-89c4a1f858d5.png)

The user could then use Custom CSS and remove the output after success. Something like:
```css
.coblocks-form__submitted ul {
    display: none;
}
```

**Comment by jrtashjian** [comment]
Although it's great that we can do this with a filter, it would be nice to bring a better UX here for everyday users.

Maybe we can add a toolbar button to add some utility fields specific to the form for things like this. I'm imagining something similar to how the HTML block has an "html" and "preview" in the block toolbar. For ours it would switch between setting up the form and saving settings like the successful submission text. We could move the email subject line out of the sidebar and into this new place as well.

@richtabor do you have any thoughts here?

**Comment by richtabor** [comment]
I think something simple like a `TextArea` control within the Settings sidebar would be the way to go. 

Label: `Confirmation text`
Default:  `Your message was sent`

### Screenshot:
<img width="1186" alt="Screen Shot 2020-08-03 at 1 34 25 PM" src="https://user-images.githubusercontent.com/1813435/89210455-1efa1680-d58e-11ea-9fa6-0a0f11979c60.png">
