### ISSUE TITLE
ISBAT use the Posts block with the Gutenberg plugin active

### ISSUE THREAD

**Issue by gwensmithx** [godaddy-wordpress/coblocks#1523]
### Describe the bug:
In **Posts Block** (not Blog Posts block), clicking on the Feed Settings dropdown in the block options in the editor throws an error with Gutenberg Version 8.2.1 plugin activated. Deactivating Gutenberg solves this.

### To reproduce:

1. Go to an Atomic Site and make sure Gutenberg Plugin Version 8.2.1 is installed and activated.
2. Go to any page or post and add the Posts Block.
3. Click on the Feed Settings in the block settings on the right hand side
4. This will show an error as per screenshots below.

### Expected behavior:
Expected to be able to see the Feed Settings with no error

### Screenshots:
![Annotation on 2020-06-03 at 12-33-12](https://user-images.githubusercontent.com/5779512/83683983-7fc39d80-a5a3-11ea-9a7c-bd2e7a1942d3.png)

![Screen Shot 2020-06-03 at 12 32 39 PM](https://user-images.githubusercontent.com/5779512/83684002-881bd880-a5a3-11ea-8beb-adc12963147a.png)

### Isolating the problem:

- [x] This bug happens with no other plugins activated
- [x] This bug happens with a default WordPress theme active
- [ ] This bug happens **without** the Gutenberg plugin active
- [x] I can reproduce this bug consistently using the steps above

### WordPress version:
5.4.1

### Gutenberg version:
8.2.1

**Comment by gwensmithx** [comment]
Originally reported 21621303-hc / 3031464-zd

**Comment by AnthonyLedesma** [comment]
This issue is resolved by #1547
