### ISSUE TITLE
ISBAT use typography controls within editor using Gutenberg

### ISSUE THREAD

**Issue by AnthonyLedesma** [godaddy-wordpress/coblocks#1528]
### Describe the bug:
CoBlocks extension typography controls allow the application of custom inline styles within the editor and front end. This extension is no longer working as expected within the editor when the Gutenberg plugin is active. Styles seem to be properly applied to the front end.

### To reproduce:
First, ensure Gutenberg plugin is active at V8.2.1+

1. Add a paragraph block and sample text.
2. Open the typography controls toolbar option.
3. Apply custom typography settings on the block.
4. See that no custom styles are applied within the editor.

This behavior does not occur when running 5.4.1 without the Gutenberg plugin running.

### Expected behavior:

Expect editor to reflect the same as the front end.

### Screenshots:

![typographyGutenbergBug](https://user-images.githubusercontent.com/30462574/84189047-73c75800-aa49-11ea-9a03-0fea4e4bde4e.gif)

### Isolating the problem:

- [x] This bug happens with no other plugins activated
- [x] This bug happens with a default WordPress theme active
- [ ] This bug happens **without** the Gutenberg plugin active
- [x] I can reproduce this bug consistently using the steps above

### WordPress version:

5.4.1

### Gutenberg version:

8.2.1

**Comment by richtabor** [comment]
Closed by #1526

**Comment by AnthonyLedesma** [comment]
#1526 Does not resolve this issue. This issue is outstanding.

**Comment by AnthonyLedesma** [comment]
This bug no longer exists with WordPress 5.5 or Gutenberg 8.6.1.
