### ISSUE TITLE
ISBAT use a properly styles Dimension Control component

### ISSUE THREAD

**Issue by AnthonyLedesma** [godaddy-wordpress/coblocks#1537]
### Describe the bug:
Dimension Controls component no longer renders correctly and could use an overhaul to ensure proper functionality with Gutenberg 8.3.0 and with current core WordPress 5.4.2.

### To reproduce:
Row block uses the Dimension Control component.
Without Gutenberg
![dimensionControlsNoGb](https://user-images.githubusercontent.com/30462574/84709763-aa084a00-af17-11ea-9556-5e2e87f0b1a7.gif)

With Gutenberg
![dimensionControlsGb](https://user-images.githubusercontent.com/30462574/84709766-ad033a80-af17-11ea-8aae-1ebaf9377416.gif)

### Expected behavior:

Expect all buttons to have proper outlines and secondary/primary class names where applicable. Related PR here: #1532

### Isolating the problem:

- [x] This bug happens with no other plugins activated
- [x] This bug happens with a default WordPress theme active
- [ ] This bug happens **without** the Gutenberg plugin active
- [x] I can reproduce this bug consistently using the steps above

### WordPress version:

Occurs with 5.4.2 and 5.5beta.

### Gutenberg version:

8.3.0
(Occurs with and with the Gutenberg plugin active)

**Comment by richtabor** [comment]
Closed via #1544
