### ISSUE TITLE
ISBAT add a Hero block without errors

### ISSUE THREAD

**Issue by fullofcaffeine** [godaddy-wordpress/coblocks#1551]
### Describe the bug:

The Hero block(s) fails with an error the first time I add them and only render correctly when I save and refresh the page. 

### To reproduce:

1. Install CoBlocks **1.26.3**;
2. Install Gutenberg **8.3.0**;
3. Go to wp-admin/post-new.php;
4. Add a new CoBlocks' `Hero` block to the page

### Expected behavior:

I should be able to add a Hero block and it should render correctly.

### Screenshots:

I reproduced the issue using the local Docker env and **recorded a screencast where I go through the steps to reproduce it:** https://www.dropbox.com/s/wqs4ymergg9cfou/coblocks-issue-dev.mp4?dl=0. Ignore the part of this screencast after the page refresh, as it is related to the other issue reported [here](https://github.com/godaddy-wordpress/coblocks/issues/1550) 

### Isolating the problem:

- [x] This bug happens with no other plugins activated **(Gutenberg 8.3.0)**
- [x] This bug happens with a default WordPress theme active
- [ ] This bug happens **without** the Gutenberg plugin active **(No, but I can't find the `Hero` block if I don't activate Gutenberg 8.3.0)**
- [x] I can reproduce this bug consistently using the steps above

### WordPress version:

I'm using `WordPress 5.5-alpha-47426-src`, which is the one that is downloaded `wp-env` included with this repo (I [followed](https://github.com/godaddy-wordpress/coblocks/blob/master/docs/contributors/getting-started.md) the instructions here).
 
### Gutenberg version: 8.3.0

Let me know if you need anything else or if I could help in any way :) 

Thanks!

**Comment by AnthonyLedesma** [comment]
Will be closed by #1515
