### ISSUE TITLE
ISBAT - Block "Plugin" does not search further than the second page

### ISSUE THREAD

**Issue by N1k0lay** [godaddy-wordpress/coblocks#1554]
Block "Plugin" does not search beyond the second page. The search takes place only on the first page of the search in the plugin library. You have to register the plugin slug through the HTML code.

**Comment by jrtashjian** [comment]
@N1k0lay I'm having trouble understanding this bug report and am going to close it. Please open a new bug report and provide enough detail so we can reproduce it – if you are having an issue with CoBlocks.

Thanks!
