### ISSUE TITLE
"Posts" block settings issue

### ISSUE THREAD

**Issue by PavleMarjanovic** [godaddy-wordpress/coblocks#1555]
(1) CoBlocks options menu becomes unusable when a category is selected which has no post yet
(2) CoBlocks number of columns appears to be limited by the number of currently present posts

(1) CoBlocks options menu becomes unusable
How I reproduce the issue:
* Edit a post or page
* Insert a “Posts” block
* Select the block and go to its settings
* Select “Feed settings”
* Select a category that has not yet been assigned to a single post
* All block settings disappear except “Advanced” and the “Feed Settings/My Blog or external feed”

consequences:
(1) e.g. you can no longer edit the appearance (e.g. thumbnail size)
(2) and in particular: you cannot change the ‘Category’ settings back to the original value

### Screenshots:
http://prntscr.com/t74dra

- [X] This bug happens with no other plugins activated
- [X] This bug happens with a default WordPress theme active
- [X] This bug happens **without** the Gutenberg plugin active
- [X] I can reproduce this bug consistently using the steps above

### WordPress version:
5.4.2

**Comment by jrtashjian** [comment]
This is related to #1561
