### ISSUE TITLE
Lightbox does not render &amp; properly

### ISSUE THREAD

**Issue by jchwenger** [godaddy-wordpress/coblocks#1558]
When using Lightbox, the '&' sign in legends is rendered ok in the gallery, but not in the full-screen version of the image?

I tried to change the legend (in the Media gallery editor) to &amp; or &#38;, but to no avail. I've been wondering if it might not be caused by the script that extracts the figcaption using innerHTML instead of something else, e.g. textContent?

Thanks in advance!

Test page, it appears on any image with a legend containing '&': https://artasperto.ch/lightbox/

Coblocks: Version 2.0.2 
WP: Version 5.4.2

**Comment by jchwenger** [comment]
I can confirm that by changing `innerHTML` to `textContent` [here](https://github.com/godaddy-wordpress/coblocks/blob/master/src/js/coblocks-lightbox.js#L103) I can get the library to display the expected behaviour, namely: the '&' in my caption is rendered correctly in the lightbox, and not as a literal '&amp;'.

**Comment by AnthonyLedesma** [comment]
Excellent idea @jchwenger! I'll see about getting that PR up next week. Please feel free to submit a pull request if you have the time. 😀

**Comment by jchwenger** [comment]
Thanks! I can see about that, although this was a quick hack, I don't have the dev setup for this I'm afraid. I notice also that it's impossible to have italics in the lightbox legend, either you get rid of all html entirely with the textContent, or your get literal `<em></em>` in the lightbox caption as well. Unsure how I'd go about fixing that.

**Comment by jrtashjian** [comment]
We've scheduled this to go out in the [next release](https://github.com/godaddy-wordpress/coblocks/milestone/40). @jchwenger our next release is the 23rd so if you'd like to make the contribution could you submit a PR by the 22nd? We'll wait until then before submitting our own to hit the deadline.

**Comment by jchwenger** [comment]
Right, here's an attempt [here](https://github.com/godaddy-wordpress/coblocks/pull/1566), hopefully without problems or errors (I am not very experienced with PRs, thanks for your patience!).
