### ISSUE TITLE
Option to have figcaptions below images in masonry

### ISSUE THREAD

**Issue by jchwenger** [godaddy-wordpress/coblocks#1560]
Hi,

Another request: it'd be great to be able to place the captions right below the images in the masonry, instead of having them on top of them? An issue arises when you have very clear and very dark pics in one gallery: even if you pick the clear or dark caption theme some captions will be hidden or nearly so. 

Thanks for reading!

Cheers,
Jeremie

**Comment by jrtashjian** [comment]
Thanks for the feature request @jchwenger! This can actually be accomplished with a little CSS using the `.wp-block-coblocks-gallery-masonry figcaption` selector. The caption is absolutely positioned so the following CSS code would put the caption beneath the image:

```
.wp-block-coblocks-gallery-masonry figcaption {
    position: static !important;
}
```

You can change any spacing, sizing, colors, etc using CSS as well. I'm going to close this issue for now but should we get more requests for this feature we can reconsider this request.

**Comment by jchwenger** [comment]
Hi @jrtashjian, thanks for this! Yes indeed, it can be positioned in such a way, but as I was trying to achieve something like this, I realised that the height position of all images in the masonry seem to be precalculated by the algorithm, each of them having a specific `top: X px;` property that isn't affected by margins or padding etc. And so unless I have a short caption, it disappears under the next element, or the bottom limit of the gallery. That can somehow be arranged by increasing the margins (but both left/right and up/down have to be increased in parallel for this to work), and only for short captions, but then I lose the left and right alignments of the whole gallery within its container. It still feels like the cleanest way would be to have some sort of calculation of the height needed for the captions when building the gallery, so it's included in the height of the `coblocks-gallery--figure`, but of course easy to say! Thanks in any case for this and in the meantime I'll keep hacking :D.

**Comment by jrtashjian** [comment]
Are you loading the page with the new CSS or updating the CSS through your brower's web inspector tools? It should work if it's the former because the masonry JS library calculates the image positions on load.

**Comment by jchwenger** [comment]
Ooh thanks for this, I didn't know. It worked indeed, props!
