### ISSUE TITLE
Post Carousel - adding a Category results in perpetual loading state and rest error.

### ISSUE THREAD

**Issue by Addison-Stavlo** [godaddy-wordpress/coblocks#1561]
### Describe the bug:

Adding a category to the 'Post Carousel' causes a perpetual loading state and rest error:

![Screen Shot 2020-07-06 at 5 02 11 PM](https://user-images.githubusercontent.com/28742426/86643166-76669000-bfaa-11ea-880f-ec19ffdc9bc9.png)

![Screen Shot 2020-07-06 at 3 36 30 PM](https://user-images.githubusercontent.com/28742426/86643059-60f16600-bfaa-11ea-939a-584fb5762bc9.png)

### To reproduce:

Encountered on WordPress 5.5 with no other plugins activated (twentytwenty theme and others).
Also noted on previous WordPress versions with Gutenberg activated.

1. Go to the Editor.
2. Add a 'Post Carousel' block.
3. Scroll down to 'Feed settings' in the block sidebar.
4. Type in a string in the 'Categories' input and press 'enter'.
5. Observe the error in the console and the block's loading state.

### Expected behavior:

I would expect there to be no error and for the category to be added.
Given an error, I would expect the block to not stay in the 'loading' state forever.

### Isolating the problem:

- [x] This bug happens with no other plugins activated
- [x] This bug happens with a default WordPress theme active
- [x] This bug happens **without** the Gutenberg plugin active
- [x] I can reproduce this bug consistently using the steps above

### WordPress version:

WordPress 5.5 w/o Gutenberg.

### Gutenberg version:

Earlier versions of WordPress with the most recent Gutenberg release active may also be able to reproduce this issue.

**Comment by jrtashjian** [comment]
Thank you for the bug report @Addison-Stavlo!

✅ Confirmed that I am also getting an error using your steps to reproduce.
