### ISSUE TITLE
Can't put buttons inside of accordion block

### ISSUE THREAD

**Issue by jhned** [godaddy-wordpress/coblocks#1563]
### Describe the bug:
I should be able to put a buttons block inside of an accordion block item. Adding a buttons block inside of an accordion item block collapses the accordion item. Re-opening the accordion item and clicking on "Add Text" in the button collapses the accordion item block again.

### To reproduce:
1. Add a new page
2. Add an accordion item block
3. Add a title
4. Add a buttons block inside of the accordion content.

### Expected behavior:
Should be able to edit the button text.

### Isolating the problem:

- [X] This bug happens with no other plugins activated
- [X] This bug happens with a default WordPress theme active
- [X] This bug happens **without** the Gutenberg plugin active
- [X] I can reproduce this bug consistently using the steps above

### WordPress version:
5.4.2

**Comment by richtabor** [comment]
Verified ✅
