### ISSUE TITLE
ISBAT see the entire (not-cropped) image in the Carousel block

### ISSUE THREAD

**Issue by jchwenger** [godaddy-wordpress/coblocks#1564]
This would be great, and is fairly self-explanatory.
In the current version, so far as I can see, images in a carousel get cropped automatically. It would be great if there was an option to let the carousel adjust to the image height dynamically!

I've just seen a great PR that would introduce light box integration to everything, looking forward! (That would have been on my list of requests.)

Cheers!

**Comment by jrtashjian** [comment]
Thanks for the feature request @jchwenger! I've updated the title to better reflect what you're requesting. We haven't made any decisions around this yet but I am leaving a note for later should we implement this.

**Developer note:** Look into using the [`adaptiveHeight`](https://flickity.metafizzy.co/options.html#adaptiveheight) option of Flickity to accomplish this. Other blocks may also benefit from this.
