### ISSUE TITLE
Unable to delete second button (in Hero block, maybe others as well)

### ISSUE THREAD

**Issue by bradley2083** [godaddy-wordpress/coblocks#1572]
### Describe the bug:
Added the Hero block and unable to delete the second button in the button block.

### To reproduce:
1. Add Hero block
2. Attempt to delete second (right) button

### Expected behavior:
Option to have 1, 2 or no buttons

### Screenshots:
<img width="586" alt="Screen Shot 2020-07-14 at 1 57 51 PM" src="https://user-images.githubusercontent.com/1781226/87475818-476ba200-c5da-11ea-92c8-49239034f4a2.png">

### Isolating the problem:
- [x] This bug happens with no other plugins activated
- [x] This bug happens with a default WordPress theme active
- [x] This bug happens **without** the Gutenberg plugin active
- [x] I can reproduce this bug consistently using the steps above

### WordPress version:
5.4.2

**Comment by richtabor** [comment]
Thanks for the report @bradley2083. I'm unable to replicate this with Gutenberg 8.5, are you?

**Comment by bradley2083** [comment]
This does appear to be fixed with Gutenberg 8.5.1 active.
