### ISSUE TITLE
Hero block: cannot permanently delete placeholder text / buttons

### ISSUE THREAD

**Issue by bradley2083** [godaddy-wordpress/coblocks#1574]
### Describe the bug:
If you add the HERO block and remove the heading, paragraph and buttons (so it's just the image), then save.  The initial front-end view looks good.  Then if you edit the page, you'll see the placeholder headline, paragraph and button options reappear. 

### To reproduce:
1. In a new page, add a /hero block.
2. Delete the headline, paragraph, and buttons.
3. Add an image to the hero block
4. Save the page or post 
5. View the page or post in the front-end and it should look good (just the image)
6. Edit the page or post
7. Notice the hero block shows the placeholder options again (and if you resave the page without deleting those options again), the empty fields appear in your hero block (empty heading, paragraph and buttons).

### Screenshots:
<img width="753" alt="Screen Shot 2020-07-16 at 1 51 56 PM" src="https://user-images.githubusercontent.com/1781226/87721600-8c730e00-c76b-11ea-8286-012d0b93e7e3.png">

### Isolating the problem:

- [x] This bug happens with no other plugins activated
- [x] This bug happens with a default WordPress theme active
- [x] This bug happens **without** the Gutenberg plugin active
- x] I can reproduce this bug consistently using the steps above

### WordPress version:
5.4.2

**Comment by bradley2083** [comment]
Also attaching screenshot of the buttons that appear in the front-end when you leave the placeholders empty and save.  The heading and paragraph don't appear (which is good), but the button block does.  

<img width="717" alt="Screen Shot 2020-07-16 at 1 56 13 PM" src="https://user-images.githubusercontent.com/1781226/87722062-4e2a1e80-c76c-11ea-9b60-37dd9d7ab661.png">

**Comment by richtabor** [comment]
I'm able to replicate all the blocks coming back, though the particular buttons block issue I believe is derivative of this core issue: https://github.com/WordPress/gutenberg/issues/17221

**Comment by bradley2083** [comment]
I'm not sure if it's a derivative of that issue or not.  If the button is left empty along with the heading and paragraph placeholders that appear, only the buttons (without button text) seem to be saved.  If empty, just like the heading and paragraph, should the buttons block not appear in the front-end?

**Comment by AnthonyLedesma** [comment]
Tested these issues today and was not able to replicate them on the latest version of CoBlocks. Seems the ability to delete the buttons correctly was fixed here: https://github.com/godaddy-wordpress/coblocks/pull/1515. Not able to see non-user-filled blocks on the front-end as expected.
