### ISSUE TITLE
ISBAT Posts block: time and content gets hidden under thumbnail on Chrome v84.0.4147.89

### ISSUE THREAD

**Issue by gdandrija** [godaddy-wordpress/coblocks#1579]
### Describe the bug:

Thumbnail styles are discarded by browser, this only happens with Chrome v84.0.4147.89, later versions and other browsers work fine, so it is likely caused by changes in the latest version of Chrome and their new "@import'' CSS policy.

As a result, thumbnails are overlapping dates and content of a post on archive pages.

### To reproduce:
1. Create 5 or more posts with some text content and thumbnails
2. Create a new Posts block using the parameters provided:
– stacked
– show post date
– show post content
– max words in content: 12
– columns: 4
– gutter: M
– thumbnail style 16:9
3. Save post
4. Visit the page

### Expected behavior:
You should see posts and text that are not overlapping.

### Screenshots:
This is how the website worked on a default theme and Chrome 83: https://i.imgur.com/3iM0Zly.png
Here is how it works with Chrome v84.0.4147.89: https://i.imgur.com/eJHyM57.png

### Isolating the problem:

- [x ] This bug happens with no other plugins activated
- [x ] This bug happens with a default WordPress theme active
- [x ] This bug happens **without** the Gutenberg plugin active
- [x ] I can reproduce this bug consistently using the steps above

### WordPress version:
5.4.2

Additional note:
Bug reported initially on WordPress.org Support page: https://wordpress.org/support/topic/posts-block-time-and-content-gets-hidden-behind-under-thumbnail/ I also tested this out myself and after updating Chrome I could verify that issue exists.

The user also provided a workaround solution, but it seems that other styles are not working for this block as well.

This seems to be the change in content display standards, please take a look and see what can be done. Thanks in advance.

**Comment by bishless** [comment]
We're seeing the same behavior on the front page of our site [https://beachfleischman.com](https://beachfleischman.com/) (mid-way down the page)

Content renders as expected in other browsers - including browsers based on Chrome like Edge or Vivaldi. I'm seeing it in Chrome 84.0.4147.105 (Windows).

**Comment by richtabor** [comment]
This issue has been resolved in a recent CoBlocks release. Thanks!
