### ISSUE TITLE
Hero block: z-index of edit/remove image component block too high

### ISSUE THREAD

**Issue by bradley2083** [godaddy-wordpress/coblocks#1580]
### Describe the bug:
If you add a hero block and click to edit (or remove the background image), the components panel's z-index is too high making it appear on top of the media upload screen.

### To reproduce:
1. Add hero block
2. Click icon to add a new image
3. Add image and click Select to insert into page
4. Now, click the image 
5. Click the edit image icon 
6. Click Edit Background
7. Now, on the media screen you will see the components panel overlay on top (should be hidden)

### Expected behavior:
Media upload screen should appear on top of edit/remove background components panel.

### Screenshots:
<img width="567" alt="Screen Shot 2020-07-20 at 4 13 46 PM" src="https://user-images.githubusercontent.com/1781226/87995326-070d9780-caa4-11ea-8cff-db1af7428b1f.png">

Video here: 
https://soapbox.wistia.com/videos/QAr2bY0gt4

### Isolating the problem:

- [x] This bug happens with no other plugins activated
- [x] This bug happens with a default WordPress theme active
- [x] This bug happens **without** the Gutenberg plugin active
- [x] I can reproduce this bug consistently using the steps above

### WordPress version:
5.4.2

**Comment by salimserdar** [comment]
@bradley2083 FYI -> This issue is related to the core of the Gutenberg editor. I just fixed and send PR[ here.](https://github.com/WordPress/gutenberg/pull/25099)

**Comment by jrtashjian** [comment]
Resolved by #1863
