### ISSUE TITLE
Deprecate IconButton component

### ISSUE THREAD

**Issue by igorradovanov** [godaddy-wordpress/coblocks#1599]
### Describe the bug:
Deprecate the IconButton component in favor of Button.

Please see https://github.com/wordpress/gutenberg/pull/19299 for more information.

### To reproduce:

Please open the Javascript console and focus on the warnings screen.

### Expected behavior:

N/A

### Screenshots:

N/A

### Isolating the problem:

- [x] This bug happens with no other plugins activated
- [x] This bug happens with a default WordPress theme active
- [ ] This bug happens **without** the Gutenberg plugin active
- [x] I can reproduce this bug consistently using the steps above

### WordPress version:

5.4.2

### Gutenberg version:

8.6.1

**Comment by richtabor** [comment]
@AnthonyLedesma Does this implement <WP 5.5 editing?
