### ISSUE TITLE
ISBAT consistenly apply styles within editor across versions

### ISSUE THREAD

**Issue by AnthonyLedesma** [godaddy-wordpress/coblocks#1604]
### Describe the bug:

CoBlocks uses CSS selectors which will soon deprecate with the release of WordPress 5.5. This need to deprecate is due to [changes in markup](https://github.com/WordPress/gutenberg/pull/21822) within the editor. The specific selector which should be adjusted is `.wp-block[data-type="*"]` and can be located using Regex `.wp-block\[.*?\]`.

At this time the selector in question can be found 137 times among 46 files including both .scss and .cypress.js files.

This PR: https://github.com/godaddy-wordpress/coblocks/pull/1603 addresses a bug with the Media Card block that is directly related to changes in editor markup.

### Isolating the problem:

- [x] This bug happens with no other plugins activated
- [x] This bug happens with a default WordPress theme active
- [x] This bug happens **without** the Gutenberg plugin active
- [x] I can reproduce this bug consistently using the steps above

### WordPress version:

Happens with 5.5 WP ( OR 5.4.2 with Gutenberg active )

### Gutenberg version:

8.5+ ( or Core 5.5 )

**Comment by richtabor** [comment]
Could you give example of a selector that needs to be updated?

**Comment by richtabor** [comment]
And is this only in the editor, or both?

**Comment by AnthonyLedesma** [comment]
This effects editor styles only. Another example of a block that definitely needs to be addressed is the Shape Divider block. 
https://github.com/godaddy-wordpress/coblocks/blob/ba2ebf5ceb04ae2eeda2a1dbdc211ba8c3812dee/src/blocks/shape-divider/styles/editor.scss#L1

This is the generated markup within the editor 
![image](https://user-images.githubusercontent.com/30462574/89056598-22349e80-d311-11ea-8d12-c6d44fcc13b3.png)

The end result here is styles that do not take effect within the editor.

**Comment by richtabor** [comment]
Ah, this is related to the light block wrapper efforts in core (which are causing other little display issues as well). Good find.
