### ISSUE TITLE
Row block is applying width to blocks inside the columns

### ISSUE THREAD

**Issue by Oosik** [godaddy-wordpress/coblocks#1613]
### Describe the bug:
In the admin, the row block seems to applying the column width property to blocks within the columns. Resulting in extremely narrow columns. There doesn't seem to be an issue on the frontend, seems to just be an issue in the admin. I saw it was reported here: https://wordpress.org/support/topic/row-block-column-width-issue-in-editor/ but there has been no follow up and I don't see it here. Sorry if this is a known issue but there have been several updates since and the problem still persists. 

### To reproduce:

1. with a fresh install, default twentytwenty theme and the latest coblocks create a page
2. enter a title
3. add a Row block via coblocks (2 column 50/50)
4. add a paragraph to both columns

at this point you should be able to see pretty large spacing between the columns even if you padding and margin are set to none. if you open your dev tools you can see that the paragraphs within each column have a width of 50%.

### Expected behavior:
I'd expect that the width control for the row block to only affect the width of the columns and not the width of child blocks.

### Screenshots:
![Screenshot from 2020-08-06 08-48-43](https://user-images.githubusercontent.com/16123016/89539943-01ad8e00-d7c2-11ea-9ce4-c5a7235f5481.png)

### Isolating the problem:

- [x] This bug happens with no other plugins activated
- [x] This bug happens with a default WordPress theme active
- [ ] This bug happens **without** the Gutenberg plugin active
- [x] I can reproduce this bug consistently using the steps above

### WordPress version:
5.4.2

### Gutenberg version:
core

**Comment by gdandrija** [comment]
Hey guys,

Multiple users are reporting the same issue, it appears that it has been reported already multiple times:

https://wordpress.org/support/topic/row-block-column-width-issue-in-editor/
https://wordpress.org/support/topic/columns-100-broken/

Can you please take a look and hopefully resolve it soon?

Have a nice day,
Andrija

**Comment by DustinWStout** [comment]
Yet another update, and yet another failure to address this issue. Not even a word about it.

**Comment by richtabor** [comment]
Hey @DustinWStout, I just put this on the roadmap. 👍
