### ISSUE TITLE
ISBAT Services block image cannot be linked

### ISSUE THREAD

**Issue by gdandrija** [godaddy-wordpress/coblocks#1624]
### Is your feature request related to a problem? Please describe.
No, checking if there is a way that Services block can add an option to add links to images so that when the user clicks on image it would link him to another page.

### Describe the solution you'd like
Ideally, a user should be able to have an option to insert a link to the service item, which will then make the image linked. While this may be achieved using HTML on the title and description sections as well as the optional CTA button, there is no way of setting this on an image.

### Describe alternatives you've considered
The only alternative would be not using the Services block and stacking elements or using custom HTML at this point

### Additional context/screenshots
https://i.imgur.com/9gdwCy2.png this is where it would be ideal to introduce this option.

It could look similar to the CTA option: https://i.imgur.com/XLXVULS.png I hope this helps

**Comment by AnthonyLedesma** [comment]
This is closed with https://github.com/godaddy-wordpress/coblocks/pull/1807
