### ISSUE TITLE
ISBAT CoBlocks cannot be used alongside Ghost Kit since WP version 5.5

### ISSUE THREAD

**Issue by gdandrija** [godaddy-wordpress/coblocks#1625]
### Describe the bug:
CoBlocks cannot be used alongside Ghost Kit since WP version 5.5. Returns an error otherwise.

### To reproduce:

1. Go to any page using both sets of blocks
2. You will be presented with an error: This block has encountered an error and cannot be previewed.
3. Disabling any of those plugins makes their respective blocks work

### Expected behavior:
Loading the page with blocks from both plugins working together.

### Screenshots:
https://i.imgur.com/0IduVSW.png

### Isolating the problem:

- [ ] This bug happens with no other plugins activated - except Ghost Kit with which it conflicts
- [x] This bug happens with a default WordPress theme active
- [x] This bug happens **without** the Gutenberg plugin active
- [x] I can reproduce this bug consistently using the steps above

WordPress version:
5.5

Additional note:
May be a Gutenberg API issue, worth checking regardless.

**Comment by gdandrija** [comment]
Initially submitted on a support forum:

https://wordpress.org/support/topic/co-blocks-and-ghost-kit-break-editor-in-wordpress-5-5/

**Comment by jonesch** [comment]
We are dealing with the same issue and I had some more notes to add:

- We are also seeing the `This Block has encountered an error and cannot be previewed.` message on every page or post we are trying to edit. Same messaging as the screenshot from imgur above.

- While editing a page via `post.php?post=XXXX&action=edit`, we are seeing a number of console errors in dev tools
```
Uncaught TypeError: $ is not a function
    at editor.js?ver=1592314082:formatted:1
```
```
react-dom.min.js:103 TypeError: e.querySelector is not a function
    at coblocks.js?ver=173ddaacc816dc5a625419abfd70be65:58
    at coblocks.js?ver=173ddaacc816dc5a625419abfd70be65:58
    at NodeList.forEach (<anonymous>)
    at coblocks.js?ver=173ddaacc816dc5a625419abfd70be65:58
    at NodeList.forEach (<anonymous>)
    at coblocks.js?ver=173ddaacc816dc5a625419abfd70be65:58
    at Vb (react-dom.min.js:104)
    at Xi (react-dom.min.js:151)
    at unstable_runWithPriority (react.min.js:26)
    at Ma (react-dom.min.js:52)
```

Hope that helps and we look forward to seeing what you all find. Thanks!!

**Comment by cagrimmett** [comment]
Looks like Ghost Kit updated yesterday to 2.14.0: https://wordpress.org/plugins/ghostkit/#developers

I did some testing and verified that Ghost Kit 2.14.0 and CoBlocks 2.2.1 no longer conflict.

**Comment by jonesch** [comment]
@cagrimmett, thanks for taking a look. I also looked back again and am seeing most of the issues ironed out now.

But I am seeing new issues with both versions @cagrimmett listed above now throwing a few new console errors that are definitely tied back to Ghost Kit and not CoBlocks. We'll try and ping their team to see if we share our findings with them.

**Comment by richtabor** [comment]
Thanks for keeping us in the loop; appreciate it!
