### ISSUE TITLE
ISBAT Icon height in backend extremely high

### ISSUE THREAD

**Issue by edrush** [godaddy-wordpress/coblocks#1627]
### Describe the bug:

As an author, I should be able to add an icon without making it fill up my screen, depending on post length.

### To reproduce:

1. Go to "Posts" > "Add new".
2. Add content like text or images, especially with big height.
3. Add a block of type Icon.
4. To better see the problem, set the "Background color" to green or red.

### Expected behavior:

The icon should be displayed only as high as it will be display on the frontend.
### Screenshots:
![Screenshot 2020-08-17 at 17 02 42](https://user-images.githubusercontent.com/4974858/90415006-ca3bbd00-e0b0-11ea-9f0d-d2da22ef43b4.png)
### Isolating the problem:

- [ ] This bug happens with no other plugins activated
no: it happens due the Plugin "Shariff" Version 4.6.5 - maybe you can give me a hint what to search for? Too me it seems the css declarations of height:auto are responsible
- [x] This bug happens with a default WordPress theme active
- [ ] This bug happens **without** the Gutenberg plugin active
- [x] I can reproduce this bug consistently using the steps above

### WordPress version:

Wordpress 5.5.0
### Gutenberg version:

Where do I find that?

**Comment by richtabor** [comment]
Hey @edrush, I tried to replicate this but couldn't do so successfully. Do you mind making a gif/screen recording?

<img width="1229" alt="Screen Shot 2020-08-25 at 3 49 42 PM" src="https://user-images.githubusercontent.com/1813435/91220838-c7f9e400-e6ea-11ea-93a9-d20033b4ee71.png">

**Comment by edrush** [comment]
hey @richtabor, sorry for answering so late and thank you for your answer! I was up to create a screen recording today for this issue but it seems to be gone on my system, too. Probably due to to recent updates. 

Best regards!
