### ISSUE TITLE
Post blog category filter not working

### ISSUE THREAD

**Issue by emMitchell** [godaddy-wordpress/coblocks#1632]
### Describe the bug:
I should be able to filter the posts by category using "Posts" block

### To reproduce:

1. Edit the page 
2. Add Posts block
3. Choose a category in the Feed settings 
4. See error on the fronted - category filter is not applied - all posts are displayed instead. However you can see the correct posts in the backend. 

### Expected behavior:
Posts from selected category should be displayed 

### Screenshots:
http://prntscr.com/u23e6v
http://prntscr.com/u23f9b
by the way, featured image is displayed over the post title - http://prntscr.com/u23ew9

### Isolating the problem:

- [ x] This bug happens with no other plugins activated
- [x ] This bug happens with a default WordPress theme active
- [ x] This bug happens **without** the Gutenberg plugin active
- [x ] I can reproduce this bug consistently using the steps above

### WordPress version:
WordPress 5.5

**Comment by eduardozulian** [comment]
Same here but on WordPress.com
