### ISSUE TITLE
Typography controls are ignored inside Buttons block

### ISSUE THREAD

**Issue by tbradsha** [godaddy-wordpress/coblocks#1640]
### To reproduce:

1. Create a Buttons block.
2. Add text to the button label
3. Try to adjust font, size, etc.

While it partially works on the live site (font size doesn't change) it doesn't change anything in the editor. 

* Editor:
 ![image](https://user-images.githubusercontent.com/32492176/90934111-fa8ba000-e3bd-11ea-9c91-621c2a98123d.png)
* Live site:
 ![image](https://user-images.githubusercontent.com/32492176/90934304-4c342a80-e3be-11ea-8056-ac6153e45464.png)

### Isolating the problem:

- [x] This bug happens with no other plugins activated
- [x] This bug happens with a default WordPress theme active
- [x] This bug happens **without** the Gutenberg plugin active
- [x] I can reproduce this bug consistently using the steps above

### WordPress version:

WP 5.5 + CoBlocks 2.2.2

### Gutenberg version:

With/without Gutenberg v8.8.8

**Comment by sandymcfadden** [comment]
This seems to happen with core blocks as well. The Cover block, Media & Text block, Group, and Column Block, are examples where this happens. Possibly any container block where blocks are added inside others.

**Comment by scosgro** [comment]
Seeing that this was closed, so wanted to report that this is still happening, or happening again (if it was fixed previously). 

The font options on the Buttons Block are ignored at the moment. 

![buttonsblock](https://user-images.githubusercontent.com/30731356/102294931-2697d780-3eff-11eb-8cc2-30d04772b854.gif)

**Comment by sophiegyo** [comment]
I encountered this yesterday and it looks like for buttons it's very much due to the custom size being applied to the parent element of the actual `a` element inside the button, which means that theme's `font-size` for links takes precedence:
<img width="409" alt="Button, viewed as HTML" src="https://user-images.githubusercontent.com/36608681/114978505-8f7d6500-9e89-11eb-80d3-b786f62d17e5.png">

**Comment by eherman-godaddy** [comment]
It doesn't look like this is an issue any longer, I'm not able to reproduce this. I tested with the buttons block, the hero block and a few others.

![typography-controls-demo](https://user-images.githubusercontent.com/85256006/128256422-d60e938a-2d8c-4fc1-ad2c-2c37b355810e.gif)
