### ISSUE TITLE
ISBAT see correct cursor when hovering Offset/Collage image

### ISSUE THREAD

**Issue by WunderBart** [godaddy-wordpress/coblocks#1644]
### Describe the bug:

In the editor, when hovering an image in the Offset/Collage gallery block that has the Lightbox setting on, the cursor is set to a magnifying glass (`zoom-in`). This can be misleading as nothing will happen when clicked. Note that it doesn't happen for Masonry block.

### To reproduce:

1. Add Offset/Collage blocks and add some photos
2. Set the Lightbox setting on
3. Hover over one of the images
4. Notice the cursor changing to a magnifying glass

### Expected behavior:
Zooming is possible on preview/published site only so the cursor shouldn't change in the editor.

### Screenshots:

<img width="932" alt="Screenshot 2020-08-25 at 14 47 20" src="https://user-images.githubusercontent.com/1451471/91176011-f2936f00-e6e1-11ea-8a40-5ccb42bc72cc.png">

### WordPress version:
5.5

### Gutenberg version:
8.7.1

**Comment by richtabor** [comment]
Verified.
