### ISSUE TITLE
ISBAT Add more than one accordion item

### ISSUE THREAD

**Issue by adriantoll** [godaddy-wordpress/coblocks#1678]
### Describe the bug:
Can't add more than one accordion item. Seems identical to #1499 

### To reproduce:
Clean install of WP 5.5 with TwentyTwenty and only Coblocks active. 

- Start a new page
- Add an accordion item with title and content
- Click "Add accordion item" button
- First accordion item collapses, but no new one is added

### Expected behavior:
A new accordion item should be added.

### Isolating the problem:
- [x] This bug happens with no other plugins activated
- [x] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently using the steps above

### WordPress version:
5.5 and 5.4.2

**Comment by richtabor** [comment]
@adriantoll I'm not able to replicate this any longer. Are you?

**Comment by adriantoll** [comment]
@richtabor Nope, this seems to be fixed now.
