### ISSUE TITLE
ISBAT Design of Media Card Block broken in IE11

### ISSUE THREAD

**Issue by nielslange** [godaddy-wordpress/coblocks#1714]
### Describe the bug:

The design of the media card block is broken in IE11. 

### To reproduce:

1. Go to a page or post
2. Add the media card block
3. Save and look up the page or post in IE11

### Expected behavior:

The media card blocks looks like in other browsers such as Edge, Chrome, etc.

### Screenshots:

![](https://user-images.githubusercontent.com/3323310/95008935-17b3bf80-0648-11eb-9ea8-84bf7b5acc1a.jpg)

### Isolating the problem:

- [x] This bug happens with no other plugins activated
- [x] This bug happens with a default WordPress theme active
- [ ] This bug happens **without** the Gutenberg plugin active
- [x] I can reproduce this bug consistently using the steps above

### WordPress version:

WordPress 5.5.1

### Gutenberg version:

Gutenberg 9.0.0

**Comment by jlemay-godaddy** [comment]
Closing this as WordPress is phasing out support for IE 11 : https://make.wordpress.org/core/2021/04/22/ie-11-support-phase-out-plan/
