### ISSUE TITLE
ISBAT use rich text options on gallery images captions

### ISSUE THREAD

**Issue by WunderBart** [godaddy-wordpress/coblocks#1717]
### Describe the bug:
When clicking the image caption, the rich text options toolbar is visible only until the mouse button is released. 

### To reproduce:
1. Add an Offset Block and add images
2. Toggle captions on
3. Click on the caption of any image to edit it.
4. Notice the toolbar above the caption blinks and disappears
5. Changing tabs bring the menu bar back, but clicking on it makes it disappear again

### Expected behavior:
The toolbar stays visible 

### Screenshots:
![Oct-06-2020 11-44-01](https://user-images.githubusercontent.com/1451471/95185655-46a56f00-07c9-11eb-9649-42e7b0832a19.gif)

### Isolating the problem:
- [x] This bug happens with no other plugins activated
- [x] This bug happens with a default WordPress theme active
- [x] This bug happens **without** the Gutenberg plugin active
- [x] I can reproduce this bug consistently using the steps above

### WordPress version:
Testes with 5.5.1 and 5.6-alpha-48683-src

### Gutenberg version:
Tested with 9.0.0 and 9.1.0

**Comment by hacchism** [comment]
Reported in #26808689-hc

The same issue happens in Masonry Block as well.
