### ISSUE TITLE
Embedded videos do not appear inside Accordion Block 

### ISSUE THREAD

**Issue by lakellie** [godaddy-wordpress/coblocks#1734]
### Describe the bug:

In certain circumstances, embedded videos do not appear inside the Accordion Block. This does not seem to happen on every theme, but is happening on Twenty Twenty and Venture, at least. 

When it happens, it looks like the iframe for the video is being set to 0 x 0 on the page for some reason. And as soon as you open the browser inspector, the video appears.

This is happening when videos are added using the embed block. It happened with videos from Vimeo and VideoPress.

### To reproduce:

1. Add an accordion block to a page or post on a site using the Twenty Twenty theme
2. Set the accordion to be closed by default
3. Add an embed block inside the accordion (you can test with any video from Vimeo)
4. Load the page and open the accordion
5. The space where the video should be is blank.

### Isolating the problem:

- [x] This bug happens with no other plugins activated
- [x] This bug happens with a default WordPress theme active
- [x] This bug happens **without** the Gutenberg plugin active
- [x] I can reproduce this bug consistently using the steps above

### WordPress version:
5.5.1

**Comment by snovosel** [comment]
This is an issue with the twentytwenty theme. @lakellie you might want to submit an issue to the theme repository here: https://github.com/WordPress/twentytwenty . I'm going to close this issue since it is happening within this repository.
