### ISSUE TITLE
ISBAT CoBlocks Gallery lightbox does not pass WAVE check for website accessibility.

### ISSUE THREAD

**Issue by gdandrija** [godaddy-wordpress/coblocks#1743]
### Describe the bug:
The lightbox feature of CoBlocks Gallery blocks trows accessibility compliance errors when tested using the WAVE tool

### To reproduce:

1. Create a CoBlocks Gallery(use any Gallery block)
2. Check the Lightbox enable option
3. Save changes
4. Test the website using the https://wave.webaim.org/ tool
5. Open the lightbox and you will see the errors thrown
-->

### Expected behavior:
CoBlocks Lightbox should follow all accessibility rules

### Screenshots:
User's website: https://i.imgur.com/uIEHXC6.png
Test website: https://i.imgur.com/N7u5fkE.png

### Isolating the problem:

- [x ] This bug happens with no other plugins activated
- [x ] This bug happens with a default WordPress theme active
- [x ] This bug happens **without** the Gutenberg plugin active
- [x ] I can reproduce this bug consistently using the steps above

### WordPress version:
5.5.3

### Gutenberg version:
/

The issue was initially reported on WordPress.org: https://wordpress.org/support/topic/accessibility-lightbox-has-no-button-labels/#post-13601266

**Comment by richtabor** [comment]
Closed by #1779
