### ISSUE TITLE
ISBAT Author Block: hide button if empty

### ISSUE THREAD

**Issue by eduardozulian** [godaddy-wordpress/coblocks#1750]
### Is your feature request related to a problem? Please describe.
When using CoBlocks, the `Author Link` button is still visible even if you never added a text to it. 

### Describe the solution you'd like
If no text is present, let's hide the empty `wp-block-button__link`. Screenshot:

<img width="627" alt="Captura de Tela 2020-11-11 às 12 34 21" src="https://user-images.githubusercontent.com/1136160/98831477-61977e80-241a-11eb-8726-7c47addb75d2.png">

### Describe alternatives you've considered
Using CSS to hide that button

### Additional context/screenshots
This happens with or without Gutenberg.

**Comment by richtabor** [comment]
This is actually an issue with the core/button block (https://github.com/WordPress/gutenberg/issues/17221). There's a PR I started there that needs another look before it gets in, but we're working that. Thanks for the detailed report; super helpful!
