### ISSUE TITLE
Masonry/Gallery add support to select image size

### ISSUE THREAD

**Issue by despecial** [godaddy-wordpress/coblocks#1756]
The masonry block uses way too big images.
Example: column is a maximum of 400px and the photo itself is 1200px wide
My theme has a gallery image size which fits perfectly

A hook or even better an option to select which images are used would be great

**Comment by AnthonyLedesma** [comment]
Thank you for contributing. I am closing this issue and linking back to a primary issue regarding refactoring of the Masonry gallery block where we plan to address this ask.
https://github.com/godaddy-wordpress/coblocks/issues/2078
