### ISSUE TITLE
'Add accordion item' creates 2 accordion items instead of one

### ISSUE THREAD

**Issue by davidLpt** [godaddy-wordpress/coblocks#1768]
Hi, when you click in the 'Add content' field of an accordion item and then click on 'Add accordion Item' button right after, it creates 2 new accordion item blocks instead of one.

**Comment by richtabor** [comment]
I was able to repeat this behavior, but it was only happening if I had more than one accordion item added. Here's a screen recording: 
![ScreenFlow](https://user-images.githubusercontent.com/1813435/103812922-40739880-502d-11eb-82bb-073d9c28fa00.gif)

**Comment by olafleur** [comment]
@AnthonyLedesma I think that issue can be closed. :)
