### ISSUE TITLE
Unable to remove button from author block

### ISSUE THREAD

**Issue by bradley2083** [godaddy-wordpress/coblocks#1797]
If you add an "Author" block, you're unable to remove the button. 

<img width="520" alt="Screen Shot 2021-01-19 at 11 22 33 AM" src="https://user-images.githubusercontent.com/1781226/105076809-6bec7f00-5a40-11eb-807d-f319ff9abaf8.png">

**Comment by richtabor** [comment]
Thanks for reporting this Bradley, we'll look into it.

**Comment by richtabor** [comment]
This actually is related to https://github.com/WordPress/gutenberg/issues/17221. I do think we should open up the Author block so its possible to remove the Author block from the editor as well though; I'll write up a story to tweak that.
