### ISSUE TITLE
Gist Block: Console error message

### ISSUE THREAD

**Issue by kishanjasani** [godaddy-wordpress/coblocks#1801]
### Describe the bug:
Add the Gist Block to page or post and It will produce an error in the console when you will try to add some random text rather than adding GitHub URL.

### To reproduce:
1. Go to 'Gist block'
2. Click on 'Textbox provided by gist block'
3. Now try to add some random text in that
4. See error in browser console

### Expected behavior:
The error should not be there.

### Screenshots:
![Screenshot from 2021-01-21 16-33-38](https://user-images.githubusercontent.com/25550562/105343760-0e0a9380-5c08-11eb-9abf-ed231739e324.png)

### Isolating the problem:

- [x] This bug happens with no other plugins activated
- [x] This bug happens with a default WordPress theme active
- [x] This bug happens **without** the Gutenberg plugin active
- [x] I can reproduce this bug consistently using the steps above

### WordPress version:
Latest 5.6

**Comment by AnthonyLedesma** [comment]
Good catch here @kishanjasani. This PR looks good. These propTypes should really be defined across CoBlocks. At this time we are missing definitions for a majority of components. I have created a new issue to track this need. https://github.com/godaddy-wordpress/coblocks/issues/1809

**Comment by kishanjasani** [comment]
Thanks, @AnthonyLedesma. Would like to have a look at that issue. :)
