### ISSUE TITLE
ISBAT use Additional CSS classes without block validation error

### ISSUE THREAD

**Issue by AnthonyLedesma** [godaddy-wordpress/coblocks#1806]
### Describe the bug:

Features block will error when using specific CSS classes when set with certain settings.

### To reproduce:

1. Add Features block and set Features block for wide alignment.
2. Open block sidebar for Features block and open advanced panel.
3. Type in `alignwide` as class name and publish the page.
4. Reload page to see block validation error.

Note that if we put in an alternate class like `test` the block validation errors will not occur. Seems to be related to the parsing of alignment classes. 

### Expected behavior:

Expect block to properly parse additional CSS classes without block validation errors.
Likely if a class name is going to be duplicated, the best approach would be to filter down to a single instance. 

### Screenshots:

**Bug exists for Features block**
![featuresBlockClassValidation](https://user-images.githubusercontent.com/30462574/106009061-30236c00-6075-11eb-971b-ed829a8f70a4.gif)

**Bug does not exist for Hero block**
![heroBlockClassValidation](https://user-images.githubusercontent.com/30462574/106009227-577a3900-6075-11eb-858b-678de83d6835.gif)

### Isolating the problem:

- [x] This bug happens with no other plugins activated
- [x] This bug happens with a default WordPress theme active
- [x] This bug happens **without** the Gutenberg plugin active
- [x] I can reproduce this bug consistently using the steps above

### WordPress version:

5.6

### Gutenberg version:

Still occurs without GB as well as running 9.8.1.

**Comment by richtabor** [comment]
Im not able to replicate this currently, @AnthonyLedesma do you mind double-checking this still exists?

**Comment by richtabor** [comment]
I could not verify this still exists; closing for now.
