### ISSUE TITLE
ISBAT have a single Services block column

### ISSUE THREAD

**Issue by AnthonyLedesma** [godaddy-wordpress/coblocks#1812]
### Describe the bug:

CoBlocks Services block allows the user to alter the block layout to have a single column up to four columns. 

I should be able to set a single column in any theme and have the style accurately reflect on the front-end.

### To reproduce:

**To see correct appearance: Ensure that Go theme is active.**
1. Add services block and switch to 1 column.
2. View the visual appearance of the Services block.

**To see the error: Ensure that TwentyTwenty or TwentyTwenty-One**
1. Add services block and switch to 1 column.
2. View the visual appearance of the Services block.

### Expected behavior:

Expect Services block to render properly with a single column regardless of active theme.

### Screenshots:

**One column in Go**
![image](https://user-images.githubusercontent.com/30462574/106621304-a91c3b00-652f-11eb-89e5-fbdc2ee73198.png)
**One column in Twenty Twenty**
![image](https://user-images.githubusercontent.com/30462574/106621357-b9ccb100-652f-11eb-9679-83cc9897926c.png)

### Isolating the problem:

- [x] This bug happens with no other plugins activated
- [x] This bug happens with a default WordPress theme active
- [x] This bug happens **without** the Gutenberg plugin active
- [x] I can reproduce this bug consistently using the steps above

### WordPress version:

5.6

### Gutenberg version:

N/A

**Comment by richtabor** [comment]
Columns === service item count. It should be that if you choose 1 column, you only have one service item display. We should probably consider changing the "Columns" label to "Count" or Items".
