### ISSUE TITLE
ISBAT Masonry Block: Rendering issue on desktop with AMP Standard mode

### ISSUE THREAD

**Issue by devNigel** [godaddy-wordpress/coblocks#1819]
### Steps to reproduce the behavior

1. Go to AMP settings and Template mode is set to `Standard`.
2. Create a post or a page and add the Masonry block.
3. You will notice that the block rendering on live page is not as expected.

The workaround is to change AMP Template mode or disable AMP for the page or post.

#### What I expected to happen

AMP settings shouldn't affect the desktop view of Masonry block.

![](https://cdn-std.droplr.net/files/acc_1121510/egVYvC)

#### What actually happened

Masonry block is affected by AMP settings in desktop view.

![](https://cdn-std.droplr.net/files/acc_1121510/fAplms)

### Isolating the problem:

- [x] This bug happens with no other plugins activated
- [x] This bug happens with a default WordPress theme active
- [x] This bug happens **without** the Gutenberg plugin active
- [x] I can reproduce this bug consistently using the steps above

### WordPress version:
5.6.1

### Gutenberg version:
NA

**Comment by richtabor** [comment]
Well Masonry is JS driven, which AMP disables on the front-end, right?

**Comment by devNigel** [comment]
@richtabor I see. Thanks for taking a look. I was not aware of that. I guess this ticket can be closed if this is expected behavior.
