### ISSUE TITLE
ISBAT Plugin version 2.8.0 triggers Fatal Error on WP prior to version 5.6

### ISSUE THREAD

**Issue by mvlaisavljevic** [godaddy-wordpress/coblocks#1827]
### Describe the bug:
The latest version 2.8.0 causes fatal on sites that are powered by WP prior to version 5.6
### To reproduce:

1. Ensure the WP version is < 5.6
2. Update CoBlocks to the latest 2.8.0 version, activate the plugin if inactive
3. The fatal error will be displayed on the FOS

### Expected behavior:
The version 2.8.0 to work properly on WP < 5.6
### Screenshots:
<img width="407" alt="Screenshot_9" src="https://user-images.githubusercontent.com/77397765/108062290-e1586900-7059-11eb-81cf-e7213b9f9fb7.png">

### Isolating the problem:

- [x] This bug happens with no other plugins activated
- [x] This bug happens with a default WordPress theme active
- [x] This bug happens **without** the Gutenberg plugin active
- [x] I can reproduce this bug consistently using the steps above

### WordPress version:
5.2 ... 5.5.3

### Gutenberg version:
N/A

**Comment by jonathanbardo** [comment]
Thanks for reporting, we are working on a patch.
