### ISSUE TITLE
Masonry Block: More Sizes / Columns

### ISSUE THREAD

**Issue by matthiasballreich** [godaddy-wordpress/coblocks#1889]
I think it would be cool to have some more size options on the masonry gallery block. At the moment i can only switch between the two sizes L and XL which creates a grin with 3 (L) or 2 (XL) columns. For my usage i want the ability to create 3 to 6 columns.

Maybe i can do it with a workaround, when modify the plugin by myself but i think it would be much better to give the user some more options for reating the block.

**Comment by richtabor** [comment]
The size availability depends on the alignment width setting of the Masonry block. If set to Wide or Fullwidth, there are more options, as the images can be smaller with more vertical columns.
