### ISSUE TITLE
ISBAT • Some style issues both in editor and front-end

### ISSUE THREAD

**Issue by Wewill** [godaddy-wordpress/coblocks#1902]
Hi team, 

— When adding a background color to accordion, the padding is larger in back-end :  

<img width="851" alt="Capture d’écran 2021-05-06 à 16 51 20" src="https://user-images.githubusercontent.com/3178443/117319768-e7f1c200-ae8b-11eb-84ee-aef1b8a46440.png">

— There are no caret for accordions in back-end as in front-end 

<img width="851" alt="Capture d’écran 2021-05-06 à 16 51 20" src="https://user-images.githubusercontent.com/3178443/117319882-035ccd00-ae8c-11eb-8fb9-a0e44327e871.png">
<img width="866" alt="Capture d’écran 2021-05-06 à 16 51 26" src="https://user-images.githubusercontent.com/3178443/117319886-03f56380-ae8c-11eb-954b-c43bfc7f0e77.png">

— Text colors fails on Hero block on editor and front-end 

<img width="1680" alt="Capture d’écran 2021-05-06 à 16 50 51" src="https://user-images.githubusercontent.com/3178443/117319979-196a8d80-ae8c-11eb-8a88-856d49353597.png">

— Text colors fails on citation block both on editor and front-end 

<img width="1327" alt="Capture d’écran 2021-05-06 à 16 49 40" src="https://user-images.githubusercontent.com/3178443/117320072-2dae8a80-ae8c-11eb-9c42-27dc40beba77.png">

— Alignement fails on "couplet" block only on editor 

<img width="704" alt="Capture d’écran 2021-05-06 à 16 49 16" src="https://user-images.githubusercontent.com/3178443/117320193-461ea500-ae8c-11eb-9315-c2fe5ef40afc.png">

— Large padding not showing on editor instead, good on front-end  

<img width="1676" alt="Capture d’écran 2021-05-06 à 16 48 48" src="https://user-images.githubusercontent.com/3178443/117320251-559dee00-ae8c-11eb-80c3-d00a9896c125.png">

Best regards !

**Comment by ehamwey** [comment]
This issue seems to have ties to both Go and CoBlocks, so the relevant PR's are listed above.

**Comment by ehamwey** [comment]
@Wewill can you provide more details on the text color issue on the Hero block, and the padding issue on Pullquote? I am unable to replicate those behaviors on my instance of Go + CoBlocks on WP 5.7.2. 

We should have draft PRs up for the other issues you mentioned, with the exception of the accordion carets behavior for the moment.

**Comment by Wewill** [comment]
@ehamwey thank you for your feedback. 
I've just tested with Go 1.4.4 + CoBlocks 2.11.2 + WP 5.7.2

You'll find attached gif which describes issues : 

- Hero

If no color as been chosen for the Hero title, the hero text color should apply. 

![Hero](https://user-images.githubusercontent.com/3178443/119828785-ce77ef00-befa-11eb-97a7-718cedd32a1f.gif)

- Citation

Same text color issue 

![Citation](https://user-images.githubusercontent.com/3178443/119828799-d2a40c80-befa-11eb-9cc5-8c3b8cec0f4c.gif)

- Couplet

Alignements issue appears only in editor

![Couplet](https://user-images.githubusercontent.com/3178443/119828802-d33ca300-befa-11eb-945a-bef6a2cf873c.gif)

- Exergue 

Padding ≠ between back-end and front-end. 

![Exergue](https://user-images.githubusercontent.com/3178443/119828805-d3d53980-befa-11eb-9734-c21d94aa4230.gif)

**Comment by Wewill** [comment]
Hi @ehamwey, great ! Thank you. 
For the Hero issue, yes, it will work but not really intuitive ; the better way would be : if I choose a color in a individual text field inside the Hero, it will override the chosen text color of hero. If not, the Hero chosen text chosen will work. 
Because, if you have many text fields inside your Hero and you don't want to change all the text fields text color ; it's better. 

And, also, it looks like a bug because as you noticed, it works for the text field block, not for the heading block when you choose the secondary, and tertiary bg color. But primary bg color fails all the text colors. 

Hope it helps !

**Comment by ehamwey** [comment]
Hi @Wewill - I've created separate issues for the remaining tasks outlined here: https://github.com/godaddy-wordpress/coblocks/issues/1914 and https://github.com/godaddy-wordpress/go/issues/677

Going to close this issue as the new reports have a bit more detail and target the specific product causing the problem. 

Thanks for your help tracking these down!
