### ISSUE TITLE
ISNBAT set colors on Pullquote when using the Default style

### ISSUE THREAD

**Issue by ehamwey** [godaddy-wordpress/coblocks#1913]
### Describe the bug:
Pullquote block still shows color selectors on the Default style, but they are non-functional. These should be hidden or fixed when using the Default style.

### To reproduce:
1. Insert a Pullquote block
2. Ensure the Default style is set
3. Attempt to change any color with any selection

### Expected behavior:
Color is changed of the selected element or the Color settings panel in the Inspector is hidden when using the Default style.

### Screenshots:
![Untitled](https://user-images.githubusercontent.com/9936886/120678316-f8cf2c80-c465-11eb-97b9-52512d2d5ee9.gif)

### Isolating the problem:
- [x] This bug happens with no other plugins activated
- [x] This bug happens with a default WordPress theme active
- [x] This bug happens **without** the Gutenberg plugin active
- [x] I can reproduce this bug consistently using the steps above

### WordPress version:
5.7.2

**Comment by snovosel** [comment]
Because this is a core block I will be closing this ticket

**Comment by AnthonyLedesma** [comment]
Good call here @snovosel. I thought that we added those color controls with CoBlocks similar to how we modify the Quote block but that is not the case. These color controls for PullQuite are coming right from core.
