### ISSUE TITLE
ISBAT Accordion Block: CSS overwrites editor color choices

### ISSUE THREAD

**Issue by JessBoctor** [godaddy-wordpress/coblocks#1918]
### Describe the bug:
When a user chooses a color for the accordion summary background in the page or post editor, it is not reflected in the published page.

### To reproduce:

1. Go to 'Pages'
2. Click on 'Add New'
3. Add an Accordion block to the page. Give the block a title and some content.
4. In the block options in the right-hand menu, choose a background color for the block
5. Publish the page
6. The plugin CSS will override the block, making the summary background `rgba(140,140,151,0.1)`

### Expected behavior:
The color selected in the editor should be seen on the published page.

### Screenshots:
Here is a video of the steps to create the issue: https://d.pr/v/hAzvu5

Image of the results: https://d.pr/i/BWS9HV

Image of the CSS code overriding the editor selection: https://d.pr/i/hapQ2b

### Isolating the problem:
This looks to be an issue with this CSS snippet: 

`.wp-block-coblocks-accordion-item__title, .wp-block-coblocks-accordion-item__title.has-background {
    background: rgba(140,140,151,0.1);
    border-radius: 4px;
    padding: 10px 15px;
    position: relative;
}`

- [x] This bug happens with no other plugins activated
- [x] This bug happens with a default WordPress theme active
- [x] This bug happens **without** the Gutenberg plugin active
- [x] I can reproduce this bug consistently using the steps above

### WordPress version:
5.7.2 

### Gutenberg version:
10.7.4

**Comment by jordesign** [comment]
+1 I've run into this same issue. Feel free to use this test site as an example.
https://woo.jordanpremium.blog/testing-coblocks-accordion/

First block has no custom color - second block has custom color applied.

**Comment by ehamwey** [comment]
Hi all, we will be pushing a patch release today that resolves this. Thanks for letting us know!

**Comment by ehamwey** [comment]
CoBlocks 2.12.1 has been released which should resolve this. Let us know if you have further issues! Thanks!
