### ISSUE TITLE
Pricing Table: ISBAT Add Other Blocks Inside the Pricing Table Block

### ISSUE THREAD

**Issue by donalirl** [godaddy-wordpress/coblocks#1919]
### Is your feature request related to a problem? Please describe.
At the moment, the Pricing Table block's Buy Now buttons can only be linked to another page. It's not possible to add another block inside that block, such as [this Payments block](https://wordpress.com/support/wordpress-editor/blocks/payments/)

### Describe the solution you'd like
If we could insert a Payments block into the Pricing Table block, a website visitor can make the payment right there on the page, instead of being taken to another page to make the payment. Fewer clicks = an easier path to purchase.

Other blocks that could be inserted into the Pricing Table include Image, List, Heading, and more, to allow more customization of the Pricing Table.

### Describe alternatives you've considered
The alternative at the moment is to link the Buy Now button to a separate page, which is not ideal.

**Comment by AnthonyLedesma** [comment]
@donalirl Thank you for this suggestion. Our next release will feature Pricing Table blocks that allow users to add other inner blocks like the payments block.
