### ISSUE TITLE
Fix broken Youtube video link

### ISSUE THREAD

**Issue by ms-studio** [godaddy-wordpress/coblocks#1921]
### Describe the bug:

The readme.txt of this plugin contains a link to a Youtube video – https://www.youtube.com/watch?v=SfWoVX_uJ0M – which is unavailable ("the uploader has closed their YouTube account."). This is displayed on the plugin description page at https://wordpress.org/plugins/coblocks/

### To reproduce:

1. Visit https://wordpress.org/plugins/coblocks/
2. Try to play the video.

### Expected behavior:

Link should be replaced by a video that works, or simply removed.

**Comment by AnthonyLedesma** [comment]
This issue is closed now but the WordPress.org plugins page for CoBlocks will not be updated until the next CoBlocks release scheduled on Jun 21st.

**Comment by AnthonyLedesma** [comment]
Thank you for bringing this issue to our attention @ms-studio.
