### ISSUE TITLE
Cover Block styles overlap text.

### ISSUE THREAD

**Issue by KirkwallDay** [godaddy-wordpress/coblocks#1924]
Hi, I'm a Happiness Engineer at WordPress.com and found this bug and wanted to bring it to your attention. We also had a similar report of the same bug here: https://github.com/WordPress/gutenberg/issues/25866 on our repo.

### Describe the bug:
When applying a style to the Cover Block like "Waves top" or "Waves bottom" the style will overlap any content on top of the cover block.

### Expected behavior:

I expect the content to show up on top of the style of the block.

### Screenshots:

<img width="1135" alt="Screen Shot on 2021-06-21 at 08-20-21" src="https://user-images.githubusercontent.com/49131029/122777782-9b125100-d269-11eb-9696-7f1d538e7dc9.png">

### Isolating the problem:

- [X] This bug happens with no other plugins activated
- [X] This bug happens with a default WordPress theme active
- [X] This bug happens **without** the Gutenberg plugin active
- [X] I can reproduce this bug consistently using the steps above

### WordPress version:

5.7.2

### Gutenberg version:

10.8.2

**Comment by snovosel-godaddy** [comment]
@KirkwallDay closing this ticket as there is no straightforward way to accommodate for this. A new block may be a better solution
