### ISSUE TITLE
ISBAT use Share blocks in FSE mode

### ISSUE THREAD

**Issue by AnthonyLedesma** [godaddy-wordpress/coblocks#1944]
### Describe the bug:

Using the experimental Full Site Editor mode with Share block in the Header or Footer can result in links with an improper permalink.

### To reproduce:

I used the TT1Blocks theme to reproduce this issue. This might occur with other FSE themes.

Go into the Full Site Editor
![image](https://user-images.githubusercontent.com/30462574/126514530-e4ea982d-7191-4f03-8300-80cdc927aa9b.png)

Add Share block to the footer or header to see this issue.

### Screenshots:

The expected permalink should match current page/uri
![image](https://user-images.githubusercontent.com/30462574/126514088-e44312cb-d601-4a9d-8c0f-7c7bdf8e6465.png)

Here is the actual permalink
![image](https://user-images.githubusercontent.com/30462574/126514229-ae3e60c2-1df2-4c66-8246-d413116ea59a.png)

### Isolating the problem:

- [ ] This bug happens with no other plugins activated
- [ ] This bug happens with a default WordPress theme active
- [ ] This bug happens **without** the Gutenberg plugin active
- [x] I can reproduce this bug consistently using the steps above

### WordPress version:

5.8

### Gutenberg version:

11.1.0

**Comment by AnthonyLedesma** [comment]
I found this while testing https://github.com/godaddy-wordpress/coblocks/pull/1939

**Comment by AnthonyLedesma** [comment]
This also effects Form block.

![image](https://user-images.githubusercontent.com/30462574/130676745-04c11fb3-b628-47b1-852d-8e62c60bb52a.png)

**Comment by olafleur-godaddy** [comment]
Closing as @jrtashjian said he would deprecate the block for the core one.
