### ISSUE TITLE
ISBAT not have the FROM field of the form block automatically changed to the submitter email to prevent deliverability issues

### ISSUE THREAD

**Issue by kdevnel** [godaddy-wordpress/coblocks#1969]
### Is your feature request related to a problem? Please describe.

I should be able to change the behaviour of rewriting the "FROM" header or the form should not set the from header to the submitted user's email address.

The issue with forcing the from header to be the submitter email is that it can caus deliverability issues. If a user from xyz@gmail.com tries to submit a form and the form sends this to abc@gmail.com this would likely get flagged by GMail among many other mail providers as spam since it recognises that the form was not sent by a GMail server even though the from address indicates it is.

The only solution to this is to make changes to the mail sending on the server manually, with custom code or with another plugin.

### Describe the solution you'd like

The above setup may be desirable in some situations but ideally shouldn't be the default behaviour. To improve deliverability out-of-the-box it would make sense to keep the from email as the default provided in the `wp_mail()` function since this is likely to be managed by the site, server or a plugin already.

### Describe alternatives you've considered

An alternative might be to set the reply-to field only so that the email still comes from the default site email address but then replies will be sent to the submitter email address.

Another option is to make the from field configurable somehow.

The only other option is to override this behaviour with a plugin that sets the from field _after_ CoBlocks changes this field.

### Additional context/screenshots

![Markup on 2021-07-28 at 08:27:52](https://user-images.githubusercontent.com/22053773/127274525-012c7164-7f1a-45d9-9474-a9d5d8beceb9.png)

![Markup on 2021-07-28 at 08:27:08](https://user-images.githubusercontent.com/22053773/127274541-2879260d-a81d-400e-9c0a-5e189b3d8cd1.png)

**Comment by AnthonyLedesma** [comment]
Related to https://github.com/godaddy-wordpress/coblocks/pull/1840
