### ISSUE TITLE
ISBAT Add more than 4-5 images to Collage Block

### ISSUE THREAD

**Issue by gdandrija** [godaddy-wordpress/coblocks#1975]
### Is your feature request related to a problem? Please describe.
There is no way to add more than 4-5 images to a Collage Block

### Describe the solution you'd like
An option that will allow me to choose the number of images that will be part of a collage block

### Describe alternatives you've considered
None

### Additional context/screenshots
Adding more collage blocks is not best for the appearance, a user should be able to add as many images as possible without performance issues

Screenshot for context: https://i.imgur.com/a7lJEE5.png

Initially submitted on WordPress.org
https://wordpress.org/support/topic/add-more-images-to-collage/

**Comment by richtabor** [comment]
Hey @gdandrija, I think that's an interesting idea, but not quite the spirit of the block. I think we'd need some complex styling to push it further, which would make the block quite heavy in my option.

I'd suggest simply using a combination of the Collage block, Image and Gallery blocks to achieve that.
