### ISSUE TITLE
Food Menu Block - icon getting accessibility error in Google Lighthouse

### ISSUE THREAD

**Issue by boopathirbk** [godaddy-wordpress/coblocks#2001]
###Bug
In Food menu block there are icons such as popular, spicy etc., when added into menu and published and when I ran google lighthouse I got this Accessibility Error.
----- Comes as follow -----
[aria-*] attributes do not match their roles
Each ARIA `role` supports a specific subset of `aria-*` attributes. Mismatching these invalidates the `aria-*` attributes.
<span class="wp-block-coblocks-food-item__attribute wp-block-coblocks-food-item__attrib…" aria-label="Popular">
------- ends -------------

### Expected behavior:

Google Lighthouse shows aria attributes are misconfigured 

### Screenshots:

![Screenshot 2021-08-21 at 5 35 56 PM](https://user-images.githubusercontent.com/22997723/130321192-0da7a38f-12b6-41f7-8b00-f9e3cd10743e.png)

### WordPress version:

Wordpress 5.8

**Comment by jasonlemay** [comment]
Looks like `role="img"` is missing.

**Comment by snovosel** [comment]
This was addressed in - https://github.com/godaddy-wordpress/coblocks/pull/2021
