### ISSUE TITLE
Services Block: Allow previously inserted media to be replaced

### ISSUE THREAD

**Issue by inaikem** [godaddy-wordpress/coblocks#2004]
### Is your feature request related to a problem? Please describe.
I should be able to replace an image previously added to the Services Block. Example:

- Add a Services Block to a post or page.
- Insert the image, heading, and text.
- It is not possible to _replace_ the inserted image.
- To replace the image you need to add the block again, choose the new image, and copy and paste the heading and text.

### Describe the solution you'd like
Request to add a "Replace" or similar link/button link to the block toolbar, or to the settings panel where it currently has the option to change the image focal point, etc. 

This would be similar to the replace image option in the Gutenberg Cover Block, or the WordPress Featured Image option for a page or post.

Screenshot of current block settings:

<img width="995" alt="Markup 2021-08-14 at 11 35 08" src="https://user-images.githubusercontent.com/66711744/130547353-3fec6947-ec67-43fd-8e4d-bfd37f5fb17e.png">

**Comment by richtabor** [comment]
That's interesting you're not seeing the "X" we have added once the image is selected. We'll look into it. 

What version of WordPress/Gutenberg are you running? 

<img width="668" alt="Screen Shot 2021-08-25 at 11 39 03 AM" src="https://user-images.githubusercontent.com/1813435/130821296-9c4db03d-a29f-49b9-bfe3-812b5c2ae5d2.png">

**Comment by inaikem** [comment]
Thanks for checking in, Rich 👋  WP 5.8, Gutenberg 11.3 and CoBlocks 2.16. While I was confirming the details for you I revisited my test for the initial report. The "X" button is now visible, so I'm going to go ahead and close this issue for the moment. I'll reopen it if it occurs again.
