### ISSUE TITLE
Black and white is not working properly in the Logos block

### ISSUE THREAD

**Issue by olafleur** [godaddy-wordpress/coblocks#2023]
When putting images like these one in the Logos block : 

<img width="782" alt="Capture d’écran, le 2021-09-10 à 15 33 31" src="https://user-images.githubusercontent.com/1068290/133189119-e03dd7ad-00eb-4d0a-830b-d7d54bd46490.png">

And selecting Black and white, this is the result : 

<img width="782" alt="Capture d’écran, le 2021-09-10 à 15 33 41" src="https://user-images.githubusercontent.com/1068290/133189133-cfe7adf2-e838-4037-93e0-8884a1790e64.png">

The expected result would be to have a black and white image ;)

**Comment by olafleur-godaddy** [comment]
Closing as my understanding of what should happen was wrong.
