### ISSUE TITLE
ISBAT use the Map block with React hooks

### ISSUE THREAD

**Issue by AnthonyLedesma** [godaddy-wordpress/coblocks#2033]
### Describe the bug:

Recent [refactor of Map block to React hooks](https://github.com/godaddy-wordpress/coblocks/pull/2010) did not cover the case of API key use. Standard block behavior is to use a simple Iframe and source the Google API. The API key method is to use a 3rd party package `react-google-maps` for its Google Maps Implementation. The way in which the component functions is not compatible with React Hooks and only functions in this context within class-based components. Part of the issue has to do with the fact that `react-google-maps` was written using a now legacy version of React and has features that are now deprecated, specifically context.

With the [Performance Metrics PR, the Map block has been reverted back to a Class-based component](https://github.com/godaddy-wordpress/coblocks/pull/2031/commits/aebbc78e21b081edb9260b870b5bb03a0c9615a9). We must investigate what it will take to refactor the Google Maps API key functionality into a state where we have functionality with hooks. I posit that perhaps we should consider looking for an alternate (more up-to-date) or write our own solution to be housed within CoBlocks codebase. 

- [The block should be able to deprecate from the following block markup](https://github.com/godaddy-wordpress/coblocks/issues/1596)
```
<!-- wp:coblocks/map {"address":"Scottsdale Arizona","pinned":true,"height":534,"align":"full"} -->
<div style="min-height:534px" data-map-attr="/qaddress/q:/scottsdale arizona/q||/qlat/q:/qundefined/q||/qlng/q:/qundefined/q||/qskin/q:/qstandard/q||/qzoom/q:/q12/q||/qiconSize/q:/q36/q||/qmapTypeControl/q:/qtrue/q||/qzoomControl/q:/qtrue/q||/qstreetViewControl/q:/qtrue/q||/qfullscreenControl/q:/qtrue/q" class="wp-block-coblocks-map alignfull"><iframe title="Google Map" frameborder="0" style="width:100%;min-height:534px" src="https://www.google.com/maps?q=scottsdale%20arizona&amp;language=ja&amp;output=embed&amp;hl=%s&amp;z=12"></iframe></div>
<!-- /wp:coblocks/map -->
```

- [IS not use jQuery in the Map block refactor](https://github.com/godaddy-wordpress/coblocks/issues/1365)
- [The Map block is affected by specific conditional user permissions that can affect UX. This is a bit of an outstanding issue that also affects the Gist block but it should be resolved for the Map block here.](https://github.com/godaddy-wordpress/coblocks/issues/175) - We might be able to resolve this issuse by using an `oembed` as suggested in the linked thread. We might also need to go more of a SSR route but I am not positve either way. That research is part of the refactors.

**Comment by olafleur-godaddy** [comment]
To replace the recompose library, that is not maintained anymore, a few tips : https://stackoverflow.com/a/55503165
Also, https://www.npmjs.com/package/@react-google-maps/api seems interesting to use.
