### ISSUE TITLE
ISBAT see the correct icon for an event item

### ISSUE THREAD

**Issue by EvanHerman** [godaddy-wordpress/coblocks#2067]
### Describe the bug:
The event item block inside of the events block doesn't have an icon, and contains no preview.

### To reproduce:
Add an events block to a page, click the + at the top left and check the 'event item' block that appears.

### Expected behavior:
An icon should be used for the event item.

### Screenshots:
![image](https://user-images.githubusercontent.com/5321364/136620641-58b119f8-807f-452b-9d4d-b2b459d7eef7.png)

### Isolating the problem:
- [x] This bug happens with no other plugins activated
- [x] This bug happens with a default WordPress theme active
- [x] This bug happens **without** the Gutenberg plugin active
- [x] I can reproduce this bug consistently using the steps above

### WordPress version:
5.8.1

### Gutenberg version:
n/a

**Comment by olafleur** [comment]
Was this fixed by #2054 ?

**Comment by EvanHerman** [comment]
@olafleur It looks like this was resolved at some point. I'm not sure if by 2054 or another PR, but it looks fine now.
![image](https://user-images.githubusercontent.com/5321364/143059765-e150dec6-70ad-4a9c-88f7-8f44b098db94.png)
