### ISSUE TITLE
Wrong url for assets

### ISSUE THREAD

**Issue by jgreys** [godaddy-wordpress/coblocks#2179]
### Describe the bug:
It looks like the URLs for the assets are wrong. It leads to /wp-content/plugins/coblocks/assets/images/ but the folder images doesn't exist.

### To reproduce:

1. Go to create / edit a page
2. Add a map block
3. Set Google Map API key
4. See 404 errors in the developer console

### Expected behavior:
Correct the URLs for the assets.

### Isolating the problem:

- [x] This bug happens with no other plugins activated
- [x] This bug happens with a default WordPress theme active
- [x] This bug happens **without** the Gutenberg plugin active
- [x] I can reproduce this bug consistently using the steps above

### WordPress version:
Latest

### Gutenberg version:
Latest

**Comment by olafleur-godaddy** [comment]
Thanks a lot for the issue!
I've opened up a PR that should fix your issue, if you want to take a look and test if that solves your problem.

**Comment by jgreys** [comment]
@olafleur-godaddy Thanks! PR fixed the issue.
