### ISSUE TITLE
ISBAT add custom icons

### ISSUE THREAD

**Issue by zitrusblau** [godaddy-wordpress/coblocks#2251]
### Describe the bug:
As from your docs, I should be able to add custom icons and place them in the active theme directory. Unfortunately, this is currently not possible w/ most recent versions tested.
https://github.com/godaddy-wordpress/coblocks/blob/master/docs/hooks/icons-block.md

### To reproduce:
Add a custom .svg file (use the example code from the doc) as shown in the doc and add an icon block. The block won't load. Error in JS console:
`315.js:2099 Uncaught (in promise) TypeError: coblocksBlockData.customIcons[o].icon.replace is not a function
    at 315.js:2099:403
    at Array.forEach (<anonymous>)
    at Module.2315 (315.js:2099:336)
    at Function.o (coblocks-8.js?ver=b8d345148b22c477c69a5ff231703701:3072:57480)
    at async coblocks-8.js?ver=b8d345148b22c477c69a5ff231703701:1:211933`

Tried to add different icons ony by one but the example SVG code from your doc should do it I guess. The error above hints to an issue unrelated to the SVG format/code provided.

### Expected behavior:
Load the block and show the icon within it.

### Isolating the problem:
- [x] This bug happens with no other plugins activated
- [x] This bug happens with a default WordPress theme active (twenty twenty one)
- [x] This bug happens **without** the Gutenberg plugin active
- [x] I can reproduce this bug consistently using the steps above

### WordPress version:
WP 5.9 (also happens on 5.8.3)

Hope you can take a look at this. Thanks!

**Comment by AnthonyLedesma** [comment]
Closed with #2256

**Comment by zitrusblau** [comment]
Okay thanks!
Now the JS errors are gone but no SVG Markup is added in the frontend unfortunately when selecting custom icons.
I also tested with your SVG example code again.

**Comment by jlemay-godaddy** [comment]
I can confirm that it's still broken. The icon will display in the editor, but not in the frontend.

**Comment by olafleur-godaddy** [comment]
Fixed in #2282 and deployed in 2.22.0
