### ISSUE TITLE
ISBAT Carousel Dot Navigation not working

### ISSUE THREAD

**Issue by gdandrija** [godaddy-wordpress/coblocks#2361]
### Describe the bug:
When Dot Navigation is toggled, dots show up on slides in the backend but not in the frontend

### To reproduce:

1. Create a Carousel using the Carousel block with at least 4 images in it
2. Toggle Dot Navigation in block settings
3. Click Update to publish changes
4. Silder shows up but without dot navigation

### Expected behavior:
To see dots on slides as in the backend

### Screenshots:
Backend dots: https://i.imgur.com/pgK2WkD.png
No dots on front: https://i.imgur.com/edX5vZt.png

### Isolating the problem:

- [x] This bug happens with no other plugins activated
- [x] This bug happens with a default WordPress theme active
- [x] This bug happens **without** the Gutenberg plugin active
- [x] I can reproduce this bug consistently using the steps above

### WordPress version:
5.9.3

### Gutenberg version:
/

Initially reported on WordPress.org:
https://wordpress.org/support/topic/carousel-dot-navigation-doesnt-seem-to-do-anything/

**Comment by adamf59** [comment]
#2389
