### ISSUE TITLE
ISBAT see the post editor's "update" button in the expected position

### ISSUE THREAD

**Issue by p-jackson** [godaddy-wordpress/coblocks#2400]
### Describe the bug:

The "update" button in the top toolbar appears in the wrong place when CoBlocks is installed.

### To reproduce:

1. Fresh site with no plugins other than CoBlocks v2.24.1 activated
2. Open a post in the post editor
3. Take a look at the top bar in the editor

### Expected behavior:

The triple-dot kebab menu is usually the menu that appears at the right of the toolbar.

### Screenshots:

![CleanShot 2022-06-17 at 17 37 24@2x](https://user-images.githubusercontent.com/1500769/174232637-82578814-6ffb-43e8-9d9b-d628ac49241e.png)

### Isolating the problem:

- [x] This bug happens with no other plugins activated
- [x] This bug happens with a default WordPress theme active **(tested with twenty twenty two)**
- [x] This bug happens **without** the Gutenberg plugin active
- [x] I can reproduce this bug consistently using the steps above

### WordPress version:

v6.0

### Gutenberg version:

Plugin not activated.

**Comment by AnthonyLedesma** [comment]
This issue was reported another time here  https://github.com/godaddy-wordpress/coblocks/issues/2421 where we managed to address it and release a fix in version 2.24.3. Closing as no longer relevant. Thanks for the report @p-jackson.
