### ISSUE TITLE
404 on latest.css.map dependency

### ISSUE THREAD

**Issue by gkiosov** [godaddy-wordpress/coblocks#2436]
### Describe the bug:
The user described the problem on the [plugin support page](https://wordpress.org/support/topic/404-on-latest-css-map-dependency/). I have the same issue.

The file `/includes/Dependencies/GoDaddy/Styles/build/latest.css` contains a string `/*# sourceMappingURL=latest.css.map*/` at the end. If you remove it, then the 404 error in the console disappears. The bundlers (like Webpack or CodeKit — dunno what bundler you using to generate CSS file from CSS preprocessor) usually add this link to the CSS source map in CSS file when generating a CSS file if the “Generate CSS source map“ setting is on. Turn it off or provide the source map file with the latest.css file.

### Isolating the problem:
- [x] This bug happens with no other plugins activated
- [x] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently using the steps above

### WordPress version:
WordPress 6.0.3
CoBlocks 2.24.4

The problem is ancient; it was also present on previous versions of the WordPress and CoBlocks.

**Comment by olafleur-godaddy** [comment]
On which page are you seeing this 404 error in the console? I am unable to reproduce the issue.

**Comment by gkiosov** [comment]
> On which page are you seeing this 404 error in the console? I am unable to reproduce the issue.

On each. But I just checked it in Chrome/Firefox also — see this error only in Safari, which is very strange.
