### ISSUE TITLE
Button background color styling lost on update to v2.25.4

### ISSUE THREAD

**Issue by jp-imagines** [godaddy-wordpress/coblocks#2460]
### Describe the bug:
Appears to be related to https://github.com/godaddy-wordpress/coblocks/pull/2449; first reported in Automattic's repo: https://github.com/Automattic/wp-calypso/issues/71287

On updating to CoBlocks 2.25.4, all buttons lose their default background color (including on hover). Buttons with customized background colors appear unaffected.

### To reproduce:

1. On a site with CoBlocks 2.25.4 **inactive**, add a Buttons block to any post or page. Confirm its appearance (and hover styling) in the editor and on the live post/page or preview.
2. Activate CoBlocks 2.25.4.
3. View the post/page again. (Issue appears in the editor, previews, and live sites.)

### Expected behavior:

Buttons should retain their default styling when no custom colors are set, as determined by the theme settings.

### Screenshots:

Screenshots from Twenty Twenty-Three theme.

With CoBlocks 2.25.4 inactive:
![Screen Capture on 2022-12-18 at 13-22-27](https://user-images.githubusercontent.com/5630717/208313060-41d06c8c-53cf-4d90-9e2a-39787ba95eb4.gif)

With CoBlocks 2.25.4 active:
![Screen Capture on 2022-12-18 at 13-23-29](https://user-images.githubusercontent.com/5630717/208313104-62cf61b0-12cc-4ec5-8693-8b35f026d119.gif)

Browser inspector:
<img width="1726" alt="Markup 2022-12-18 at 13 26 08" src="https://user-images.githubusercontent.com/5630717/208313204-0cf187c8-6521-42b2-a9f5-3c7501cd0375.png">

### Isolating the problem:

- [x] This bug happens with no other plugins activated
- [x] This bug happens with a default WordPress theme active
- [x] This bug happens **without** the Gutenberg plugin active
- [x] I can reproduce this bug consistently using the steps above

### WordPress version:

6.1.1

### Gutenberg version:

N/A

**Comment by WunderBart** [comment]
> Appears to be related to https://github.com/godaddy-wordpress/coblocks/pull/2449;

Confirmed that the bug was introduced in #2449. @EvanHerman, would you be able to take a look at this one? 🙏 /cc @aledesma-godaddy

**Comment by simison** [comment]
Selectors in [button styles](https://github.com/godaddy-wordpress/coblocks/blob/ca3e5be17b11503e1bef82a3ecd44e4e78c9c9fb/src/extensions/button-styles/styles/style.scss) are fairly generic and could easily leak into unwated elements. Worth scoping them with more unique CSS selector.

**Comment by AnthonyLedesma** [comment]
Thank you for the report, everyone. Pushing out release 2.25.5 which resolves the issue.
