### ISSUE TITLE
ISBAT add a working carousel with the WP site editor

### ISSUE THREAD

**Issue by ama542blake** [godaddy-wordpress/coblocks#2494]
### Describe the bug:
When I add a carousel block to my site using the WordPress site editor tool, it is completely broken. I can't even do things like change the size of the images in the carousel (see the attached images). Most importantly, the buttons to navigate through the images are broken. These buttons are broken both from the editor page, as well as when I actually visit the site.

When I add a carousel on a normal page or post, I do not have this issue. Everything works as it should. So it appears that the issue is compatibility with the site editor feature. I understand that this feature is in beta, so perhaps there's an issue there?

### To reproduce:
1. Use any theme that is compatible with the site editor feature (I was able to produce this with Twenty-Twenty Two).
2. Click the "Editor" button in the appearance section of the dashboard.
3. Add a carousel with multiple images.
4. Try to click between images, or change the size of the images- you won't be able to.
5. Save the changes and visit the site, againt trying to navigate through the images- you still won't be able to.

### Expected behavior:
I expect that I should be able to add a carousel block that works as it does on other pages to my site.

### Screenshots:
As you can see here, whether the image size was "S" or "L", the image size did not change.
<img width="1427" alt="Screen Shot 2023-02-13 at 8 19 22 PM" src="https://user-images.githubusercontent.com/32677038/218614351-ef5543b7-18c0-4dcc-bc4e-84c91afed35d.png">
<img width="1434" alt="Screen Shot 2023-02-13 at 8 19 31 PM" src="https://user-images.githubusercontent.com/32677038/218614369-f1a06edb-4857-43b3-9a68-210e9ec1cab1.png">

### Isolating the problem:
- [x] This bug happens with no other plugins activated
- [x] This bug happens with a default WordPress theme active
- [x] This bug happens **without** the Gutenberg plugin active
- [x] I can reproduce this bug consistently using the steps above

### WordPress version:
6.1.1

**Comment by AnthonyLedesma** [comment]
Resolved quite some time ago with #2519
