### ISSUE TITLE
 Invisible blocks when animation is added (Slideshow, Tiled Gallery..)

### ISSUE THREAD

**Issue by mxhassani** [godaddy-wordpress/coblocks#2495]
### Describe the bug:
Adding an animation from Gutenberg to some blocks makes said blocks invisible (but still clickable).

Tested and confirmed with Slideshow, Tiled Gallery

The issue appears to be the class `zoomIn` (or similar) isn't added to the block while the class  `coblocks-animate` is added, which leaves the block with the propriety `opacity: 0;` in:

```
body:not(.amp) .coblocks-animate {
  animation-fill-mode: forwards;
  animation-timing-function: ease-in;
  opacity: 0;
}
```

### To reproduce:

1. Open the Editor
2. Add a Slideshow or Tiled Gallery block
3. Add an animation from the block toolbar
4. Save and check

### Expected behavior:
To see the block after it plays an animation

### WordPress version:
6.1.1 

### Gutenberg version:
15.0.1

### Available workarounds?

Yes, easy to implement

### Workaround details

Add one of the following CSS codes:

**Code 1** - Catch-all but may make some other block animations a bit janky: 
```
/* fix animation bug */
body:not(.amp) .coblocks-animate{
   opacity: 1 !important; 
}
```

**Code 2** - But you'd want to get specific if you want to keep the same type of animation picked by the user:

```
/* fix animation bug */
body:not(.amp) .coblocks-animate{
  animation-duration: .75s;
  animation-name: zoomIn;
}
```

You can replace `zoomIn` with one of the following:

```
fadein
slidein
slidein
spin
spinner__animation
loading__animation
coblocks-ellipsis
fadeIn
zoomIn
slideInLeft
slideInRight
slideInBottom
clipHorizontal
clipVertical
pulse
```

**Comment by EvanHerman** [comment]
@mxhassani Where are those blocks, Slideshow and Tiled Gallery, coming from? I don't believe they are included in CoBlocks, so when I try and add one to a page I can't find it.

When I use the zoom in with the CoBlocks Masonry Gallery, for example, it works fine.

**Comment by mxhassani** [comment]
@EvanHerman Those are Jetpack blocks - I tested on a different host and I am getting similar results as yours. 
This may be hosting related issue. I will take this there and update here if necessary.

Keeping this open for:
> I do see some blocks where the animations don't work

**Comment by EvanHerman** [comment]
PR up at https://github.com/godaddy-wordpress/coblocks/pull/2509 to address the CoBlocks animations not working on non CoBlocks blocks when they are the only blocks on a page. (More details in the PR
