### ISSUE TITLE
Usage of get_current_screen() without checking its availability leaading to potential fatal error

### ISSUE THREAD

**Issue by maximus80** [godaddy-wordpress/coblocks#2515]
### Describe the bug:
Possible fatal error, due to function `get_current_screen()` not always being defined here: https://github.com/godaddy-wordpress/coblocks/blob/master/includes/block-migrate/loader.php#L30

The problem is, that the code automatically assumes that the function is defined, which is not always the case. Only if `screen.php` or `admin.php` is loaded, it will be defined.

Since the code gets executed on `the_post` action, it can happen during any 3rd party plugin request that loops through posts using `the_post()`.

### To reproduce:
Create a custom query from a plugin that uses `the_post()` that runs without `screen.php` or `admin.php` being loaded.

### Expected behavior:

- CoBlocks should not use an anonymous function here, which can't be unhooked easily.
- CoBlocks should checks if `get_current_screen()` is actually defined.
- CoBlocks should makes sure `screen.php` or `admin.php` are included:
`require_once ABSPATH . 'wp-admin/includes/screen.php';`
`require_once ABSPATH . 'wp-admin/admin.php';`
- Additionally, CoBlocks should not access member variable `is_block_editor` without check.

### Isolating the problem:
- [x ] I can reproduce this bug consistently using the steps above

### WordPress version:
6.1.1+

**Comment by AnthonyLedesma** [comment]
@maximus80 Thank you for taking the time to make this issue! We just merged in a fix for the missing dependency in some situations and will be pushing out a patch release.

**Comment by AnthonyLedesma** [comment]
handled with #2514

**Comment by maximus80** [comment]
Glad to hear that, thanks for the quick action :+1:
