### ISSUE TITLE
Conflict with Gutenberg 16.1+ causes copied content text to lose paragraphs

### ISSUE THREAD

**Issue by cuemarie** [godaddy-wordpress/coblocks#2539]
### Describe the bug:
I should be able to copy text from a text editor and paste it into the WordPress editor and have line breaks / paragraphs retained.  As of Gutenberg 16.1.0 and later, this is not possible with CoBlocks active on the site. 

### To reproduce:

1. Activate Gutenberg 16.1.0 or later
2. Activate CoBlocks (any version)
3. Open a new post
4. In a text editor program (MS Word, Text Edit, etc), type several lines of text with separate paragraphs. 
5. Copy that text, and paste it in the new post. 

### Expected behavior:
The content to paste in separate paragraph blocks.

### Screenshots:

https://github.com/godaddy-wordpress/coblocks/assets/27249804/b44d68ef-dbf0-4641-bb91-68c2de8e7342

### Isolating the problem:

- [ ] This bug happens with no other plugins activated
- [X] This bug happens with a default WordPress theme active
- [ ] This bug happens **without** the Gutenberg plugin active
- [X] I can reproduce this bug consistently using the steps above

Tested a few various CoBlocks versions (3.0.4, 3.0.3, 2.25.5, and 2.0.0) - all encountered the same conflict with Gutenberg 16.1+

### WordPress version:

WP 6.2.2

### Gutenberg version:

Gutenberg 16.1.0 and later reproduce the behavior consistently, with CoBlocks active.

Gutenberg 16.0.0 and earlier do not reproduce the behavior with CoBlocks active.

**Comment by cuemarie** [comment]
Just noting that we continue to see WordPress.com customer reports of this issue (noted on https://github.com/Automattic/wp-calypso/issues/79381).  

At this time, the only solution we can recommend to them is to deactivate the CoBlocks plugin altogether.

**Comment by AnthonyLedesma** [comment]
Thank you for the report @cuemarie.

We tracked the issue down to a `raw` transform definition in the Highlight block. Surprisingly the logic has been untouched for years. Regardless, we have removed the bugged logic and plan to release a new version soon.
https://github.com/godaddy-wordpress/coblocks/pull/2563

**Comment by AnthonyLedesma** [comment]
Resolved with the release of CoBlocks 3.1.3.

related: #2563

**Comment by cuemarie** [comment]
@AnthonyLedesma Thanks so much for the update and fix!
