### ISSUE TITLE
All shape divider block is add flipped classes

### ISSUE THREAD

**Issue by miguelurtado** [godaddy-wordpress/coblocks#2551]
### Describe the bug:
All shape divider block is add classes (is-vertically-flipped is-horizontally-flipped) same not flipped enable in Gutenberg Editor.

### To reproduce:
Create divider block not flipper enable and check the CSS class in frontend page render.

### CoBlocks version:
3.1.0

### WordPress version:
6.3

### Gutenberg version:
15.2-16.1

**Comment by webmandesign** [comment]
Hi,

I can confirm the issue. "Shape Divider" block is always flipped vertically no matter how you set its options.

**Editor view:**

![](https://easycaptures.com/fs/uploaded/1721/1574955119.png)

**Front-end view:**

![](https://easycaptures.com/fs/uploaded/1721/7139632352.png)

(I've logged a [support ticket at WPORG](https://wordpress.org/support/topic/bug-shape-divider-block-is-vertically-flipped/) too.)

**Comment by AnthonyLedesma** [comment]
Hi Folks, the issue is now resolved with the release of CoBlocks 3.1.2. Thanks again for the time to write up a report!

**Comment by webmandesign** [comment]
Thank you @AnthonyLedesma for fast resolution!
