### ISSUE TITLE
Mansonry Gallery does not support Lightbox

### ISSUE THREAD

**Issue by DMOEdetc** [godaddy-wordpress/coblocks#2559]
### Describe the bug:
When I place a Masonry Gallery with lightbox enabled, it does show the cursor correctly but does not load lightbox. When I place a normal gallery with lightbox on the same page, it works.

### To reproduce:
1. Place masonry gallery
2. enable lightbox
3. go to page and try to open image
4. it does not work
5. place gallery on same page below lightbox
6. enable lightbox there too
7. it works

- [x ] This bug happens with no other plugins activated
- [ ] This bug happens with a default WordPress theme active
- [ ] This bug happens **without** the Gutenberg plugin active
- [x ] I can reproduce this bug consistently using the steps above

### WordPress version:
WordPress 6.3

### Gutenberg version:
the one delivered with WordPress 6.3

**Comment by pixelhexe** [comment]
I have the same problem. A few weeks ago everything was fine so it's most likely due to an update (of WordPress or Co-Blocks) which destroyed the lightbox functionality for Masonry Gallery Block.

**Comment by AnthonyLedesma** [comment]
@pixelhexe @DMOEdetc Thank you for contributing. This issue is now resolved with the release of CoBlocks 3.1.3.

related: #2565
