### ISSUE TITLE
ISBAT see the Bottom Wave image style on the live site and in the editor

### ISSUE THREAD

**Issue by cuemarie** [godaddy-wordpress/coblocks#2567]
### Describe the bug:

I should be able to set an image block to use the style `Bottom Wave` or `Top Wave`, but this currently works only in the editor, and not on the live site.

### To reproduce:

1. On a WordPress site, activate GoDaddy 3.1.4 and Gutenberg 16.6.0
2. Create a new page and add an image block
3. Set the image to "Bottom Wave" or "Top Wave" style
4. Publish the page and view the live site

### Expected behavior:
The bottom wave style to appear in both the editor and on the live site

### Screenshots:

![Markup on 2023-09-13 at 14:53:06](https://github.com/godaddy-wordpress/coblocks/assets/27249804/c3ebbf4a-8531-4225-85ae-6424336eb85c)

![Markup on 2023-09-13 at 14:53:28](https://github.com/godaddy-wordpress/coblocks/assets/27249804/7f77bee4-f650-4254-8d3e-b9c45bfd3f00)

### Isolating the problem:

- [x] This bug happens with no other plugins activated
- [x] This bug happens with a default WordPress theme active
- [x] This bug happens **without** the Gutenberg plugin active
- [x] I can reproduce this bug consistently using the steps above

### WordPress version:

6.3.1

### Gutenberg version:

16.6.0, but other versions and GB deactivated also produce the issue.

**Comment by AnthonyLedesma** [comment]
This issue is resolved with CoBlocks 3.1.6
Resolved by https://github.com/godaddy-wordpress/coblocks/pull/2591
