### ISSUE TITLE
ISBAT ...Carousel block doesn't allow images to be enlarged

### ISSUE THREAD

**Issue by vlaisavljevic** [godaddy-wordpress/coblocks#2571]
### Describe the bug:
Images from the Carousel block cannot be enlarged on CoBlocks 3.1.0+

### To reproduce:
- Install and activate version 3.1.0+
- Create a simple Carousel block (Lightbox variation)
- Save the page and try to enlarge images on the front

### Expected behavior:
The images should be enlargeable

### Screenshots:
https://ibb.co/YW4jMjj

**Comment by joeygwynn** [comment]
Hi Folks,

There hasn't been a response to this in quite some time.  If someone can be please this it would be great!

**Comment by AnthonyLedesma** [comment]
This is resolved with CoBlocks 3.1.6

**Comment by AnthonyLedesma** [comment]
Related #2589

**Comment by joeygwynn** [comment]
Wow,

I have confirmed that the lightbox is now working on the site and the mobile site.  Thanks so much!
