### ISSUE TITLE
I am not able to use Lightbox in Masonry Gallery

### ISSUE THREAD

**Issue by krishna36** [godaddy-wordpress/coblocks#2582]
### Describe the bug:

I am not able to use Lightbox in Masonry Gallery. Once I enable the Lightbox, i am able to navigate to 4 images, after 5th Image it takes me the galley and I cannot move further.
I do have a3 Lazy Load plugin installed as well.

If I scroll down the gallery and select any image in the middle of the gallery the Lightbox does not work. 

### To reproduce:
Create a Page.
Create a Masonry Gallery
Enable Light box
Save

Test the page (preview)

### Expected behavior:
Light Box should show all images.

### Screenshots:
<img width="1432" alt="Screen Shot 2024-02-07 at 1 23 45 AM" src="https://github.com/godaddy-wordpress/coblocks/assets/2291735/276cf47a-bf0e-4da1-ab2a-16db32560cb2">
<img width="1392" alt="Screen Shot 2024-02-07 at 1 23 39 AM" src="https://github.com/godaddy-wordpress/coblocks/assets/2291735/3b37c4dc-b6c8-4fd3-8767-6e591542ca51">
<img width="1416" alt="Screen Shot 2024-02-07 at 1 21 35 AM" src="https://github.com/godaddy-wordpress/coblocks/assets/2291735/fd798f70-04cd-4654-bc1b-22fd6e734a59">
<img width="1428" alt="Screen Shot 2024-02-07 at 1 21 21 AM" src="https://github.com/godaddy-wordpress/coblocks/assets/2291735/18252fc0-999e-46b7-b1da-950ade101bcb">

### Isolating the problem:

- [ ] This bug happens with no other plugins activated
- [ ] This bug happens with a default WordPress theme active
- [ ] This bug happens **without** the Gutenberg plugin active
- [ ] I can reproduce this bug consistently using the steps above

**Comment by gdaleks** [comment]
Tested on a local installation with Go and CoBlocks and wasn't able to replicate the issue. Responded in the thread on WordPress.org: https://wordpress.org/support/topic/i-am-not-able-to-use-lightbox-in-masonry-gallery/#post-17442923
