### ISSUE TITLE
Can't Completely Uninstall CoBlocks without wpex-eb-settings-plugin error

### ISSUE THREAD

**Issue by designman22** [godaddy-wordpress/coblocks#2587]
### Describe the bug:

"I should be able to deactivate and delete the CoBlocks plugin without WordPress throwing the following error when I edit block templates in a theme: **wpex-eb-settings-plugin has encountered an error and cannot be rendered.** This error happens on a site hosted on GoDaddy Managed WordPress" 

### To reproduce:

1. Go to 'plugins section of WordPress.'
2. Click on 'deactivate' and then click 'delete' and flush cache.
3. Navigate 'to the Site Editor in WordPress, select a template there, and click Edit'
4. See error 'wpex-eb-settings-plugin has encountered an error and cannot be rendered'

### Expected behavior:
The plugin's code should be completely removed after the plugin has been deleted, and it should be possible to edit WordPress templates and patterns without an error being thrown.

### Isolating the problem:

- [x ] This bug happens with no other plugins activated
- [ x] This bug happens with a default WordPress theme active
- [x] This bug happens **without** the Gutenberg plugin active
- [ x] I can reproduce this bug consistently using the steps above

### WordPress version:

Version 6.4.3

**Comment by AnthonyLedesma** [comment]
Hi @designman22,

Thank you for reporting the issue with `wpex-eb-settings-plugin` while deactivating the plugin. I understand that a new version of both CoBlocks and the EB settings plugin were released which should resolve the issue you had experienced. Please let us know if the issues persist after the latest updates. 

Best

**Comment by AnthonyLedesma** [comment]
Should be resolved now.
