### ISSUE TITLE
ISBAT ...

### ISSUE THREAD

**Issue by jbachman04** [godaddy-wordpress/coblocks#2604]
### Describe the bug:

When viewing a page in the editor that has the "Services" block and the "Services" block has several entries in it, only the first entry is showing up after the latest update to the CoBlocks plugin.

### To reproduce:

1. Open a page that you have the "Services" block on that has multiple entries in the editor.
2. If you had multiple entries in the "Services" block, only the first one should be showing up in the editor.

As long as the AutoSave doesn't save the page you are viewing or you manually press Update, the actual published page will display fine to the general public. It only appears to be having issues on the backend.

### Expected behavior:

When opening a page in the editor on WordPress, all previous entries in the "Services" block should appear.
### Screenshots:

![image](https://github.com/godaddy-wordpress/coblocks/assets/3921724/e7b64c25-baa2-4e3c-a4b3-a289de42912f)

![image](https://github.com/godaddy-wordpress/coblocks/assets/3921724/86179d9b-0a4e-402e-a10a-f96c40c6ca9c)

### Isolating the problem:

- [x] This bug happens with no other plugins activated
- [x] This bug happens with a default WordPress theme active
- [x] This bug happens **without** the Gutenberg plugin active
- [x ] I can reproduce this bug consistently using the steps above

### WordPress version:

6.5.2
### Gutenberg version:

Unknown... No Gutenberg Plugin is listed...

**Comment by jbachman04** [comment]
Update: I have tried reloading from a backup and still get the same results. I also tried installing and activating and then deactivating the Gutenberg plugin (latest version) and even tried downgrading the CoBlocks plugin to an earlier version along with an earlier version of WordPress and the same thing still happens. 

Any help on this matter would be great as I really don't want to have to recreate over 40 profiles on this site.

**Comment by rickcurran** [comment]
I am also seeing this issue occurring, it is a significant loss of block data in a page with almost 70 Services blocks columns in place. I am however struggling to consistently reproduce the issue, I first made a test page, added some services blocks, saved the page and then reloaded and I saw the same loss of block data for some of them. But I then made a second test page and I have yet to see this page fail to work. As such I cannot consistently reproduce it, all I can see is that there is definitely an issue but I can't say if there are mitigating circumstances such as clashes with other plugins etc.

**Comment by rickcurran** [comment]
Hi, I've been digging further into this to see what might be happening and I did notice one thing about the page that I was experiencing the error on. Each Services block on the page was set to 3 x Services columns, but looking at the underlying block markup there were 4 there, with the last one containing no block data, title description, image etc. Whereas when I made a new test page with Services blocks the only block markup there was the actual 3 x Services columns.

Here's a sample block markup from the page I was getting the data loss on:

`
    <div class="wp-block-coblocks-services">
        <div class="has-columns has-3-columns has-responsive-columns has-medium-gutter">
            
            <div class="wp-block-coblocks-service">
                <figure class="wp-block-coblocks-service__figure"><img src="https://creativedundee.com/wp-content/uploads/2021/01/Andy_alt2.jpg" alt="" style="object-position:40% 56.99999999999999%" /></figure>
                <div class="wp-block-coblocks-service__content">
                    
                    <h3 class="wp-block-heading has-text-align-none" id="andy-robertson">Andy Robertson</h3>
                    

                    
                    <p class="has-text-align-none">Andy is a designer, artist and community worker,&nbsp;collaborating with young people through Hot Chocolate Trust. <a href="https://www.instagram.com/p/Ca6x9CTIiqb/" target="_blank" rel="noreferrer noopener">Read more...</a></p>
                    
                </div>
            </div>
            

            
            <div class="wp-block-coblocks-service">
                <figure class="wp-block-coblocks-service__figure"><img src="https://creativedundee.com/wp-content/uploads/2021/01/F-Canavan01.jpg" alt="" style="object-position:51% 39%" /></figure>
                <div class="wp-block-coblocks-service__content">
                    
                    <h3 class="wp-block-heading has-text-align-none" id="fiona-canavan">Fíona Canavan</h3>
                    

                    
                    <p class="has-text-align-none">Fíona is an architect who loves collaboration and bringing architecture to a wider audience. <a href="https://www.instagram.com/p/Cao4ojVs_Fa/" target="_blank" rel="noreferrer noopener">Read more...</a></p>
                    
                </div>
            </div>
            

            
            <div class="wp-block-coblocks-service">
                <figure class="wp-block-coblocks-service__figure"><img src="https://creativedundee.com/wp-content/uploads/2020/11/Rhiannon-Mudaliar-by-David-P-Scott-NET-2.jpg" alt="" style="object-position:63% 37%" /></figure>
                <div class="wp-block-coblocks-service__content">
                    
                    <h3 class="wp-block-heading has-text-align-none" id="rhiannon-mudaliar">Rhiannon Mudaliar</h3>
                    

                    
                    <p class="has-text-align-none">Rhiannon is a director and artist, telling powerful stories that amplify voices and challenge the status quo. <a href="https://www.instagram.com/p/CaFLUchMdIW/" target="_blank" rel="noreferrer noopener">Read more...</a></p>
                    
                </div>
            </div>
            

            
            <div class="wp-block-coblocks-service">
                <div class="wp-block-coblocks-service__content">
                    
                    <h3 class="wp-block-heading has-text-align-none"></h3>
                    

                    
                    <p class="has-text-align-none"></p>
                    
                </div>
            </div>
            
        </div>
    </div>
    `

You'll see that it's set to 3 columns but there are four `wp-block-coblocks-service` blocks contained within the parent `wp-block-coblocks-services` block. So I think that somehow this extra one may be part of the issue as to why this is occurring?

**Comment by AnthonyLedesma** [comment]
Hey folks, I think this issue may be resolved with #2613 released in version 3.1.11 of CoBlocks. Please re-open the issue if this is still happening for you.
