### ISSUE TITLE
ISBAT Cannot access Site design to change fonts

### ISSUE THREAD

**Issue by sawwd** [godaddy-wordpress/coblocks#2608]
### Describe the bug:
I should be able to access the Site design. My setup is the latest version shipped by GoDaddy hosting: Wordpress, CoBlocks and Go theme.

### To reproduce:

Go to pages and try to access the Site design from the top right side.

### Expected behavior:

I should able to access the Site design to change the fonts etc.

### Screenshots:

![2024-04-26_16-49-52](https://github.com/godaddy-wordpress/coblocks/assets/13658340/a9836f4e-1e30-46a0-91a9-e6fe435bea67)

### Isolating the problem:

- [ x] This bug happens with no other plugins activated
- [ x] This bug happens with a default WordPress theme active
- [ x] This bug happens **without** the Gutenberg plugin active
- [ x] I can reproduce this bug consistently using the steps above

### WordPress version:

6.5.2

**Comment by AnthonyLedesma** [comment]
Hi @sawwd,

The latest version of CoBlocks 3.1.9 should resolve this issue. Thank you for taking the time to report this bug.

Best regards

**Comment by AnthonyLedesma** [comment]
Resolved by https://github.com/godaddy-wordpress/coblocks/pull/2610
