### ISSUE TITLE
The buttons within the Service block are disappearing.

### ISSUE THREAD

**Issue by ntomic-godaddy** [godaddy-wordpress/coblocks#2611]
### Describe the bug:
When a Button element is added inside the Service block, they disappear after saving the page. 

### To reproduce:
1. Create a new page
2. Add Service block
3. Add Button element within the Services block: 
![image](https://github.com/godaddy-wordpress/coblocks/assets/120448842/3ba62c8b-29ff-45ab-970c-1afc8ed6f92e)
4. Save page, button is visible on the front-end
5. Re-open page editor
6. Notice that button disappeared from the editor
7. If the page is saved again, button is not visible even on the front-end

### Expected behavior:
Button should be visible and editable in the editor, and on the frontend

### Isolating the problem:

- [x] This bug happens with no other plugins activated
- [x] This bug happens with a default WordPress theme active
- [x] This bug happens **without** the Gutenberg plugin active
- [x] I can reproduce this bug consistently using the steps above

**Comment by AnthonyLedesma** [comment]
This issue is resolved with #2613
