### ISSUE TITLE
ISBAT see an excerpt generated from content within the Columns block.

### ISSUE THREAD

**Issue by edgarwe** [godaddy-wordpress/coblocks#735]
**Describe the bug**
All content in row aren't in excerpt it's like invisible.

**To Reproduce**

1. Go to 'a post'
2. Add a row and content in
3. Go to 'single.php'
4. Add 'the_excerpt(); or echo get_the_excerpt();'
5. Look a live post
6. See problems

**Expected behavior**
View the content of row in any excerpt.

**Isolating the problem:**
Mark completed items with an [x].

-   [x] This bug happens with no other plugins activated
-   [x] This bug happens with a default WordPress theme active
-   [ ] This bug happens **without** the Gutenberg plugin active
-   [x] I can reproduce this bug consistently using the steps above

**WordPress Version**
Wordpress 5.2.2

**Comment by paranoia1906** [comment]
Doing some research on this issue today. No success by using the `excerpt_allowed_blocks` filter but Ill take a another stab at finding a way to add to the block exception list.

Testing some 3rd party blocks I find that the issue of not being included within excerpts is something that all tested custom blocks have an issue with right now. I was not able to generate excerpts of Kadence, Atomic, Ultimate, Stackable, and Block Lab Blocks. All fail to render text content using excerpts. This tells us that these development teams have yet to address/fix the issue.

**Comment by EvanHerman** [comment]
Looks like this is because only the `core/columns` block is passed through `_excerpt_render_inner_columns_blocks `.

https://github.com/WordPress/WordPress/blob/master/wp-includes/blocks.php#L163-L166

There needs to be a filter there or something where we can specify custom blocks to also pass content through `_excerpt_render_inner_columns_blocks`.

**Comment by jrtashjian** [comment]
I'm going to work at pushing that ticket forward and submit a patch. We need to be able to pass in blocks with innerBlocks that we want parsed for the excerpt.

**Comment by jrtashjian** [comment]
I'm going to close this issue since it's a bug that needs to be resolved in WordPress core. As of today this issue is tracked in core and has been assigned to the 5.7 release.

https://core.trac.wordpress.org/ticket/47637
