### ISSUE TITLE
Logos using the black & white filter are completely black

### ISSUE THREAD

**Issue by mmtr** [godaddy-wordpress/coblocks#748]
**Describe the bug**
With the Black & White filter enabled in a Logos & Badges block, images are completely black except for transparent pixels.

<img width="738" alt="Screen Shot 2019-08-17 at 13 36 32" src="https://user-images.githubusercontent.com/1233880/63206677-1053ee80-c0f4-11e9-8d80-29653eff1aa9.png">

**To Reproduce**
1. Insert a Logo & Badges block.
1. Add some images.
1. Toggle the Black & White filter, under the Logos Settings.

**Expected behavior**
I was expecting a grayscale. Actually, I can get it after disabling some styles of the `.wp-block-coblocks-logos.has-filter-grayscale img` selector in the browser devtools:

<img width="1164" alt="Screen Shot 2019-08-17 at 13 39 10" src="https://user-images.githubusercontent.com/1233880/63206725-cddee180-c0f4-11e9-9d02-8f0d16ad8521.png">

**Isolating the problem:**
-   [x] This bug happens with no other plugins activated
-   [x] This bug happens with a default WordPress theme active
-   [x] This bug happens **without** the Gutenberg plugin active
-   [x] I can reproduce this bug consistently using the steps above

**WordPress Version**
5.2

**Gutenberg Version**
6.3.0

**Comment by richtabor** [comment]
@mmtr This is caused by the `brightness(0)` part of the grayscale filter class. You could overwrite that class and include it in your theme (without the brightness part) and it'll just do grayscale, not black and white.

**Comment by mmtr** [comment]
@richtabor Thanks. So the brightness filter is intended? Note that is causing images with solid backgrounds be displayed as black boxes.

Example:

Logo with white background (with no transparent pixels):
<img width="300" src="https://user-images.githubusercontent.com/1233880/63310721-c1e26200-c336-11e9-9821-4cb31d39d03c.png">

Logo with green background:
<img width="300" src="https://user-images.githubusercontent.com/1233880/63310755-df173080-c336-11e9-8940-d82c0dbaa5c1.png">

Logos with B&W filter enabled:
![Aug-20-2019 10-41-43](https://user-images.githubusercontent.com/1233880/63310837-2ac9da00-c337-11e9-808d-a335cd3d2b7c.gif)

**Comment by richtabor** [comment]
> Thanks. So the brightness filter is intended? Note that this is causing images with solid backgrounds to be displayed as black boxes.

Correct, to make transparent images black (instead of monotone). We could possibly consider a selector control which displays if Black & White is toggled on, to give an option between Monotone and true black/white.

**Comment by richtabor** [comment]
It may be beneficial to have monotone set to default, although this may require a deprecation.

**Comment by richtabor** [comment]
Here's the logic we need to put in place. 

When the current "Black & White" toggle is turned on, a SelectControl labeled "Filter Style" should be visible beneath it, which lets users choose between `Grayscale` or `Black`.

Currently the default value is essentially the `Black & White` option, though I would like to make "Grayscale" the default. This will likely create a deprecation issue, though we'll have to investigate that. 

Per utility structuring, `Black` should add the`f-grayscale-100 f-brightness-0` classes, whereas `Grayscale` would just add the `f-grayscale-100` utility class. 

```
.f-grayscale-100 {
     filter:  grayscale(1);
}

.f-brightness-100 {
     filter: brightness(0);
}
```

**Comment by richtabor** [comment]
Thinking a good option would be to remove the toggle and use a button group instead:
<img width="1316" alt="Screen Shot 2020-01-10 at 11 39 39 AM" src="https://user-images.githubusercontent.com/1813435/72169866-e5698000-339d-11ea-9625-5b8d4ef85c16.png">

Here's the [Figma mock](https://www.figma.com/file/QHNIUWXnyWRjUmk7Tc8mC1/Logo-Block-Grayscale-Black?node-id=0%3A1).

**Comment by jrtashjian** [comment]
I think we should utilize the Styles panel and remove this custom control. The Styles panel has a nice preview of the block which can show what the grayscale or black image filter would look like before switching. It also allows the user to set a default which will persist each time the Logos & Badges block is used.

**Comment by richtabor** [comment]
> I think we should utilize the Styles panel and remove this custom control. 

Great idea! I'll update the spec.
