### ISSUE TITLE
ISBAT disable the typography controls

### ISSUE THREAD

**Issue by AnthonyLedesma** [godaddy-wordpress/coblocks#751]
**Is this enhancement related to a problem? Please describe.**
Consider the following scenario. If I were to create a number of core blocks and edit those blocks Typography Controls, what would happen if I decide to disable CoBlocks plugin down the road? The answer is either block invalidation or automatic revert to core supported styles. 

### Typography Controls in use on core blocks
![image](https://user-images.githubusercontent.com/30462574/63348704-aa8f7e80-c30e-11e9-9fcb-e1fc66a96315.png)

### With CoBlocks disabled
![image](https://user-images.githubusercontent.com/30462574/63348788-ddd20d80-c30e-11e9-9b7b-8bb2f05bb138.png)

**Describe the solution you'd like**
An option to disable the Typography Controls across any core blocks such as a checkbox or toggle on the CoBlocks menu page.

**Describe alternatives you've considered**
When CoBlocks is disabled and core blocks have been modified we still have the option to convert to a valid block type.

![typographyConvertBlock](https://user-images.githubusercontent.com/30462574/63348109-78315180-c30d-11e9-91b4-a3d39cf279fb.gif)

**Additional context**
The following core blocks have Typography Controls enabled:
- paragraph
- heading
- cover
- button
- list

Request inspired by WordPress.org support request.
https://wordpress.org/support/topic/typography-control-panel-setting-to-deactivate/
https://wordpress.org/support/topic/hide-typography-controls-to-users/

**Comment by richtabor** [comment]
Yea I've been thinking how we could make this happen. I think the best course of action would be to have some sort of option within Gutenberg to turn off Advanced Typography controls.

**Comment by richtabor** [comment]
Related #637

**Comment by FOLIOBOOK** [comment]
I have spent hours searching for a solution to the typography styles problem that this feature cannot be turned off for authors. The blog is gradually turning into a Christmas tree! How can we forget such a feature when the plugin is incredible ... Very frustrating. Is there a solution so far?
