### ISSUE TITLE
ISBAT tab out of the Social Profiles link popover

### ISSUE THREAD

**Issue by richtabor** [godaddy-wordpress/coblocks#783]
**Describe the bug**
While the Social Profiles links are tabbable, the popover themselves are not. Pressing tab or enter does not close the popover, as it should. 

**To Reproduce**

1. Add a Social Profiles block
2. Tab to a particular icon button
3. Press Enter to reveal popover
4. Type in a link and try to close

**Expected behavior**
The block can be operated via tabs.

**Comment by paranoia1906** [comment]
I tinkered with the popovers to try and get this request but I kept running into unexpected behavior. I think it has to do with the way that popovers are implemented in core. 

**tabindex removed from popovers**
![image](https://user-images.githubusercontent.com/30462574/64194030-05f35d80-ce33-11e9-9ae7-b46b4add5ef2.png)

**Comment by richtabor** [comment]
@paranoia1906 Try looking into how the ESC key gets you out of the block inserter.

**Comment by EvanHerman** [comment]
I'm not sure if this is still relevant. I just tested and it does appear that after entering a URL, hitting enter or tabbing to the arrow and hitting enter does close the popover.

If someone could double check to confirm, we can close this issue.

**Comment by AnthonyLedesma** [comment]
I think this issue is still relevant today. Not able to tab out of the text input box once it's been selected.

**Comment by jrtashjian** [comment]
This is still a relevant bug.

We should implement a similar UI to adding an inline link within a paragraph. This UI includes a button to add the link and the UI can be closed by clicking that button and by hitting enter. Esc seems to keep the popover open but I think we can just make it close for our case.

![image](https://user-images.githubusercontent.com/375788/102273102-d107fe80-3eef-11eb-91b3-da766d15492d.png)

**Comment by jlemay-godaddy** [comment]
Fixed in #2050
