### ISSUE TITLE
wp.blockEditor.RichText formattingControls prop is deprecated

### ISSUE THREAD

**Issue by richtabor** [godaddy-wordpress/coblocks#799]
**Describe the bug**
Gutenberg added a deprecation notice for the `formattingControls` prop, which limits which formatting controls are available for RichText components. This one is a bit tricky, as the suggested prop `allowedFormats` does not work with current WordPress core. 

We are currently using`formattingControls` on the Click to Tweet block, Food Item, and Pricing Table blocks, to limit which formats are available to those blocks. For example, the Food Item block does not allow inline images, permalink or strikethrough formats - but does Bold and Italic.

**Comment by jrtashjian** [comment]
Closing. Fixed in #1701
