### ISSUE TITLE
ISBAT ensure the integrity of the Social Profiles block through automated tests

### ISSUE THREAD

**Issue by jrtashjian** [godaddy-wordpress/coblocks#876]
Automated tests need to be added to the `social-profiles` block which follow the groundwork from #835.

#### Tests Required:
- [x] The save function #1057
- [x] Block transforms #1237
- [x] Block deprecation (not applicable)

#### AC
- Any attribute that modifies the serialized block output needs to have tests.
- Any existing transforms to or from a block needs to have tests (if applicable).
- Any existing block deprecations need to have tests (if applicable).

**Comment by AnthonyLedesma** [comment]
Closing with the completion of #1237.
