### ISSUE TITLE
ISBAT align buttons within the Columns block

### ISSUE THREAD

**Issue by AnthonyLedesma** [godaddy-wordpress/coblocks#889]
**Describe the bug**
When setting the alignment options on Column block I would expect all child/inner blocks to be effected by this selection. I found that Buttons block is not behaving as expected. 

**To Reproduce**
- Add a row with one or more columns.
  * Also effects blocks that use columns such as Media Card block.
- Add child blocks to the column block including Button blocks.
- Set alignment options on the column block to see the issue.

**Screenshots**
**Without Gutenberg 6.4 running, only the CoBlocks Buttons block is effected.**
![ColumnBlockAlignButtonsNoGB](https://user-images.githubusercontent.com/30462574/65169296-1a228780-d9fb-11e9-8ceb-9d73dca54369.gif)

**With Gutenberg 6.4 running both the Buttons block and core Button block have a similar issue.** 
![ColumnBlockAlignButtons](https://user-images.githubusercontent.com/30462574/65168770-0d516400-d9fa-11e9-89a7-afc9c895f0fe.gif)

**Expected behavior**
Expected all inner blocks (except for full width blocks like Shape Divider block) to be effected by parent alignment options.

**Isolating the problem:**
Mark completed items with an [x].

-   [X] This bug happens with no other plugins activated
-   [X] This bug happens with a default WordPress theme active
-   [X] This bug happens **without** the Gutenberg plugin active
-   [X] I can reproduce this bug consistently using the steps above

**WordPress Version**
What version of WordPress are you using?
5.2.3

**Gutenberg Version**
What version of the Gutenberg plugin are you using? (If any)
6.4 (Optional)

**Comment by jrtashjian** [comment]
Closing: As of today this seems to be working as expected.
