### ISSUE TITLE
ISBAT set attributes on CoBlocks blocks when extending

### ISSUE THREAD

**Issue by addzycullen** [godaddy-wordpress/coblocks#896]
**Describe the bug**
I've extended a number of blocks on a site I'm working on with some extra Inspector Controls that are used to set classes. This all works perfectly, except with CoBlocks blocks.

The codeI'm using works for every block(Core and Other Block Plugins) that I have tried except CoBlocks, particularly the Row & Column blocks.I assume there's something in the code preventing this?

Has this issue been seen by anybody else?

Extension code is available below...

```
const addAlignmentAttributes = ( settings, name ) => {
	if ( typeof settings.attributes !== 'undefined' ) {
		settings.attributes = Object.assign( settings.attributes, {
			contentAlignCenter: {
				type: 'boolean',
				default: false,
			},
		} );
	}
	return settings;
};

const addAlignmentControls = createHigherOrderComponent( BlockEdit => {
	return props => {
		const { name, attributes, setAttributes, isSelected } = props;
		const { contentAlignCenter } = props.attributes;

		return (
			<Fragment>
				<BlockEdit { ...props } />
				<InspectorControls>
					<PanelBody title={ __( 'Content Alignment Options' ) } initialOpen={ false }>
						<ToggleControl label={ __( 'Vertical Align Center' ) } checked={ contentAlignCenter } onChange={ () => setAttributes( { contentAlignCenter: ! contentAlignCenter } ) } />
					</PanelBody>
				</InspectorControls>
			</Fragment>
		);
	};
}, 'addAlignmentControls' );

function applyExtraClass( extraProps, blockType, attributes ) {
	const { contentAlignCenter } = attributes;

	if ( typeof contentAlignCenter !== 'undefined' && contentAlignCenter ) {
		extraProps.className = classnames( extraProps.className, 'sophia-block--vert-center' );
	}

	return extraProps;
}

addFilter( 'blocks.registerBlockType', 'sophia/custom/attributes', addAlignmentAttributes );
addFilter( 'editor.BlockEdit', 'sophia/attributes', addAlignmentControls );
addFilter( 'blocks.getSaveContent.extraProps', 'sophia/applyExtraClass', applyExtraClass );
```

**To Reproduce**
1.Use the filters/methods provided and toggle on vertical alignment centering in the InspectorControls.
2. Update Post & Refresh
3. Go back to the toggle in your InspectorControls and you'll see its off again. attribute does not store.

**Expected behavior**
Toggling Custom Inspector Control should store an attribute and display a class on the frontend/

**Isolating the problem:**

- This bug happens with no other plugins activated
- This bug happens with a default WordPress theme active
- I can reproduce this bug consistently using the steps above

**WordPress Version**
5.2.3

**Gutenberg Version**
WP Core 5.2.3

**Comment by richtabor** [comment]
Have you tried extending other non-core blocks with the same result?

**Comment by addzycullen** [comment]
Yes, I tried a few. 

Blocks I have created and one or two other plugins

**Comment by richtabor** [comment]
Hmm, does it happen with only the Row block, or all our blocks?

**Comment by gianlucariccobono** [comment]
@addzycullen Did you find a solution for this? I have exactly the same problem.

**Comment by addzycullen** [comment]
Sorry about the delayed response.

@richtabor All of your blocks unfortunately :(

@gianlucariccobono No I didn't :(

**Comment by jrtashjian** [comment]
This bug is still valid. I did some investigating and it looks like we are not passing the `className` prop to the save function's output properly in most of our blocks - we are completely overriding it. This is most definitely incorrect.

This is an example of what I'm seeing in our codebase:

```
let classes = classnames( {
	[ `coblocks-row--${ id }` ]: id,
} );
```

I'm not sure when well get this bug resolved but if anyone would like to take a stab at it you will most likely only need to add `props.className` to the `classnames()` call so they are all merged properly.

**Comment by AnthonyLedesma** [comment]
Hi @addzycullen, It's been a while since you've opened this issue but I was testing it again today and could not replicate the report. I've added the extension filters and have been able to successfully persist the attributes across saves as well as display the className on the front-end as the filter intends. Here is the exact filters I used including the relevant imports.

```javascript
import { __ } from '@wordpress/i18n';
import { addFilter } from '@wordpress/hooks';
import { createHigherOrderComponent } from '@wordpress/compose';
import { Fragment } from '@wordpress/element';
import { InspectorControls } from '@wordpress/block-editor';
import { PanelBody, ToggleControl } from '@wordpress/components';
import classnames from 'classnames';

const addAlignmentAttributes = ( settings, name ) => {
	if ( typeof settings.attributes !== 'undefined' ) {
		settings.attributes = Object.assign( settings.attributes, {
			contentAlignCenter: {
				type: 'boolean',
				default: false,
			},
		} );
	}
	return settings;
};

const addAlignmentControls = createHigherOrderComponent( ( BlockEdit ) => {
	return ( props ) => {
		const { name, attributes, setAttributes, isSelected } = props;
		const { contentAlignCenter } = props.attributes;

		return (
			<Fragment>
				<BlockEdit { ...props } />
				<InspectorControls>
					<PanelBody initialOpen={ false } title={ __( 'Content Alignment Options' ) }>
						<ToggleControl checked={ contentAlignCenter } label={ __( 'Vertical Align Center' ) } onChange={ () => setAttributes( { contentAlignCenter: ! contentAlignCenter } ) } />
					</PanelBody>
				</InspectorControls>
			</Fragment>
		);
	};
}, 'addAlignmentControls' );

function applyExtraClass( extraProps, blockType, attributes ) {
	const { contentAlignCenter } = attributes;

	if ( typeof contentAlignCenter !== 'undefined' && contentAlignCenter ) {
		extraProps.className = classnames( extraProps.className, 'sophia-block--vert-center' );
	}

	return extraProps;
}

addFilter( 'blocks.registerBlockType', 'sophia/custom/attributes', addAlignmentAttributes );
addFilter( 'editor.BlockEdit', 'sophia/attributes', addAlignmentControls );
addFilter( 'blocks.getSaveContent.extraProps', 'sophia/applyExtraClass', applyExtraClass );
```
 
![ExtendingBlockAttributes](https://user-images.githubusercontent.com/30462574/146225286-4531e386-cbf0-4ef7-88ef-ab3ba34bcc89.gif)

**Comment by AnthonyLedesma** [comment]
I wanted to point out as well that the example provided previously is still true however it does not seem to be related to this issue since the filter still applies the className through `extraProps` and does not requre the save function logic.

**Comment by AnthonyLedesma** [comment]
I am going to close this issue as no longer an issue. I've done a bit of looking on this but was not able to identify what exactly has resolved this issue. If you find that this issue is still relevant please let us know.
