### ISSUE TITLE
ISBAT crop or auto-height images in Carousel Block

### ISSUE THREAD

**Issue by AnthonyLedesma** [godaddy-wordpress/coblocks#944]
**Is your feature request related to a problem? Please describe.**
The Carousel block will apply auto-height to images dependent on the image height. We should explore methods to give the user better control over whether the image will effectively crop or will resize accordingly. 

**Describe the solution you'd like**
Something we could consider is adding a "Crop" toggle option which when toggled essentially makes it autoheight and one image across only.

**Describe alternatives you've considered**
At this time the alternatives are custom CSS or editing the image prior to upload to Carousel block.

**Inspired by wp.org support request**
https://wordpress.org/support/topic/carousel-block-object-fit-contain/
https://wordpress.org/support/topic/images-uncropped-in-the-carousel-block

**Comment by lorenzaME** [comment]
Hi I think that the Carousel block should not crop images, is there a chance to have this behaviour?
Hope so and  that you will assign this task to improve the carousel behaviour bacause it is quite frustrating having photos cropped.
Thanks
Lorenza

**Comment by gmariani** [comment]
Still an issue. I have square images that get the top and bottoms cropped off. And can't display just a single image per slide either, so you see 1/4 of the images before and after, unlike any other slide show plugin you'd expect.

**Comment by AnthonyLedesma** [comment]
Thank you for contributing. I am closing this issue and linking back to a primary issue regarding refactoring of the Carousel gallery block where we plan to address this ask.
https://github.com/godaddy-wordpress/coblocks/issues/2077
