### ISSUE TITLE
ISNBAT set Cover block Typography Controls

### ISSUE THREAD

**Issue by AnthonyLedesma** [godaddy-wordpress/coblocks#947]
**Describe the bug**
At this time the Cover block has CoBlocks Typography Controls functionality. This is an issue because the Typography Controls are already given to any Inner blocks (Heading, Paragraph) thus  having the functionality on Cover block is adds complexity and redundancy and should be disabled.

**To Reproduce**

1. Add Cover block.
2. Click block and view toolbar.
3. Notice icon for Typography Controls.

**Screenshots**
Typography Controls icon within the toolbar. 
![image](https://user-images.githubusercontent.com/30462574/66140768-8b476a80-e5b7-11e9-938c-bece5bfd95e2.png)

**Expected behavior**
We should find a way to disable the additional functionality for Cover block but allow for inner blocks. We should also ensure that block deprecations are created if needed. 

An experimental branch has been started under `remove-text-settings-coverblock` where some work has been completed. Beware of missing deprecation in this branch. 

**Isolating the problem:**
Mark completed items with an [x].

-   [X] This bug happens with no other plugins activated
-   [X] This bug happens with a default WordPress theme active
-   [X] This bug happens **without** the Gutenberg plugin active
-   [X] I can reproduce this bug consistently using the steps above

**WordPress Version**
What version of WordPress are you using?
5.2.3

**Gutenberg Version**
What version of the Gutenberg plugin are you using? (If any)
N/A

**Comment by paranoia1906** [comment]
Related issue: 
https://github.com/godaddy/coblocks/issues/751
